// Goals 7-12 translation data
// [code, en, ja, es]

const DATA_7_12 = {
  7: [
    [
      '7.1',
      'By 2030, ensure universal access to affordable, reliable and modern energy services',
      '2030年までに、安価かつ信頼できる現代的エネルギーサービスへの普遍的アクセスを確保する',
      'De aqui a 2030, garantizar el acceso universal a servicios energeticos asequibles, fiables y modernos',
    ],
    [
      '7.2',
      'By 2030, increase substantially the share of renewable energy in the global energy mix',
      '2030年までに、世界のエネルギーミックスにおける再生可能エネルギーの割合を大幅に拡大させる',
      'De aqui a 2030, aumentar considerablemente la proporcion de energia renovable en el conjunto de fuentes energeticas',
    ],
    [
      '7.3',
      'By 2030, double the global rate of improvement in energy efficiency',
      '2030年までに、世界全体のエネルギー効率の改善率を倍増させる',
      'De aqui a 2030, duplicar la tasa mundial de mejora de la eficiencia energetica',
    ],
    [
      '7.a',
      'By 2030, enhance international cooperation to facilitate access to clean energy research and technology, including renewable energy, energy efficiency and advanced and cleaner fossil-fuel technology, and promote investment in energy infrastructure and clean energy technology',
      '2030年までに、再生可能エネルギー、エネルギー効率及び先進的かつ環境負荷の低い化石燃料技術などのクリーンエネルギーの研究及び技術へのアクセスを促進するための国際協力を強化し、エネルギー関連インフラとクリーンエネルギー技術への投資を促進する',
      'De aqui a 2030, aumentar la cooperacion internacional para facilitar el acceso a la investigacion y la tecnologia relativas a la energia limpia, incluidas las fuentes renovables, la eficiencia energetica y las tecnologias avanzadas y menos contaminantes de combustibles fosiles, y promover la inversion en infraestructura energetica y tecnologias limpias',
    ],
    [
      '7.b',
      'By 2030, expand infrastructure and upgrade technology for supplying modern and sustainable energy services for all in developing countries, in particular least developed countries, small island developing States and landlocked developing countries',
      '2030年までに、各々の支援プログラムに沿って開発途上国、特に後発開発途上国及び小島嶼開発途上国、内陸開発途上国のすべての人々に現代的で持続可能なエネルギーサービスを供給できるよう、インフラ拡大と技術向上を行う',
      'De aqui a 2030, ampliar la infraestructura y mejorar la tecnologia para prestar servicios energeticos modernos y sostenibles para todos en los paises en desarrollo, en particular los paises menos adelantados, los pequenos Estados insulares en desarrollo y los paises en desarrollo sin litoral',
    ],
  ],
  8: [
    [
      '8.1',
      'Sustain per capita economic growth in accordance with national circumstances and, in particular, at least 7 per cent gross domestic product growth per annum in the least developed countries',
      '各国の状況に応じて、一人当たり経済成長率を持続させる。特に後発開発途上国は少なくとも年率7%の成長率を保つ',
      'Mantener el crecimiento economico per capita de conformidad con las circunstancias nacionales y, en particular, un crecimiento del producto interno bruto de al menos el 7% anual en los paises menos adelantados',
    ],
    [
      '8.2',
      'Achieve higher levels of economic productivity through diversification, technological upgrading and innovation, including through a focus on high value added and labour-intensive sectors',
      '高付加価値セクターや労働集約型セクターに重点を置くことなどにより、多様化、技術向上及びイノベーションを通じた高いレベルの経済生産性を達成する',
      'Lograr niveles mas elevados de productividad economica mediante la diversificacion, la modernizacion tecnologica y la innovacion, entre otras cosas centrando la atencion en los sectores con gran valor anadido y un uso intensivo de la mano de obra',
    ],
    [
      '8.3',
      'Promote development-oriented policies that support productive activities, decent job creation, entrepreneurship, creativity and innovation, and encourage the formalization and growth of micro-, small- and medium-sized enterprises, including through access to financial services',
      '生産活動や適切な雇用創出、起業、創造性及びイノベーションを支援する開発重視型の政策を促進するとともに、金融サービスへのアクセス改善などを通じて中小零細企業の設立や成長を奨励する',
      'Promover politicas orientadas al desarrollo que apoyen las actividades productivas, la creacion de puestos de trabajo decentes, el emprendimiento, la creatividad y la innovacion, y fomentar la formalizacion y el crecimiento de las microempresas y las pequenas y medianas empresas, incluso mediante el acceso a servicios financieros',
    ],
    [
      '8.4',
      'Improve progressively, through 2030, global resource efficiency in consumption and production and endeavour to decouple economic growth from environmental degradation',
      '2030年までに、世界の消費と生産における資源効率を漸進的に改善させ、先進国主導の下、持続可能な消費と生産に関する10年計画枠組みに従い、経済成長と環境悪化の分断を図る',
      'Mejorar progresivamente, de aqui a 2030, la produccion y el consumo eficientes de los recursos mundiales y procurar desvincular el crecimiento economico de la degradacion del medio ambiente',
    ],
    [
      '8.5',
      'By 2030, achieve full and productive employment and decent work for all women and men, including for young people and persons with disabilities, and equal pay for work of equal value',
      '2030年までに、若者や障害者を含むすべての男性及び女性の、完全かつ生産的な雇用及び働きがいのある人間らしい仕事、ならびに同一労働同一賃金を達成する',
      'De aqui a 2030, lograr el empleo pleno y productivo y el trabajo decente para todas las mujeres y los hombres, incluidos los jovenes y las personas con discapacidad, asi como la igualdad de remuneracion por trabajo de igual valor',
    ],
    [
      '8.6',
      'By 2020, substantially reduce the proportion of youth not in employment, education or training',
      '2020年までに、就労、就学及び職業訓練のいずれも行っていない若者の割合を大幅に減らす',
      'De aqui a 2020, reducir considerablemente la proporcion de jovenes que no estan empleados y no cursan estudios ni reciben capacitacion',
    ],
    [
      '8.7',
      'Take immediate and effective measures to eradicate forced labour, end modern slavery and human trafficking and secure the prohibition and elimination of the worst forms of child labour, including recruitment and use of child soldiers, and by 2025 end child labour in all its forms',
      '強制労働を根絶し、現代の奴隷制、人身売買を終わらせるための緊急かつ効果的な措置の実施、最悪な形態の児童労働の禁止及び撲滅を確保する。2025年までに児童兵士の募集と使用を含むあらゆる形態の児童労働を撲滅する',
      'Adoptar medidas inmediatas y eficaces para erradicar el trabajo forzoso, poner fin a las formas contemporaneas de esclavitud y la trata de personas y asegurar la prohibicion y eliminacion de las peores formas de trabajo infantil, incluidos el reclutamiento y la utilizacion de ninos soldados, y, de aqui a 2025, poner fin al trabajo infantil en todas sus formas',
    ],
    [
      '8.8',
      'Protect labour rights and promote safe and secure working environments for all workers, including migrant workers, in particular women migrants, and those in precarious employment',
      '移住労働者、特に女性の移住労働者や不安定な雇用状態にある労働者など、すべての労働者の権利を保護し、安全・安心な労働環境を促進する',
      'Proteger los derechos laborales y promover un entorno de trabajo seguro y sin riesgos para todos los trabajadores, incluidos los trabajadores migrantes, en particular las mujeres migrantes y las personas con empleos precarios',
    ],
    [
      '8.9',
      'By 2030, devise and implement policies to promote sustainable tourism that creates jobs and promotes local culture and products',
      '2030年までに、雇用創出、地方の文化振興・産品販促につながる持続可能な観光業を促進するための政策を立案し実施する',
      'De aqui a 2030, elaborar y poner en practica politicas encaminadas a promover un turismo sostenible que cree puestos de trabajo y promueva la cultura y los productos locales',
    ],
    [
      '8.10',
      'Strengthen the capacity of domestic financial institutions to encourage and expand access to banking, insurance and financial services for all',
      'すべての人々のための銀行取引、保険及び金融サービスへのアクセスを促進・拡大するため、国内の金融機関の能力を強化する',
      'Fortalecer la capacidad de las instituciones financieras nacionales para fomentar y ampliar el acceso a los servicios bancarios, financieros y de seguros para todos',
    ],
    [
      '8.a',
      'Increase Aid for Trade support for developing countries, in particular least developed countries, including through the Enhanced Integrated Framework for Trade-related Technical Assistance to Least Developed Countries',
      '後発開発途上国への貿易関連技術支援のための拡大統合フレームワーク（EIF）などを通じた支援を含む、開発途上国、特に後発開発途上国に対する貿易のための援助を拡大する',
      'Aumentar el apoyo a la iniciativa de ayuda para el comercio en los paises en desarrollo, en particular los paises menos adelantados, incluso mediante el Marco Integrado Mejorado para la Asistencia Tecnica a los Paises Menos Adelantados en Materia de Comercio',
    ],
    [
      '8.b',
      'By 2020, develop and operationalize a global strategy for youth employment and implement the Global Jobs Pact of the International Labour Organization',
      '2020年までに、若年雇用のための世界的戦略及び国際労働機関の仕事に関する世界協定の実施を展開・運用化する',
      'De aqui a 2020, desarrollar y poner en marcha una estrategia mundial para el empleo de los jovenes y aplicar el Pacto Mundial para el Empleo de la Organizacion Internacional del Trabajo',
    ],
  ],
  9: [
    [
      '9.1',
      'Develop quality, reliable, sustainable and resilient infrastructure, including regional and transborder infrastructure, to support economic development and human well-being, with a focus on affordable and equitable access for all',
      'すべての人々に安価で公平なアクセスに重点を置いた経済発展と人間の福祉を支援するために、地域・越境インフラを含む質の高い、信頼でき、持続可能かつ強靱なインフラを開発する',
      'Desarrollar infraestructuras fiables, sostenibles, resilientes y de calidad, incluidas infraestructuras regionales y transfronterizas, para apoyar el desarrollo economico y el bienestar humano, haciendo especial hincapie en el acceso asequible y equitativo para todos',
    ],
    [
      '9.2',
      "Promote inclusive and sustainable industrialization and, by 2030, significantly raise industry's share of employment and gross domestic product, in line with national circumstances, and double its share in least developed countries",
      '包摂的かつ持続可能な産業化を促進し、2030年までに各国の状況に応じて雇用及びGDPに占める産業セクターの割合を大幅に増加させる。後発開発途上国については同割合を倍増させる',
      'Promover una industrializacion inclusiva y sostenible y, de aqui a 2030, aumentar significativamente la contribucion de la industria al empleo y al producto interno bruto, de acuerdo con las circunstancias nacionales, y duplicar esa contribucion en los paises menos adelantados',
    ],
    [
      '9.3',
      'Increase the access of small-scale industrial and other enterprises, in particular in developing countries, to financial services, including affordable credit, and their integration into value chains and markets',
      '特に開発途上国における小規模の製造業その他の企業の、安価な資金貸出などの金融サービスやバリューチェーン及び市場への統合へのアクセスを拡大する',
      'Aumentar el acceso de las pequenas industrias y otras empresas, particularmente en los paises en desarrollo, a los servicios financieros, incluidos creditos asequibles, y su integracion en las cadenas de valor y los mercados',
    ],
    [
      '9.4',
      'By 2030, upgrade infrastructure and retrofit industries to make them sustainable, with increased resource-use efficiency and greater adoption of clean and environmentally sound technologies and industrial processes, with all countries taking action in accordance with their respective capabilities',
      '2030年までに、資源利用効率の向上とクリーン技術及び環境に配慮した技術・産業プロセスの導入拡大を通じたインフラ改良や産業改善により、持続可能性を向上させる。すべての国々は各国の能力に応じた取組を行う',
      'De aqui a 2030, modernizar la infraestructura y reconvertir las industrias para que sean sostenibles, utilizando los recursos con mayor eficacia y promoviendo la adopcion de tecnologias y procesos industriales limpios y ambientalmente racionales, y logrando que todos los paises tomen medidas de acuerdo con sus capacidades respectivas',
    ],
    [
      '9.5',
      'Enhance scientific research, upgrade the technological capabilities of industrial sectors in all countries, in particular developing countries, including, by 2030, encouraging innovation and substantially increasing the number of research and development workers per 1 million people',
      '2030年までにイノベーションを促進させることや100万人当たりの研究開発従事者数を大幅に増加させ、また官民研究開発の支出を拡大させるなど、開発途上国をはじめとするすべての国々の産業セクターにおける科学研究を促進し、技術能力を向上させる',
      'Aumentar la investigacion cientifica y mejorar la capacidad tecnologica de los sectores industriales de todos los paises, en particular los paises en desarrollo, entre otras cosas fomentando la innovacion y aumentando considerablemente, de aqui a 2030, el numero de personas que trabajan en investigacion y desarrollo por millon de habitantes',
    ],
    [
      '9.a',
      'Facilitate sustainable and resilient infrastructure development in developing countries through enhanced financial, technological and technical support to African countries, least developed countries, landlocked developing countries and small island developing States',
      'アフリカ諸国、後発開発途上国、内陸開発途上国及び小島嶼開発途上国への金融・テクノロジー・技術的支援の強化を通じて、開発途上国における持続可能かつ強靱なインフラ開発を促進する',
      'Facilitar el desarrollo de infraestructuras sostenibles y resilientes en los paises en desarrollo mediante un mayor apoyo financiero, tecnologico y tecnico a los paises africanos, los paises menos adelantados, los paises en desarrollo sin litoral y los pequenos Estados insulares en desarrollo',
    ],
    [
      '9.b',
      'Support domestic technology development, research and innovation in developing countries, including by ensuring a conducive policy environment for, inter alia, industrial diversification and value addition to commodities',
      '産業の多様化や商品への付加価値創造などに資する政策環境の確保などを通じて、開発途上国の国内における技術開発、研究及びイノベーションを支援する',
      'Apoyar el desarrollo de tecnologias, la investigacion y la innovacion nacionales en los paises en desarrollo, incluso garantizando un entorno normativo propicio a la diversificacion industrial y la adicion de valor a los productos basicos, entre otras cosas',
    ],
    [
      '9.c',
      'Significantly increase access to information and communications technology and strive to provide universal and affordable access to the Internet in least developed countries by 2020',
      '後発開発途上国において情報通信技術へのアクセスを大幅に向上させ、2020年までに普遍的かつ安価なインターネット・アクセスを提供できるよう図る',
      'Aumentar significativamente el acceso a la tecnologia de la informacion y las comunicaciones y esforzarse por proporcionar acceso universal y asequible a Internet en los paises menos adelantados de aqui a 2020',
    ],
  ],
  10: [
    [
      '10.1',
      'By 2030, progressively achieve and sustain income growth of the bottom 40 per cent of the population at a rate higher than the national average',
      '2030年までに、各国の所得下位40%の所得成長率について、国内平均を上回る数値を漸進的に達成し、持続させる',
      'De aqui a 2030, lograr progresivamente y mantener el crecimiento de los ingresos del 40% mas pobre de la poblacion a una tasa superior a la media nacional',
    ],
    [
      '10.2',
      'By 2030, empower and promote the social, economic and political inclusion of all, irrespective of age, sex, disability, race, ethnicity, origin, religion or economic or other status',
      '2030年までに、年齢、性別、障害、人種、民族、出自、宗教、あるいは経済的地位その他の状況に関わりなく、すべての人々の能力強化及び社会的、経済的及び政治的な包含を促進する',
      'De aqui a 2030, potenciar y promover la inclusion social, economica y politica de todas las personas, independientemente de su edad, sexo, discapacidad, raza, etnia, origen, religion o situacion economica u otra condicion',
    ],
    [
      '10.3',
      'Ensure equal opportunity and reduce inequalities of outcome, including by eliminating discriminatory laws, policies and practices and promoting appropriate legislation, policies and action in this regard',
      '差別的な法律、政策及び慣行の撤廃、ならびに適切な関連法規、政策、行動の促進などを通じて、機会均等を確保し、成果の不平等を是正する',
      'Garantizar la igualdad de oportunidades y reducir la desigualdad de resultados, incluso eliminando las leyes, politicas y practicas discriminatorias y promoviendo legislaciones, politicas y medidas adecuadas a ese respecto',
    ],
    [
      '10.4',
      'Adopt policies, especially fiscal, wage and social protection policies, and progressively achieve greater equality',
      '税制、賃金、社会保障政策をはじめとする政策を導入し、平等の拡大を漸進的に達成する',
      'Adoptar politicas, especialmente fiscales, salariales y de proteccion social, y lograr progresivamente una mayor igualdad',
    ],
    [
      '10.5',
      'Improve the regulation and monitoring of global financial markets and institutions and strengthen the implementation of such regulations',
      '世界金融市場と金融機関に対する規制とモニタリングを改善し、こうした規制の実施を強化する',
      'Mejorar la reglamentacion y vigilancia de las instituciones y los mercados financieros mundiales y fortalecer la aplicacion de esos reglamentos',
    ],
    [
      '10.6',
      'Ensure enhanced representation and voice for developing countries in decision-making in global international economic and financial institutions in order to deliver more effective, credible, accountable and legitimate institutions',
      'より効果的で信用力があり、説明責任のある正当な制度を実現するため、地球規模の国際経済・金融制度の意思決定における開発途上国の参加や発言力を拡大する',
      'Asegurar una mayor representacion e intervencion de los paises en desarrollo en las decisiones adoptadas por las instituciones economicas y financieras internacionales para aumentar la eficacia, fiabilidad, rendicion de cuentas y legitimidad de esas instituciones',
    ],
    [
      '10.7',
      'Facilitate orderly, safe, regular and responsible migration and mobility of people, including through the implementation of planned and well-managed migration policies',
      '計画に基づく適正な移住政策の実施などを通じて、秩序のとれた、安全で規則的かつ責任ある移住や流動性を促進する',
      'Facilitar la migracion y la movilidad ordenadas, seguras, regulares y responsables de las personas, incluso mediante la aplicacion de politicas migratorias planificadas y bien gestionadas',
    ],
    [
      '10.a',
      'Implement the principle of special and differential treatment for developing countries, in particular least developed countries, in accordance with World Trade Organization agreements',
      '世界貿易機関協定に従い、開発途上国、特に後発開発途上国に対する特別かつ異なる待遇の原則を実施する',
      'Aplicar el principio del trato especial y diferenciado para los paises en desarrollo, en particular los paises menos adelantados, de conformidad con los acuerdos de la Organizacion Mundial del Comercio',
    ],
    [
      '10.b',
      'Encourage official development assistance and financial flows, including foreign direct investment, to States where the need is greatest, in particular least developed countries, African countries, small island developing States and landlocked developing countries, in accordance with their national plans and programmes',
      '各国の国家計画やプログラムに従って、後発開発途上国、アフリカ諸国、小島嶼開発途上国及び内陸開発途上国を始めとする、ニーズが最も大きい国々への、政府開発援助及び海外直接投資を含む資金の流入を促進する',
      'Fomentar la asistencia oficial para el desarrollo y las corrientes financieras, incluida la inversion extranjera directa, para los Estados con mayores necesidades, en particular los paises menos adelantados, los paises africanos, los pequenos Estados insulares en desarrollo y los paises en desarrollo sin litoral, en consonancia con sus planes y programas nacionales',
    ],
    [
      '10.c',
      'By 2030, reduce to less than 3 per cent the transaction costs of migrant remittances and eliminate remittance corridors with costs higher than 5 per cent',
      '2030年までに、移住労働者による送金コストを3%未満に引き下げ、コストが5%を超える送金経路を撤廃する',
      'De aqui a 2030, reducir a menos del 3% los costos de transaccion de las remesas de los migrantes y eliminar los corredores de remesas con un costo superior al 5%',
    ],
  ],
  11: [
    [
      '11.1',
      'By 2030, ensure access for all to adequate, safe and affordable housing and basic services and upgrade slums',
      '2030年までに、すべての人々の、適切、安全かつ安価な住宅及び基本的サービスへのアクセスを確保し、スラムを改善する',
      'De aqui a 2030, asegurar el acceso de todas las personas a viviendas y servicios basicos adecuados, seguros y asequibles y mejorar los barrios marginales',
    ],
    [
      '11.2',
      'By 2030, provide access to safe, affordable, accessible and sustainable transport systems for all, improving road safety, notably by expanding public transport, with special attention to the needs of those in vulnerable situations, women, children, persons with disabilities and older persons',
      '2030年までに、脆弱な立場にある人々、女性、子ども、障害者及び高齢者のニーズに特に配慮し、公共交通機関の拡大などを通じた交通の安全性改善により、すべての人々に、安全かつ安価で容易に利用できる、持続可能な輸送システムへのアクセスを提供する',
      'De aqui a 2030, proporcionar acceso a sistemas de transporte seguros, asequibles, accesibles y sostenibles para todos y mejorar la seguridad vial, en particular mediante la ampliacion del transporte publico, prestando especial atencion a las necesidades de las personas en situacion de vulnerabilidad, las mujeres, los ninos, las personas con discapacidad y las personas de edad',
    ],
    [
      '11.3',
      'By 2030, enhance inclusive and sustainable urbanization and capacity for participatory, integrated and sustainable human settlement planning and management in all countries',
      '2030年までに、包摂的かつ持続可能な都市化を促進し、すべての国々の参加型、包摂的かつ持続可能な人間居住計画・管理の能力を強化する',
      'De aqui a 2030, aumentar la urbanizacion inclusiva y sostenible y la capacidad para la planificacion y la gestion participativas, integradas y sostenibles de los asentamientos humanos en todos los paises',
    ],
    [
      '11.4',
      "Strengthen efforts to protect and safeguard the world's cultural and natural heritage",
      '世界の文化遺産及び自然遺産の保護・保全の努力を強化する',
      'Redoblar los esfuerzos para proteger y salvaguardar el patrimonio cultural y natural del mundo',
    ],
    [
      '11.5',
      'By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by disasters, including water-related disasters, with a focus on protecting the poor and people in vulnerable situations',
      '2030年までに、貧困層及び脆弱な立場にある人々の保護に焦点をあてながら、水関連災害などの災害による死者や被災者数を大幅に削減し、世界の国内総生産比で直接的経済損失を大幅に減らす',
      'De aqui a 2030, reducir significativamente el numero de muertes causadas por los desastres, incluidos los relacionados con el agua, y de personas afectadas por ellos, y reducir considerablemente las perdidas economicas directas provocadas por los desastres en comparacion con el producto interno bruto mundial, haciendo especial hincapie en la proteccion de los pobres y las personas en situaciones de vulnerabilidad',
    ],
    [
      '11.6',
      'By 2030, reduce the adverse per capita environmental impact of cities, including by paying special attention to air quality and municipal and other waste management',
      '2030年までに、大気の質及び一般並びにその他の廃棄物の管理に特別な注意を払うことによるものを含め、都市の一人当たりの環境上の悪影響を軽減する',
      'De aqui a 2030, reducir el impacto ambiental negativo per capita de las ciudades, incluso prestando especial atencion a la calidad del aire y la gestion de los desechos municipales y de otro tipo',
    ],
    [
      '11.7',
      'By 2030, provide universal access to safe, inclusive and accessible, green and public spaces, in particular for women and children, older persons and persons with disabilities',
      '2030年までに、女性、子ども、高齢者及び障害者を含め、人々に安全で包摂的かつ利用が容易な緑地や公共スペースへの普遍的アクセスを提供する',
      'De aqui a 2030, proporcionar acceso universal a zonas verdes y espacios publicos seguros, inclusivos y accesibles, en particular para las mujeres y los ninos, las personas de edad y las personas con discapacidad',
    ],
    [
      '11.a',
      'Support positive economic, social and environmental links between urban, peri-urban and rural areas by strengthening national and regional development planning',
      '各国・地域規模の開発計画の強化を通じて、経済、社会、環境面における都市部、都市周辺部及び農村部間の良好なつながりを支援する',
      'Apoyar los vinculos economicos, sociales y ambientales positivos entre las zonas urbanas, periurbanas y rurales fortaleciendo la planificacion del desarrollo nacional y regional',
    ],
    [
      '11.b',
      'By 2020, substantially increase the number of cities and human settlements adopting and implementing integrated policies and plans towards inclusion, resource efficiency, mitigation and adaptation to climate change, resilience to disasters',
      '2020年までに、包含、資源効率、気候変動の緩和と適応、災害に対する強靱さを目指す総合的政策及び計画を導入・実施した都市及び人間居住地の件数を大幅に増加させる',
      'De aqui a 2020, aumentar considerablemente el numero de ciudades y asentamientos humanos que adoptan e implementan politicas y planes integrados para promover la inclusion, el uso eficiente de los recursos, la mitigacion del cambio climatico y la adaptacion a el y la resiliencia ante los desastres',
    ],
    [
      '11.c',
      'Support least developed countries, including through financial and technical assistance, in building sustainable and resilient buildings utilizing local materials',
      '財政的及び技術的な支援などを通じて、後発開発途上国における現地の資材を用いた、持続可能かつ強靱な建造物の整備を支援する',
      'Proporcionar apoyo a los paises menos adelantados, incluso mediante asistencia financiera y tecnica, para que puedan construir edificios sostenibles y resilientes utilizando materiales locales',
    ],
  ],
  12: [
    [
      '12.1',
      'Implement the 10-Year Framework of Programmes on Sustainable Consumption and Production Patterns, all countries taking action, with developed countries taking the lead',
      '開発途上国の開発状況や能力を勘案しつつ、持続可能な消費と生産に関する10年計画枠組みを実施し、先進国主導の下、すべての国々が対策を講じる',
      'Aplicar el Marco Decenal de Programas sobre Modalidades de Consumo y Produccion Sostenibles, con la participacion de todos los paises y bajo el liderazgo de los paises desarrollados',
    ],
    [
      '12.2',
      'By 2030, achieve the sustainable management and efficient use of natural resources',
      '2030年までに天然資源の持続可能な管理及び効率的な利用を達成する',
      'De aqui a 2030, lograr la gestion sostenible y el uso eficiente de los recursos naturales',
    ],
    [
      '12.3',
      'By 2030, halve per capita global food waste at the retail and consumer levels and reduce food losses along production and supply chains, including post-harvest losses',
      '2030年までに小売・消費レベルにおける世界全体の一人当たりの食料の廃棄を半減させ、収穫後損失などの生産・サプライチェーンにおける食品ロスを減少させる',
      'De aqui a 2030, reducir a la mitad el desperdicio de alimentos per capita mundial en la venta al por menor y a nivel de los consumidores y reducir las perdidas de alimentos en las cadenas de produccion y suministro, incluidas las perdidas posteriores a la cosecha',
    ],
    [
      '12.4',
      'By 2020, achieve the environmentally sound management of chemicals and all wastes throughout their life cycle, in accordance with agreed international frameworks, and significantly reduce their release to air, water and soil in order to minimize their adverse impacts on human health and the environment',
      '2020年までに、合意された国際的な枠組みに従い、製品ライフサイクルを通じ、環境上適正な化学物質やすべての廃棄物の管理を実現し、人の健康や環境への悪影響を最小化するため、化学物質や廃棄物の大気、水、土壌への放出を大幅に削減する',
      'De aqui a 2020, lograr la gestion ecologicamente racional de los productos quimicos y de todos los desechos a lo largo de su ciclo de vida, de conformidad con los marcos internacionales convenidos, y reducir significativamente su liberacion a la atmosfera, el agua y el suelo a fin de minimizar sus efectos adversos en la salud humana y el medio ambiente',
    ],
    [
      '12.5',
      'By 2030, substantially reduce waste generation through prevention, reduction, recycling and reuse',
      '2030年までに、廃棄物の発生防止、削減、再生利用及び再利用により、廃棄物の発生を大幅に削減する',
      'De aqui a 2030, reducir considerablemente la generacion de desechos mediante actividades de prevencion, reduccion, reciclado y reutilizacion',
    ],
    [
      '12.6',
      'Encourage companies, especially large and transnational companies, to adopt sustainable practices and to integrate sustainability information into their reporting cycle',
      '特に大企業や多国籍企業などの企業に対し、持続可能な取り組みを導入し、持続可能性に関する情報を定期報告に盛り込むよう奨励する',
      'Alentar a las empresas, en especial las grandes empresas y las empresas transnacionales, a que adopten practicas sostenibles e incorporen informacion sobre la sostenibilidad en su ciclo de presentacion de informes',
    ],
    [
      '12.7',
      'Promote public procurement practices that are sustainable, in accordance with national policies and priorities',
      '国内の政策や優先事項に従って持続可能な公共調達の慣行を促進する',
      'Promover practicas de adquisicion publica que sean sostenibles, de conformidad con las politicas y prioridades nacionales',
    ],
    [
      '12.8',
      'By 2030, ensure that people everywhere have the relevant information and awareness for sustainable development and lifestyles in harmony with nature',
      '2030年までに、人々があらゆる場所において、持続可能な開発及び自然と調和したライフスタイルに関する情報と意識を持つようにする',
      'De aqui a 2030, asegurar que las personas de todo el mundo tengan la informacion y los conocimientos pertinentes para el desarrollo sostenible y los estilos de vida en armonia con la naturaleza',
    ],
    [
      '12.a',
      'Support developing countries to strengthen their scientific and technological capacity to move towards more sustainable patterns of consumption and production',
      '開発途上国に対し、より持続可能な消費・生産形態の促進のための科学的・技術的能力の強化を支援する',
      'Ayudar a los paises en desarrollo a fortalecer su capacidad cientifica y tecnologica para avanzar hacia modalidades de consumo y produccion mas sostenibles',
    ],
    [
      '12.b',
      'Develop and implement tools to monitor sustainable development impacts for sustainable tourism that creates jobs and promotes local culture and products',
      '雇用創出、地方の文化振興・産品販促につながる持続可能な観光業に対して持続可能な開発がもたらす影響を測定する手法を開発・導入する',
      'Elaborar y aplicar instrumentos para vigilar los efectos en el desarrollo sostenible, a fin de lograr un turismo sostenible que cree puestos de trabajo y promueva la cultura y los productos locales',
    ],
    [
      '12.c',
      'Rationalize inefficient fossil-fuel subsidies that encourage wasteful consumption by removing market distortions, in accordance with national circumstances, including by restructuring taxation and phasing out those harmful subsidies, where they exist, to reflect their environmental impacts',
      '開発途上国の特別なニーズや状況を十分考慮し、貧困層やコミュニティを保護する形で開発に関する悪影響を最小限に留めつつ、税制改正や、有害な補助金が存在する場合はその環境への影響を考慮してその段階的廃止などを通じ、各国の状況に応じて、市場のひずみを除去することで、浪費的な消費を奨励する非効率な化石燃料補助金を合理化する',
      'Racionalizar los subsidios ineficientes a los combustibles fosiles que fomentan el consumo antieconimico eliminando las distorsiones del mercado, de acuerdo con las circunstancias nacionales, incluso mediante la reestructuracion de los sistemas tributarios y la eliminacion gradual de los subsidios perjudiciales, cuando existan, para reflejar su impacto ambiental',
    ],
  ],
};

module.exports = { DATA_7_12 };
