// Goals 13-17 translation data
// [code, en, ja, es]

const DATA_13_17 = {
  13: [
    [
      '13.1',
      'Strengthen resilience and adaptive capacity to climate-related hazards and natural disasters in all countries',
      'すべての国々において、気候関連災害や自然災害に対する強靱性及び適応の能力を強化する',
      'Fortalecer la resiliencia y la capacidad de adaptacion a los riesgos relacionados con el clima y los desastres naturales en todos los paises',
    ],
    [
      '13.2',
      'Integrate climate change measures into national policies, strategies and planning',
      '気候変動対策を国別の政策、戦略及び計画に盛り込む',
      'Incorporar medidas relativas al cambio climatico en las politicas, estrategias y planes nacionales',
    ],
    [
      '13.3',
      'Improve education, awareness-raising and human and institutional capacity on climate change mitigation, adaptation, impact reduction and early warning',
      '気候変動の緩和、適応、影響軽減及び早期警戒に関する教育、啓発、人的能力及び制度機能を改善する',
      'Mejorar la educacion, la sensibilizacion y la capacidad humana e institucional respecto de la mitigacion del cambio climatico, la adaptacion a el, la reduccion de sus efectos y la alerta temprana',
    ],
    [
      '13.a',
      'Implement the commitment undertaken by developed-country parties to the United Nations Framework Convention on Climate Change to a goal of mobilizing jointly $100 billion annually by 2020 from all sources to address the needs of developing countries in the context of meaningful mitigation actions and transparency on implementation',
      '重要な緩和行動の実施とその実施における透明性確保に関する開発途上国のニーズに対応するため、2020年までにあらゆる供給源から年間1,000億ドルを共同で動員するという、UNFCCCの先進締約国によるコミットメントを実施する',
      'Cumplir el compromiso de los paises desarrollados que son partes en la Convencion Marco de las Naciones Unidas sobre el Cambio Climatico de lograr para el ano 2020 el objetivo de movilizar conjuntamente 100.000 millones de dolares anuales procedentes de todas las fuentes a fin de atender las necesidades de los paises en desarrollo',
    ],
    [
      '13.b',
      'Promote mechanisms for raising capacity for effective climate change-related planning and management in least developed countries and small island developing States, including focusing on women, youth and local and marginalized communities',
      '後発開発途上国及び小島嶼開発途上国において、女性や青年、地方及び社会的に疎外されたコミュニティに焦点を当てることを含め、気候変動関連の効果的な計画策定と管理のための能力を向上するメカニズムを推進する',
      'Promover mecanismos para aumentar la capacidad para la planificacion y gestion eficaces en relacion con el cambio climatico en los paises menos adelantados y los pequenos Estados insulares en desarrollo, haciendo particular hincapie en las mujeres, los jovenes y las comunidades locales y marginadas',
    ],
  ],
  14: [
    [
      '14.1',
      'By 2025, prevent and significantly reduce marine pollution of all kinds, in particular from land-based activities, including marine debris and nutrient pollution',
      '2025年までに、海洋ごみや富栄養化を含む、特に陸上活動による汚染など、あらゆる種類の海洋汚染を防止し、大幅に削減する',
      'De aqui a 2025, prevenir y reducir significativamente la contaminacion marina de todo tipo, en particular la producida por actividades realizadas en tierra, incluidos los detritos marinos y la polucion por nutrientes',
    ],
    [
      '14.2',
      'By 2020, sustainably manage and protect marine and coastal ecosystems to avoid significant adverse impacts, including by strengthening their resilience, and take action for their restoration in order to achieve healthy and productive oceans',
      '2020年までに、海洋及び沿岸の生態系に関する重大な悪影響を回避するため、強靱性の強化などによる持続的な管理と保護を行い、健全で生産的な海洋を実現するため、海洋及び沿岸の生態系の回復のための取組を行う',
      'De aqui a 2020, gestionar y proteger sosteniblemente los ecosistemas marinos y costeros para evitar efectos adversos importantes, incluso fortaleciendo su resiliencia, y adoptar medidas para restaurarlos a fin de restablecer la salud y la productividad de los oceanos',
    ],
    [
      '14.3',
      'Minimize and address the impacts of ocean acidification, including through enhanced scientific cooperation at all levels',
      'あらゆるレベルでの科学的協力の促進などを通じて、海洋酸性化の影響を最小限化し、対処する',
      'Minimizar y abordar los efectos de la acidificacion de los oceanos, incluso mediante una mayor cooperacion cientifica a todos los niveles',
    ],
    [
      '14.4',
      'By 2020, effectively regulate harvesting and end overfishing, illegal, unreported and unregulated fishing and destructive fishing practices and implement science-based management plans, in order to restore fish stocks in the shortest time feasible',
      '水産資源を、実現可能な最短期間で少なくとも各資源の生物学的特性によって定められる最大持続生産量のレベルまで回復させるため、2020年までに、漁獲を効果的に規制し、過剰漁業や違法・無報告・無規制漁業及び破壊的な漁業慣行を終了し、科学的な管理計画を実施する',
      'De aqui a 2020, reglamentar eficazmente la explotacion pesquera y poner fin a la pesca excesiva, la pesca ilegal, no declarada y no reglamentada y las practicas pesqueras destructivas, y aplicar planes de gestion con fundamento cientifico a fin de restablecer las poblaciones de peces en el plazo mas breve posible',
    ],
    [
      '14.5',
      'By 2020, conserve at least 10 per cent of coastal and marine areas, consistent with national and international law and based on the best available scientific information',
      '2020年までに、国内法及び国際法に則り、最大限入手可能な科学情報に基づいて、少なくとも沿岸域及び海域の10パーセントを保全する',
      'De aqui a 2020, conservar al menos el 10% de las zonas costeras y marinas, de conformidad con las leyes nacionales y el derecho internacional y sobre la base de la mejor informacion cientifica disponible',
    ],
    [
      '14.6',
      'By 2020, prohibit certain forms of fisheries subsidies which contribute to overcapacity and overfishing, eliminate subsidies that contribute to illegal, unreported and unregulated fishing and refrain from introducing new such subsidies',
      '開発途上国及び後発開発途上国に対する適切かつ効果的な特別かつ異なる待遇が、世界貿易機関の漁業補助金交渉の不可分の要素であるべきことを認識した上で、2020年までに、過剰漁獲能力や過剰漁獲につながる漁業補助金を禁止し、違法・無報告・無規制漁業につながる補助金を撤廃し、同様の新たな補助金の導入を抑制する',
      'De aqui a 2020, prohibir ciertas formas de subvenciones a la pesca que contribuyen a la sobrecapacidad y la pesca excesiva, eliminar las subvenciones que contribuyen a la pesca ilegal, no declarada y no reglamentada y abstenerse de introducir nuevas subvenciones de esa indole',
    ],
    [
      '14.7',
      'By 2030, increase the economic benefits to Small Island Developing States and least developed countries from the sustainable use of marine resources, including through sustainable management of fisheries, aquaculture and tourism',
      '2030年までに、漁業、水産養殖及び観光の持続可能な管理などを通じ、小島嶼開発途上国及び後発開発途上国の海洋資源の持続的な利用による経済的便益を増大させる',
      'De aqui a 2030, aumentar los beneficios economicos que los pequenos Estados insulares en desarrollo y los paises menos adelantados obtienen del uso sostenible de los recursos marinos, en particular mediante la gestion sostenible de la pesca, la acuicultura y el turismo',
    ],
    [
      '14.a',
      'Increase scientific knowledge, develop research capacity and transfer marine technology in order to improve ocean health and to enhance the contribution of marine biodiversity to the development of developing countries',
      '海洋の健全性の改善と、開発途上国、特に小島嶼開発途上国および後発開発途上国の開発における海洋生物多様性の寄与向上のために、科学的知識の増進、研究能力の向上、及び海洋技術の移転を行う',
      'Aumentar los conocimientos cientificos, desarrollar la capacidad de investigacion y transferir tecnologia marina a fin de mejorar la salud de los oceanos y potenciar la contribucion de la biodiversidad marina al desarrollo de los paises en desarrollo',
    ],
    [
      '14.b',
      'Provide access for small-scale artisanal fishers to marine resources and markets',
      '小規模・沿岸零細漁業者に対し、海洋資源及び市場へのアクセスを提供する',
      'Facilitar el acceso de los pescadores artesanales a los recursos marinos y los mercados',
    ],
    [
      '14.c',
      'Enhance the conservation and sustainable use of oceans and their resources by implementing international law as reflected in the United Nations Convention on the Law of the Sea',
      '「我々の求める未来」のパラ158において想起されるとおり、海洋及び海洋資源の保全及び持続可能な利用のための法的枠組みを規定する海洋法に関する国際連合条約に反映されている国際法を実施することにより、海洋及び海洋資源の保全及び持続可能な利用を強化する',
      'Mejorar la conservacion y el uso sostenible de los oceanos y sus recursos aplicando el derecho internacional reflejado en la Convencion de las Naciones Unidas sobre el Derecho del Mar',
    ],
  ],
  15: [
    [
      '15.1',
      'By 2020, ensure the conservation, restoration and sustainable use of terrestrial and inland freshwater ecosystems and their services, in particular forests, wetlands, mountains and drylands, in line with obligations under international agreements',
      '2020年までに、国際協定の下での義務に則って、森林、湿地、山地及び乾燥地をはじめとする陸域生態系と内陸淡水生態系及びそれらのサービスの保全、回復及び持続可能な利用を確保する',
      'De aqui a 2020, asegurar la conservacion, el restablecimiento y el uso sostenible de los ecosistemas terrestres y los ecosistemas interiores de agua dulce y sus servicios, en particular los bosques, los humedales, las montanas y las zonas aridas, en consonancia con las obligaciones contraidas en virtud de acuerdos internacionales',
    ],
    [
      '15.2',
      'By 2020, promote the implementation of sustainable management of all types of forests, halt deforestation, restore degraded forests and substantially increase afforestation and reforestation globally',
      '2020年までに、あらゆる種類の森林の持続可能な経営の実施を促進し、森林減少を阻止し、劣化した森林を回復し、世界全体で新規植林及び再植林を大幅に増加させる',
      'De aqui a 2020, promover la puesta en practica de la gestion sostenible de todos los tipos de bosques, detener la deforestacion, recuperar los bosques degradados y aumentar considerablemente la forestacion y la reforestacion en todo el mundo',
    ],
    [
      '15.3',
      'By 2030, combat desertification, restore degraded land and soil, including land affected by desertification, drought and floods, and strive to achieve a land degradation-neutral world',
      '2030年までに、砂漠化に対処し、砂漠化、干ばつ及び洪水の影響を受けた土地などの劣化した土地と土壌を回復し、土地劣化に荷担しない世界の達成に尽力する',
      'De aqui a 2030, luchar contra la desertificacion, rehabilitar las tierras y los suelos degradados, incluidas las tierras afectadas por la desertificacion, la sequia y las inundaciones, y procurar lograr un mundo con efecto neutro en la degradacion del suelo',
    ],
    [
      '15.4',
      'By 2030, ensure the conservation of mountain ecosystems, including their biodiversity, in order to enhance their capacity to provide benefits that are essential for sustainable development',
      '2030年までに持続可能な開発に不可欠な便益をもたらす山地生態系の能力を強化するため、生物多様性を含む山地生態系の保全を確実に行う',
      'De aqui a 2030, asegurar la conservacion de los ecosistemas montanosos, incluida su diversidad biologica, a fin de mejorar su capacidad de proporcionar beneficios esenciales para el desarrollo sostenible',
    ],
    [
      '15.5',
      'Take urgent and significant action to reduce the degradation of natural habitats, halt the loss of biodiversity and, by 2020, protect and prevent the extinction of threatened species',
      '自然生息地の劣化を抑制し、生物多様性の損失を阻止し、2020年までに絶滅危惧種を保護し、また絶滅防止するための緊急かつ意味のある対策を講じる',
      'Adoptar medidas urgentes y significativas para reducir la degradacion de los habitats naturales, detener la perdida de biodiversidad y, de aqui a 2020, proteger las especies amenazadas y evitar su extincion',
    ],
    [
      '15.6',
      'Promote fair and equitable sharing of the benefits arising from the utilization of genetic resources and promote appropriate access to such resources, as internationally agreed',
      '国際合意に基づき、遺伝資源の利用から生ずる利益の公正かつ衡平な配分を推進するとともに、遺伝資源への適切なアクセスを推進する',
      'Promover la participacion justa y equitativa en los beneficios derivados de la utilizacion de los recursos geneticos y promover el acceso adecuado a esos recursos, segun lo convenido internacionalmente',
    ],
    [
      '15.7',
      'Take urgent action to end poaching and trafficking of protected species of flora and fauna and address both demand and supply of illegal wildlife products',
      '保護の対象となっている動植物種の密猟及び違法取引を撲滅するための緊急対策を講じるとともに、違法な野生生物製品の需要と供給の両面に対処する',
      'Adoptar medidas urgentes para poner fin a la caza furtiva y el trafico de especies protegidas de flora y fauna y abordar tanto la demanda como la oferta de productos ilegales de flora y fauna silvestres',
    ],
    [
      '15.8',
      'By 2020, introduce measures to prevent the introduction and significantly reduce the impact of invasive alien species on land and water ecosystems and control or eradicate the priority species',
      '2020年までに、外来種の侵入を防止するとともに、これらの種による陸域・海洋生態系への影響を大幅に減少させるための対策を導入し、さらに優先種の駆除または根絶を行う',
      'De aqui a 2020, adoptar medidas para prevenir la introduccion de especies exoticas invasoras y reducir significativamente sus efectos en los ecosistemas terrestres y acuaticos y controlar o erradicar las especies prioritarias',
    ],
    [
      '15.9',
      'By 2020, integrate ecosystem and biodiversity values into national and local planning, development processes, poverty reduction strategies and accounts',
      '2020年までに、生態系と生物多様性の価値を、国や地方の計画策定、開発プロセス及び貧困削減のための戦略及び会計に組み込む',
      'De aqui a 2020, integrar los valores de los ecosistemas y la biodiversidad en la planificacion, los procesos de desarrollo, las estrategias de reduccion de la pobreza y la contabilidad nacionales y locales',
    ],
    [
      '15.a',
      'Mobilize and significantly increase financial resources from all sources to conserve and sustainably use biodiversity and ecosystems',
      '生物多様性と生態系の保全と持続的な利用のために、あらゆる資金源からの資金の動員及び大幅な増額を行う',
      'Movilizar y aumentar significativamente los recursos financieros procedentes de todas las fuentes para conservar y utilizar de forma sostenible la biodiversidad y los ecosistemas',
    ],
    [
      '15.b',
      'Mobilize significant resources from all sources and at all levels to finance sustainable forest management and provide adequate incentives to developing countries to advance such management, including for conservation and reforestation',
      '保全や再植林を含む持続可能な森林経営を推進するため、あらゆるレベルのあらゆる供給源から、持続可能な森林経営のための資金の調達と開発途上国への十分なインセンティブ付与のための相当量の資源を動員する',
      'Movilizar recursos considerables de todas las fuentes y a todos los niveles para financiar la gestion forestal sostenible y proporcionar incentivos adecuados a los paises en desarrollo para que promuevan dicha gestion, en particular con miras a la conservacion y la reforestacion',
    ],
    [
      '15.c',
      'Enhance global support for efforts to combat poaching and trafficking of protected species, including by increasing the capacity of local communities to pursue sustainable livelihood opportunities',
      '持続的な生計機会を追求するために地域コミュニティの能力向上を図る等、保護種の密猟及び違法な取引に対処するための努力に対する世界的な支援を強化する',
      'Aumentar el apoyo mundial a la lucha contra la caza furtiva y el trafico de especies protegidas, incluso aumentando la capacidad de las comunidades locales para perseguir oportunidades de subsistencia sostenibles',
    ],
  ],
  16: [
    [
      '16.1',
      'Significantly reduce all forms of violence and related death rates everywhere',
      'あらゆる場所において、すべての形態の暴力及び暴力に関連する死亡率を大幅に減少させる',
      'Reducir significativamente todas las formas de violencia y las correspondientes tasas de mortalidad en todo el mundo',
    ],
    [
      '16.2',
      'End abuse, exploitation, trafficking and all forms of violence against and torture of children',
      '子どもに対する虐待、搾取、取引及びあらゆる形態の暴力及び拷問を撲滅する',
      'Poner fin al maltrato, la explotacion, la trata y todas las formas de violencia y tortura contra los ninos',
    ],
    [
      '16.3',
      'Promote the rule of law at the national and international levels and ensure equal access to justice for all',
      '国家及び国際的なレベルでの法の支配を促進し、すべての人々に司法への平等なアクセスを提供する',
      'Promover el estado de derecho en los planos nacional e internacional y garantizar la igualdad de acceso a la justicia para todos',
    ],
    [
      '16.4',
      'By 2030, significantly reduce illicit financial and arms flows, strengthen the recovery and return of stolen assets and combat all forms of organized crime',
      '2030年までに、違法な資金及び武器の取引を大幅に減少させ、奪われた財産の回復及び返還を強化し、あらゆる形態の組織犯罪を根絶する',
      'De aqui a 2030, reducir significativamente las corrientes financieras y de armas ilicitas, fortalecer la recuperacion y devolucion de los activos robados y luchar contra todas las formas de delincuencia organizada',
    ],
    [
      '16.5',
      'Substantially reduce corruption and bribery in all their forms',
      'あらゆる形態の汚職や贈賄を大幅に減少させる',
      'Reducir considerablemente la corrupcion y el soborno en todas sus formas',
    ],
    [
      '16.6',
      'Develop effective, accountable and transparent institutions at all levels',
      'あらゆるレベルにおいて、有効で説明責任のある透明性の高い公共機関を発展させる',
      'Crear a todos los niveles instituciones eficaces y transparentes que rindan cuentas',
    ],
    [
      '16.7',
      'Ensure responsive, inclusive, participatory and representative decision-making at all levels',
      'あらゆるレベルにおいて、対応的、包摂的、参加型及び代表的な意思決定を確保する',
      'Garantizar la adopcion en todos los niveles de decisiones inclusivas, participativas y representativas que respondan a las necesidades',
    ],
    [
      '16.8',
      'Broaden and strengthen the participation of developing countries in the institutions of global governance',
      'グローバル・ガバナンス機関への開発途上国の参加を拡大・強化する',
      'Ampliar y fortalecer la participacion de los paises en desarrollo en las instituciones de gobernanza mundial',
    ],
    [
      '16.9',
      'By 2030, provide legal identity for all, including birth registration',
      '2030年までに、すべての人々に出生登録を含む法的な身分証明を提供する',
      'De aqui a 2030, proporcionar acceso a una identidad juridica para todos, en particular mediante el registro de nacimientos',
    ],
    [
      '16.10',
      'Ensure public access to information and protect fundamental freedoms, in accordance with national legislation and international agreements',
      '国内法規及び国際協定に従い、情報への公共アクセスを確保し、基本的自由を保障する',
      'Garantizar el acceso publico a la informacion y proteger las libertades fundamentales, de conformidad con las leyes nacionales y los acuerdos internacionales',
    ],
    [
      '16.a',
      'Strengthen relevant national institutions, including through international cooperation, for building capacity at all levels, in particular in developing countries, to prevent violence and combat terrorism and crime',
      '特に開発途上国において、暴力の防止とテロリズム・犯罪の撲滅に関するあらゆるレベルでの能力構築のため、国際協力などを通じて関連国家機関を強化する',
      'Fortalecer las instituciones nacionales pertinentes, incluso mediante la cooperacion internacional, para crear a todos los niveles, particularmente en los paises en desarrollo, la capacidad de prevenir la violencia y combatir el terrorismo y la delincuencia',
    ],
    [
      '16.b',
      'Promote and enforce non-discriminatory laws and policies for sustainable development',
      '持続可能な開発のための非差別的な法規及び政策を推進し、実施する',
      'Promover y aplicar leyes y politicas no discriminatorias en favor del desarrollo sostenible',
    ],
  ],
  17: [
    [
      '17.1',
      'Strengthen domestic resource mobilization, including through international support to developing countries, to improve domestic capacity for tax and other revenue collection',
      '課税及び徴税能力の向上のため、開発途上国への国際的な支援なども通じて、国内資源の動員を強化する',
      'Fortalecer la movilizacion de recursos internos, incluso mediante la prestacion de apoyo internacional a los paises en desarrollo, con el fin de mejorar la capacidad nacional para recaudar ingresos fiscales y de otra indole',
    ],
    [
      '17.2',
      'Developed countries to implement fully their official development assistance commitments, including the commitment by many developed countries to achieve the target of 0.7 per cent of gross national income for official development assistance to developing countries',
      '先進国は、開発途上国に対するODAをGNI比0.7%に、後発開発途上国に対するODAをGNI比0.15~0.20%にするという目標を達成するとの多くの国によるコミットメントを含むODAに係るコミットメントを完全に実施する',
      'Velar por que los paises desarrollados cumplan plenamente sus compromisos en relacion con la asistencia oficial para el desarrollo, incluido el compromiso de numerosos paises desarrollados de alcanzar el objetivo de destinar el 0,7% del ingreso nacional bruto a la asistencia oficial para el desarrollo de los paises en desarrollo',
    ],
    [
      '17.3',
      'Mobilize additional financial resources for developing countries from multiple sources',
      '複数の財源から、開発途上国のための追加的資金源を動員する',
      'Movilizar recursos financieros adicionales de multiples fuentes para los paises en desarrollo',
    ],
    [
      '17.4',
      'Assist developing countries in attaining long-term debt sustainability through coordinated policies aimed at fostering debt financing, debt relief and debt restructuring, as appropriate',
      '必要に応じた負債による資金調達、債務救済及び債務再編の促進を目的とした協調的な政策により、開発途上国の長期的な債務の持続可能性の実現を支援し、重債務貧困国の対外債務への対応により債務リスクを軽減する',
      'Ayudar a los paises en desarrollo a lograr la sostenibilidad de la deuda a largo plazo con politicas coordinadas orientadas a fomentar la financiacion, el alivio y la reestructuracion de la deuda, segun proceda, y hacer frente a la deuda externa de los paises pobres muy endeudados a fin de reducir el endeudamiento excesivo',
    ],
    [
      '17.5',
      'Adopt and implement investment promotion regimes for least developed countries',
      '後発開発途上国のための投資促進枠組みを導入及び実施する',
      'Adoptar y aplicar sistemas de promocion de las inversiones en favor de los paises menos adelantados',
    ],
    [
      '17.6',
      'Enhance North-South, South-South and triangular regional and international cooperation on and access to science, technology and innovation and enhance knowledge-sharing on mutually agreed terms',
      '科学技術イノベーションに関する南北協力、南南協力及び地域的・国際的な三角協力へのアクセスを向上させ、また、相互に合意した条件で知識共有を進める',
      'Mejorar la cooperacion regional e internacional Norte-Sur, Sur-Sur y triangular en materia de ciencia, tecnologia e innovacion y el acceso a estas, y aumentar el intercambio de conocimientos en condiciones mutuamente convenidas',
    ],
    [
      '17.7',
      'Promote the development, transfer, dissemination and diffusion of environmentally sound technologies to developing countries on favourable terms, including on concessional and preferential terms, as mutually agreed',
      '開発途上国に対し、譲許的・特恵的条件などの相互に合意した有利な条件の下で、環境に配慮した技術の開発、移転、普及及び拡散を促進する',
      'Promover el desarrollo de tecnologias ecologicamente racionales y su transferencia, divulgacion y difusion a los paises en desarrollo en condiciones favorables, incluso en condiciones concesionarias y preferenciales, segun lo convenido de mutuo acuerdo',
    ],
    [
      '17.8',
      'Fully operationalize the technology bank and science, technology and innovation capacity-building mechanism for least developed countries by 2017 and enhance the use of enabling technology, in particular information and communications technology',
      '2017年までに、後発開発途上国のための技術バンク及び科学技術イノベーション能力構築メカニズムを完全運用させ、情報通信技術をはじめとする実現技術の利用を強化する',
      'Poner en pleno funcionamiento, a mas tardar en 2017, el banco de tecnologia y el mecanismo de apoyo a la creacion de capacidad en materia de ciencia, tecnologia e innovacion para los paises menos adelantados y aumentar la utilizacion de tecnologias instrumentales, en particular la tecnologia de la informacion y las comunicaciones',
    ],
    [
      '17.9',
      'Enhance international support for implementing effective and targeted capacity-building in developing countries to support national plans to implement all the Sustainable Development Goals',
      'すべての持続可能な開発目標を実施するための国家計画を支援するべく、南北協力、南南協力及び三角協力などを通じて、開発途上国における効果的かつ的をしぼった能力構築の実施に対する国際的な支援を強化する',
      'Aumentar el apoyo internacional para realizar actividades de creacion de capacidad eficaces y especificas en los paises en desarrollo a fin de respaldar los planes nacionales de implementacion de todos los Objetivos de Desarrollo Sostenible',
    ],
    [
      '17.10',
      'Promote a universal, rules-based, open, non-discriminatory and equitable multilateral trading system under the World Trade Organization, including through the conclusion of negotiations under its Doha Development Agenda',
      'ドーハ・ラウンド交渉の受結などを通じ、世界貿易機関の下での普遍的でルールに基づいた、差別的でない、公平な多角的貿易体制を促進する',
      'Promover un sistema de comercio multilateral universal, basado en normas, abierto, no discriminatorio y equitativo en el marco de la Organizacion Mundial del Comercio, incluso mediante la conclusion de las negociaciones en el marco del Programa de Doha para el Desarrollo',
    ],
    [
      '17.11',
      "Significantly increase the exports of developing countries, in particular with a view to doubling the least developed countries' share of global exports by 2020",
      '開発途上国による輸出を大幅に増加させ、特に2020年までに世界の輸出に占める後発開発途上国のシェアを倍増させる',
      'Aumentar significativamente las exportaciones de los paises en desarrollo, en particular con miras a duplicar la participacion de los paises menos adelantados en las exportaciones mundiales de aqui a 2020',
    ],
    [
      '17.12',
      'Realize timely implementation of duty-free and quota-free market access on a lasting basis for all least developed countries, consistent with World Trade Organization decisions',
      '後発開発途上国からの輸入に対する特恵的な原産地規則が透明で簡略的かつ市場アクセスの円滑化に寄与するものとなるようにすることを含む世界貿易機関の決定に矛盾しない形で、すべての後発開発途上国に対し、永続的な無税・無枠の市場アクセスを適時実施する',
      'Lograr la consecucion oportuna del acceso a los mercados libre de derechos y contingentes de manera duradera para todos los paises menos adelantados, conforme a las decisiones de la Organizacion Mundial del Comercio',
    ],
    [
      '17.13',
      'Enhance global macroeconomic stability, including through policy coordination and policy coherence',
      '政策協調や政策の首尾一貫性などを通じて、世界的なマクロ経済の安定を促進する',
      'Aumentar la estabilidad macroeconomica mundial, incluso mediante la coordinacion y coherencia de las politicas',
    ],
    [
      '17.14',
      'Enhance policy coherence for sustainable development',
      '持続可能な開発のための政策の一貫性を強化する',
      'Mejorar la coherencia de las politicas para el desarrollo sostenible',
    ],
    [
      '17.15',
      "Respect each country's policy space and leadership to establish and implement policies for poverty eradication and sustainable development",
      '貧困撲滅と持続可能な開発のための政策の確立・実施にあたっては、各国の政策空間及びリーダーシップを尊重する',
      'Respetar el margen normativo y el liderazgo de cada pais para establecer y aplicar politicas de erradicacion de la pobreza y desarrollo sostenible',
    ],
    [
      '17.16',
      'Enhance the Global Partnership for Sustainable Development, complemented by multi-stakeholder partnerships that mobilize and share knowledge, expertise, technology and financial resources, to support the achievement of the Sustainable Development Goals in all countries',
      'すべての国々、特に開発途上国での持続可能な開発目標の達成を支援すべく、知識、専門的知見、技術及び資金源を動員、共有するマルチステークホルダー・パートナーシップによって補完しつつ、持続可能な開発のためのグローバル・パートナーシップを強化する',
      'Mejorar la Alianza Mundial para el Desarrollo Sostenible, complementada por alianzas entre multiples interesados que movilicen e intercambien conocimientos, especializacion, tecnologia y recursos financieros, a fin de apoyar el logro de los Objetivos de Desarrollo Sostenible en todos los paises',
    ],
    [
      '17.17',
      'Encourage and promote effective public, public-private and civil society partnerships, building on the experience and resourcing strategies of partnerships',
      'さまざまなパートナーシップの経験や資源戦略を基にした、効果的な公的、官民、市民社会のパートナーシップを奨励・推進する',
      'Fomentar y promover la constitucion de alianzas eficaces en las esferas publica, publico-privada y de la sociedad civil, aprovechando la experiencia y las estrategias de obtencion de recursos de las alianzas',
    ],
    [
      '17.18',
      'By 2020, enhance capacity-building support to developing countries, including for least developed countries and small island developing states, to increase significantly the availability of high-quality, timely and reliable data',
      '2020年までに、後発開発途上国及び小島嶼開発途上国を含む開発途上国に対する能力構築支援を強化し、所得、性別、年齢、人種、民族、居住資格、障害、地理的位置及びその他各国事情に関連する特性別の質が高く、タイムリーかつ信頼性のある非集計型データの入手可能性を向上させる',
      'De aqui a 2020, mejorar el apoyo a la creacion de capacidad prestado a los paises en desarrollo, incluidos los paises menos adelantados y los pequenos Estados insulares en desarrollo, para aumentar significativamente la disponibilidad de datos oportunos, fiables y de gran calidad',
    ],
    [
      '17.19',
      'By 2030, build on existing initiatives to develop measurements of progress on sustainable development that complement gross domestic product, and support statistical capacity-building in developing countries',
      '2030年までに、持続可能な開発の進捗状況を測るGDP以外の尺度を開発する既存の取組を更に前進させ、開発途上国における統計に関する能力構築を支援する',
      'De aqui a 2030, aprovechar las iniciativas existentes para elaborar indicadores que permitan medir los progresos en materia de desarrollo sostenible y complementen el producto interno bruto, y apoyar la creacion de capacidad estadistica en los paises en desarrollo',
    ],
  ],
};

module.exports = { DATA_13_17 };
