import 'dart:convert';

import 'package:flutter/services.dart';

import 'package:seed_app/features/transport/data/models/city_model.dart';

// ignore_for_file: constant_identifier_names
const CITY_COUNT = 969;
const _ASSET_PATH = 'data/app/cities.json';

/// Loads the city list (sorted by population, descending).
Future<List<City>> loadCities() async {
  final root = await _loadRoot();
  return (root['cities'] as List<dynamic>)
      .map((e) => City.fromJson(e as Map<String, dynamic>))
      .toList();
}

/// Loads the fixed landmass crossings (tunnels, ferry corridors).
Future<List<CityLink>> loadCityLinks() async {
  final root = await _loadRoot();
  final metadata = root['metadata'] as Map<String, dynamic>;
  return (metadata['links'] as List<dynamic>)
      .map((e) => CityLink.fromJson(e as Map<String, dynamic>))
      .toList();
}

/// Loads the water-blocked pair set: same-mass pairs whose
/// straight line crosses open water the ground circuity factor
/// cannot honestly cover (generated by build_water_blocklist.py
/// as index pairs into the cities array). Keys match
/// `cityPairKey`; pass to `suggestedDistancesKm`.
Future<Set<String>> loadWaterBlockedPairs() async {
  final root = await _loadRoot();
  final metadata = root['metadata'] as Map<String, dynamic>;
  final blocked = metadata['water_blocked'] as List<dynamic>? ?? const [];
  if (blocked.isEmpty) return const {};
  final cities = root['cities'] as List<dynamic>;
  String key(int i) {
    final c = cities[i] as Map<String, dynamic>;
    return '${c['cc']}/${c['name']}';
  }

  return blocked.map((e) {
    final pair = e as List<dynamic>;
    final ka = key(pair[0] as int);
    final kb = key(pair[1] as int);
    return ka.compareTo(kb) <= 0 ? '$ka||$kb' : '$kb||$ka';
  }).toSet();
}

Future<Map<String, dynamic>>? _rootFuture;

// The asset is static, so decode the 136 KB JSON once and share it
// across loadCities/loadCityLinks and repeated screen opens.
Future<Map<String, dynamic>> _loadRoot() => _rootFuture ??= rootBundle
    .loadString(_ASSET_PATH)
    .then((s) => json.decode(s) as Map<String, dynamic>)
    .onError((error, stackTrace) {
      // Never memoize a rejected future: a transient first-load
      // failure would otherwise rethrow until app restart.
      _rootFuture = null;
      Error.throwWithStackTrace(error!, stackTrace);
    });
