import 'package:flutter/material.dart';

/// Centralized icon mapping for action icons.
///
/// Maps icon name strings (from Firestore) to Material Icons.
const actionIconMap = <String, IconData>{
  'recycling': Icons.recycling,
  'delete': Icons.delete_outline,
  'local_drink': Icons.local_drink,
  'shopping_bag': Icons.shopping_bag,
  'coffee': Icons.coffee,
  'bike': Icons.pedal_bike,
  'pedal_bike': Icons.pedal_bike,
  'bus': Icons.directions_bus,
  'train': Icons.directions_transit,
  'directions_walk': Icons.directions_walk,
  'restaurant': Icons.restaurant,
  'eco': Icons.eco,
  'compost': Icons.compost,
  'shopping': Icons.shopping_cart,
  'bolt': Icons.bolt,
  'power': Icons.power_off,
  'dry_cleaning': Icons.dry_cleaning,
  'water_drop': Icons.water_drop,
  'shower': Icons.shower,
  'local_grocery': Icons.local_grocery_store,
  'storefront': Icons.local_grocery_store,
  'takeout': Icons.takeout_dining,
  'people': Icons.people,
  'electric_car': Icons.electric_car,
  'forest': Icons.forest,
  'lightbulb': Icons.lightbulb_outline,
  'inventory_2': Icons.inventory_2,
  'food_bank': Icons.food_bank,
  'local_laundry_service': Icons.local_laundry_service,
  'local_cafe': Icons.local_cafe,
  'no_drinks': Icons.no_drinks,
  'autorenew': Icons.autorenew,
  'plumbing': Icons.plumbing,
  'dishwasher': Icons.kitchen,
  // New icons for expanded action library
  'campaign': Icons.campaign,
  'menu_book': Icons.menu_book,
  'groups': Icons.groups,
  'park': Icons.park,
  'yard': Icons.yard,
  'volunteer_activism': Icons.volunteer_activism,
  'cleaning_services': Icons.cleaning_services,
  'thermostat': Icons.thermostat,
  'wb_sunny': Icons.wb_sunny,
  'solar_power': Icons.solar_power,
  'air': Icons.air,
  'pets': Icons.pets,
  'science': Icons.science,
  'diversity_3': Icons.diversity_3,
  'school': Icons.school,
  'handshake': Icons.handshake,
  'balance': Icons.balance,
  'public': Icons.public,
  'work': Icons.work,
  'engineering': Icons.engineering,
  'catching_pokemon': Icons.catching_pokemon,
  'grass': Icons.grass,
  'kitchen': Icons.kitchen,
  'microwave': Icons.microwave,
  'local_shipping': Icons.local_shipping,
  'edit_note': Icons.edit_note,
  'share': Icons.share,
  'electric_bolt': Icons.electric_bolt,
  'ev_station': Icons.ev_station,
  'smartphone': Icons.smartphone,
  'build': Icons.build,
  'soap': Icons.soap,
};

/// Returns the icon for the given icon name string.
/// Falls back to [Icons.eco] for unknown names.
IconData getActionIcon(String iconName) {
  return actionIconMap[iconName] ?? Icons.eco;
}
