/**
 * Long descriptions for eco-actions:
 * RECYCLING, TRANSPORT, FOOD categories.
 *
 * Each description is 3-5 sentences with markdown
 * formatting, bold CO2 figures, and source links.
 *
 * This is a partial file merged into the final
 * descriptions module.
 */

const descriptions = {
  // -------------------------------------------------------
  // RECYCLING (10 actions)
  // -------------------------------------------------------
  recycle_aluminum_can: {
    en:
      'Recycling a single aluminum can saves '
      + 'roughly **99g of CO2** compared to '
      + 'smelting one from raw bauxite ore. '
      + 'The process requires just 5% of the '
      + 'energy needed for primary production '
      + '([International Aluminium Institute]'
      + '(https://international-aluminium.org'
      + '/landing/aluminium-recycling-saves-95'
      + '-of-the-energy-needed-for-primary-'
      + 'aluminium-production/)). '
      + 'Unlike most materials, aluminum can be '
      + 'recycled infinitely with no quality '
      + 'loss ([Aluminum Association]'
      + '(https://www.aluminum.org/Recycling)). '
      + 'A single can returns to store shelves '
      + 'as a new can in as little as 60 days.',
    ja:
      'アルミ缶1本のリサイクルで、原料の'
      + 'ボーキサイトから精錬する場合に比べ'
      + '約**99gのCO2**を削減できます。'
      + 'リサイクルに必要なエネルギーは一次'
      + '生産のわずか5%です'
      + '（[国際アルミニウム協会]'
      + '(https://international-aluminium.org'
      + '/landing/aluminium-recycling-saves-95'
      + '-of-the-energy-needed-for-primary-'
      + 'aluminium-production/)）。'
      + 'アルミニウムは品質を落とすことなく'
      + '無限にリサイクル可能で、回収から約'
      + '60日で新しい缶として店頭に並びます'
      + '（[Aluminum Association]'
      + '(https://www.aluminum.org/Recycling)）。',
    es:
      'Reciclar una sola lata de aluminio '
      + 'ahorra aproximadamente **99g de CO2** '
      + 'en comparación con fundir una nueva '
      + 'desde bauxita. El proceso requiere '
      + 'solo el 5% de la energía necesaria '
      + 'para la producción primaria '
      + '([International Aluminium Institute]'
      + '(https://international-aluminium.org'
      + '/landing/aluminium-recycling-saves-95'
      + '-of-the-energy-needed-for-primary-'
      + 'aluminium-production/)). '
      + 'El aluminio se puede reciclar '
      + 'infinitamente sin perder calidad '
      + '([Aluminum Association]'
      + '(https://www.aluminum.org/Recycling)). '
      + 'Una lata reciclada puede volver a los '
      + 'estantes en solo 60 días.',
  },

  recycle_plastic_bottle: {
    en:
      'Recycling a standard 28g PET plastic '
      + 'bottle prevents roughly **47g of CO2** '
      + 'from entering the atmosphere. The '
      + '[EPA WARM model](https://www.epa.gov'
      + '/warm) calculates that recycled PET '
      + 'displaces virgin resin production, '
      + 'which is highly energy-intensive. '
      + 'Each bottle recycled also keeps '
      + 'persistent plastic out of landfills '
      + 'and oceans, where it can take over '
      + '450 years to decompose.',
    ja:
      '標準的な28gのPETボトルをリサイクル'
      + 'すると約**47gのCO2**排出を防げます。'
      + '[EPA WARMモデル](https://www.epa.gov'
      + '/warm)によると、リサイクルPETは'
      + 'エネルギー集約的なバージン樹脂の'
      + '生産を代替します。リサイクルにより'
      + '分解に450年以上かかるプラスチックが'
      + '埋立地や海洋に流出するのも防げます。',
    es:
      'Reciclar una botella estándar de PET '
      + 'de 28g evita que aproximadamente '
      + '**47g de CO2** lleguen a la atmósfera. '
      + 'El [modelo WARM de la EPA]'
      + '(https://www.epa.gov/warm) calcula que '
      + 'el PET reciclado desplaza la producción '
      + 'de resina virgen, un proceso muy '
      + 'intensivo en energía. Cada botella '
      + 'reciclada también evita que plástico '
      + 'persistente termine en vertederos u '
      + 'océanos, donde tarda más de 450 años '
      + 'en descomponerse.',
  },

  recycle_cardboard: {
    en:
      'Recycling cardboard saves about '
      + '**50g of CO2** per typical box. '
      + 'Cardboard recycling prevents roughly '
      + '2,160g of CO2 per kilogram by avoiding '
      + 'virgin pulp production '
      + '([EPA WARM](https://www.epa.gov'
      + '/warm)). The process also conserves '
      + 'trees that act as active carbon sinks. '
      + 'Corrugated cardboard is one of the '
      + 'most successfully recycled materials, '
      + 'with recovery rates exceeding 90% in '
      + 'many countries.',
    ja:
      '段ボールのリサイクルは1箱あたり約'
      + '**50gのCO2**を削減します。段ボール'
      + 'リサイクルは1kgあたり約2,160gの'
      + 'CO2を節約し、バージンパルプ生産を'
      + '回避します（[EPA WARM]'
      + '(https://www.epa.gov/warm)）。'
      + 'また炭素吸収源として機能する森林の'
      + '保全にも貢献します。段ボールは最も'
      + 'リサイクル率の高い素材の一つで、多く'
      + 'の国で回収率90%以上を達成しています。',
    es:
      'Reciclar cartón ahorra '
      + 'aproximadamente **50g de CO2** por '
      + 'caja típica. El reciclaje de cartón '
      + 'evita unas 2.160g de CO2 por '
      + 'kilogramo al no necesitar producción '
      + 'de pulpa virgen ([EPA WARM]'
      + '(https://www.epa.gov/warm)). '
      + 'El proceso también conserva árboles '
      + 'que actúan como sumideros de carbono. '
      + 'El cartón corrugado es uno de los '
      + 'materiales con mayor tasa de '
      + 'reciclaje, superando el 90% en muchos '
      + 'países.',
  },

  composting: {
    en:
      'Composting food scraps prevents about '
      + '**200g of CO2 equivalent** per session '
      + 'by diverting organic waste from '
      + 'landfills. The [EPA](https://www.epa'
      + '.gov/land-research/quantifying-methane'
      + '-emissions-landfilled-food-waste) '
      + 'reports that 58% of fugitive methane '
      + 'from landfills comes from food waste. '
      + 'Methane is 80x more potent than CO2 '
      + 'over 20 years, making composting a '
      + 'powerful climate action. The resulting '
      + 'compost also enriches soil and reduces '
      + 'the need for synthetic fertilizers.',
    ja:
      '生ごみのコンポスト化は1回あたり約'
      + '**200gのCO2相当**を削減します。'
      + '[EPA](https://www.epa.gov/land-research'
      + '/quantifying-methane-emissions-'
      + 'landfilled-food-waste)によると、'
      + '埋立地からの逸散メタンの58%は'
      + '食品廃棄物が原因です。メタンは20年'
      + 'スパンでCO2の80倍の温室効果があり、'
      + 'コンポストは強力な気候変動対策です。'
      + 'できた堆肥は土壌を豊かにし、合成'
      + '肥料の使用量も削減できます。',
    es:
      'Compostar restos de comida evita '
      + 'aproximadamente **200g de CO2 '
      + 'equivalente** por sesión al desviar '
      + 'residuos orgánicos de vertederos. La '
      + '[EPA](https://www.epa.gov/land-research'
      + '/quantifying-methane-emissions-'
      + 'landfilled-food-waste) informa que el '
      + '58% del metano fugitivo de vertederos '
      + 'proviene de residuos alimentarios. '
      + 'El metano es 80 veces más potente que '
      + 'el CO2 en 20 años, haciendo del '
      + 'compostaje una acción climática '
      + 'poderosa. El compost resultante '
      + 'enriquece el suelo y reduce la '
      + 'necesidad de fertilizantes sintéticos.',
  },

  recycle_glass: {
    en:
      'Recycling a typical glass jar saves '
      + 'about **40g of CO2** by reducing the '
      + 'energy needed to melt raw materials. '
      + 'Glass recycling saves roughly 300g of '
      + 'CO2 per 450g wine bottle according to '
      + 'the [EPA WARM model]'
      + '(https://www.epa.gov/warm). '
      + 'Like aluminum, glass can be recycled '
      + 'endlessly without degradation. Every '
      + '10% increase in recycled cullet used '
      + 'in production cuts energy consumption '
      + 'by about 3%.',
    ja:
      'ガラス瓶1本のリサイクルで約**40gの'
      + 'CO2**を削減できます。原料を溶かす'
      + 'のに必要なエネルギーが減るためです。'
      + '[EPA WARMモデル](https://www.epa.gov'
      + '/warm)によると、450gのワインボトル'
      + '1本で約300gのCO2を節約できます。'
      + 'アルミニウム同様、ガラスは劣化なく'
      + '無限にリサイクル可能です。カレット'
      + '（リサイクルガラス）の使用率を10%'
      + '上げるとエネルギー消費が約3%削減'
      + 'されます。',
    es:
      'Reciclar un frasco de vidrio típico '
      + 'ahorra unos **40g de CO2** al reducir '
      + 'la energía para fundir materias '
      + 'primas. El reciclaje de vidrio ahorra '
      + 'unos 300g de CO2 por botella de vino '
      + 'de 450g según el [modelo WARM de la '
      + 'EPA](https://www.epa.gov/warm). '
      + 'Al igual que el aluminio, el vidrio se '
      + 'puede reciclar infinitamente sin '
      + 'degradarse. Cada 10% de aumento en el '
      + 'uso de casco reciclado reduce el '
      + 'consumo energético un 3%.',
  },

  recycle_paper: {
    en:
      'Recycling a batch of paper saves '
      + 'approximately **50g of CO2** by '
      + 'displacing virgin pulp manufacturing. '
      + 'Paper recycling prevents about 2,590g '
      + 'of CO2 per kilogram according to '
      + 'the [EPA WARM model]'
      + '(https://www.epa.gov/warm). '
      + 'It also conserves water and reduces '
      + 'the pressure on forests that serve as '
      + 'critical carbon sinks. Paper fibers '
      + 'can typically be recycled 5-7 times '
      + 'before they become too short to use.',
    ja:
      '紙のリサイクルは1回あたり約**50gの'
      + 'CO2**を削減し、バージンパルプ製造を'
      + '代替します。[EPA WARMモデル]'
      + '(https://www.epa.gov/warm)によると、'
      + '紙のリサイクルは1kgあたり約2,590gの'
      + 'CO2を防ぎます。水資源の節約や、重要'
      + 'な炭素吸収源である森林への負荷軽減'
      + 'にもつながります。紙の繊維は通常'
      + '5〜7回リサイクル可能です。',
    es:
      'Reciclar un lote de papel ahorra '
      + 'aproximadamente **50g de CO2** al '
      + 'desplazar la fabricación de pulpa '
      + 'virgen. El reciclaje de papel evita '
      + 'unas 2.590g de CO2 por kilogramo '
      + 'según el [modelo WARM de la EPA]'
      + '(https://www.epa.gov/warm). '
      + 'También conserva agua y reduce la '
      + 'presión sobre los bosques que sirven '
      + 'como sumideros críticos de carbono. '
      + 'Las fibras de papel se pueden reciclar '
      + 'de 5 a 7 veces antes de volverse '
      + 'demasiado cortas.',
  },

  recycle_ewaste: {
    en:
      'Recycling an old smartphone prevents '
      + 'roughly **2,000g (2kg) of CO2** by '
      + 'recovering precious metals and rare '
      + 'earth elements that would otherwise '
      + 'require energy-intensive mining. '
      + 'Electronic devices contain gold, '
      + 'copper, and palladium whose extraction '
      + 'from ore is highly carbon-intensive. '
      + 'The [EPA GHG Equivalencies '
      + 'Calculator](https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies-'
      + 'calculator) helps quantify these '
      + 'savings. Proper e-waste recycling also '
      + 'prevents toxic lead and mercury from '
      + 'leaching into groundwater.',
    ja:
      '古いスマートフォンをリサイクルする'
      + 'と約**2,000g（2kg）のCO2**を削減'
      + 'でき、貴金属やレアアース元素を回収'
      + 'してエネルギー集約的な採掘を回避'
      + 'します。電子機器には金、銅、パラ'
      + 'ジウムが含まれ、鉱石からの抽出は'
      + '炭素集約度が非常に高いです。'
      + '[EPA温室効果ガス等価計算ツール]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies-'
      + 'calculator)でこれらの削減効果を'
      + '定量化できます。適切な電子廃棄物'
      + 'リサイクルは有害な鉛や水銀が'
      + '地下水に浸出するのも防ぎます。',
    es:
      'Reciclar un smartphone antiguo evita '
      + 'unas **2.000g (2kg) de CO2** al '
      + 'recuperar metales preciosos y '
      + 'elementos de tierras raras que de '
      + 'otro modo requerirían minería '
      + 'intensiva en energía. Los '
      + 'dispositivos electrónicos contienen '
      + 'oro, cobre y paladio cuya extracción '
      + 'del mineral es altamente intensiva '
      + 'en carbono. La [Calculadora de '
      + 'Equivalencias GEI de la EPA]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies-'
      + 'calculator) ayuda a cuantificar '
      + 'estos ahorros. El reciclaje adecuado '
      + 'de e-waste también evita que plomo y '
      + 'mercurio tóxicos se filtren a las '
      + 'aguas subterráneas.',
  },

  recycle_textiles: {
    en:
      'Recycling a bag of textiles prevents '
      + 'roughly **40,000g (40kg) of CO2** by '
      + 'diverting fabric from landfills and '
      + 'reducing demand for virgin fiber '
      + 'production. The fashion industry '
      + 'accounts for up to 10% of global '
      + 'carbon emissions. Reusing textiles '
      + 'avoids the water-intensive cotton '
      + 'farming and petroleum-based synthetic '
      + 'fiber manufacturing processes '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Even worn-out fabrics can be '
      + 'downcycled into insulation or rags.',
    ja:
      '衣類を袋ごとリサイクルすると約'
      + '**40,000g（40kg）のCO2**を削減'
      + 'でき、布地の埋立処分を回避し'
      + 'バージン繊維の生産需要を減らせ'
      + 'ます。ファッション産業は世界の'
      + '炭素排出量の最大10%を占めます。'
      + '繊維の再利用は、水資源を大量に'
      + '使う綿花栽培や石油由来の合成繊維'
      + '製造を回避します（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。'
      + '着古した布地も断熱材やウエスに'
      + 'ダウンサイクルできます。',
    es:
      'Reciclar una bolsa de textiles evita '
      + 'unas **40.000g (40kg) de CO2** al '
      + 'desviar telas de los vertederos y '
      + 'reducir la demanda de producción de '
      + 'fibra virgen. La industria de la '
      + 'moda representa hasta el 10% de las '
      + 'emisiones globales de carbono. '
      + 'Reutilizar textiles evita el cultivo '
      + 'de algodón intensivo en agua y la '
      + 'fabricación de fibras sintéticas '
      + 'derivadas del petróleo '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Incluso las telas gastadas '
      + 'pueden reciclarse como aislamiento '
      + 'o trapos.',
  },

  recycle_batteries: {
    en:
      'Recycling a single AA battery '
      + 'prevents roughly **95g of CO2** and '
      + 'keeps toxic heavy metals out of '
      + 'landfills. Battery recycling recovers '
      + 'valuable zinc, manganese, and steel '
      + 'that would otherwise require '
      + 'energy-intensive mining. The [EPA]'
      + '(https://www.epa.gov/warm) emphasizes '
      + 'that improper disposal risks toxic '
      + 'leaching into soil and groundwater. '
      + 'Many retailers and municipal centers '
      + 'offer free battery drop-off programs.',
    ja:
      '単三電池1本のリサイクルで約**95gの'
      + 'CO2**を防ぎ、有害な重金属の埋立地'
      + 'への流出を防止します。電池リサイクル'
      + 'では亜鉛、マンガン、鉄などの貴重な'
      + '金属を回収し、エネルギー集約的な'
      + '採掘を回避します。[EPA]'
      + '(https://www.epa.gov/warm)は不適切な'
      + '廃棄が土壌や地下水への有害物質浸出'
      + 'リスクを高めると警告しています。'
      + '多くの小売店や自治体が無料の電池'
      + '回収プログラムを提供しています。',
    es:
      'Reciclar una sola pila AA evita '
      + 'aproximadamente **95g de CO2** y '
      + 'mantiene metales pesados tóxicos fuera '
      + 'de los vertederos. El reciclaje de '
      + 'pilas recupera zinc, manganeso y acero '
      + 'valiosos que de otro modo requerirían '
      + 'minería intensiva en energía. La [EPA]'
      + '(https://www.epa.gov/warm) destaca que '
      + 'la eliminación inadecuada puede '
      + 'provocar filtración tóxica al suelo y '
      + 'aguas subterráneas. Muchos comercios y '
      + 'centros municipales ofrecen puntos de '
      + 'recogida gratuita de pilas.',
  },

  recycle_cooking_oil: {
    en:
      'Recycling used cooking oil saves '
      + 'approximately **150g of CO2** per '
      + 'liter by converting it into biodiesel '
      + 'that displaces fossil fuels. Pouring '
      + 'oil down the drain clogs sewer systems '
      + 'and costs municipalities millions in '
      + 'repairs. Biodiesel from waste oil '
      + 'reduces lifecycle greenhouse gas '
      + 'emissions by up to 86% compared to '
      + 'petroleum diesel ([EPA WARM]'
      + '(https://www.epa.gov/warm)). '
      + 'Many restaurants and recycling centers '
      + 'accept used cooking oil for free.',
    ja:
      '使用済み食用油のリサイクルで1リットル'
      + 'あたり約**150gのCO2**を削減でき'
      + 'ます。廃油はバイオディーゼルに変換'
      + 'され化石燃料を代替します。油を排水口'
      + 'に流すと下水管の詰まりを引き起こし、'
      + '自治体に多額の修理費用が発生します。'
      + '廃油由来のバイオディーゼルは石油'
      + 'ディーゼルと比べライフサイクル温室'
      + '効果ガスを最大86%削減します'
      + '（[EPA WARM](https://www.epa.gov'
      + '/warm)）。多くの飲食店やリサイクル'
      + 'センターが無料で廃油を回収しています。',
    es:
      'Reciclar aceite de cocina usado ahorra '
      + 'aproximadamente **150g de CO2** por '
      + 'litro al convertirlo en biodiesel que '
      + 'desplaza combustibles fósiles. Verter '
      + 'aceite por el desagüe obstruye las '
      + 'alcantarillas y cuesta millones en '
      + 'reparaciones. El biodiesel de aceite '
      + 'residual reduce las emisiones de gases '
      + 'de efecto invernadero hasta un 86% '
      + 'comparado con el diesel de petróleo '
      + '([EPA WARM](https://www.epa.gov'
      + '/warm)). Muchos restaurantes y centros '
      + 'de reciclaje aceptan aceite usado '
      + 'gratuitamente.',
  },

  // -------------------------------------------------------
  // TRANSPORT (12 actions)
  // -------------------------------------------------------
  walk_instead_drive: {
    en:
      'Walking instead of driving a short '
      + 'trip saves about **250g of CO2** by '
      + 'replacing an average 1.5km car '
      + 'journey. A typical petrol car emits '
      + '164g of CO2 per kilometer '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Walking produces zero '
      + 'tailpipe emissions and also improves '
      + 'cardiovascular health. Even replacing '
      + 'one short car trip per day adds up to '
      + 'over 90kg of CO2 saved per year.',
    ja:
      '短距離の車移動を徒歩に替えると約'
      + '**250gのCO2**を削減できます。平均'
      + '1.5kmの車移動を置き換える計算です。'
      + '一般的なガソリン車は1kmあたり164gの'
      + 'CO2を排出します（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。'
      + '徒歩は排気ガスゼロで心血管の健康にも'
      + '良い影響があります。1日1回の短距離'
      + '移動を徒歩に替えるだけで年間90kg以上'
      + 'のCO2削減になります。',
    es:
      'Caminar en vez de conducir un trayecto '
      + 'corto ahorra unos **250g de CO2** al '
      + 'reemplazar un viaje promedio de 1,5km '
      + 'en auto. Un coche de gasolina típico '
      + 'emite 164g de CO2 por kilómetro '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Caminar no produce emisiones '
      + 'y además mejora la salud '
      + 'cardiovascular. Reemplazar un viaje '
      + 'corto en auto al día suma más de 90kg '
      + 'de CO2 ahorrados al año.',
  },

  bike_short_trip: {
    en:
      'Cycling a short trip under 3km saves '
      + 'approximately **450g of CO2** compared '
      + 'to driving. Cars emit about 164g/km '
      + 'while cycling produces only ~16g/km '
      + 'from metabolic emissions '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). That is a saving of roughly '
      + '149g per kilometer. Cycling also '
      + 'reduces traffic congestion and '
      + 'improves air quality in urban areas '
      + '([Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)).',
    ja:
      '3km未満の短距離を自転車で移動すると'
      + '車と比べ約**450gのCO2**を削減でき'
      + 'ます。車は1kmあたり約164gのCO2を'
      + '排出しますが、自転車は代謝由来の'
      + '約16g/kmのみです（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。'
      + '1kmあたり約149gの節約になります。'
      + '自転車は交通渋滞の緩和や都市部の'
      + '大気質改善にも貢献します'
      + '（[Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)）。',
    es:
      'Ir en bicicleta en un trayecto corto '
      + 'de menos de 3km ahorra '
      + 'aproximadamente **450g de CO2** '
      + 'comparado con conducir. Los coches '
      + 'emiten unos 164g/km mientras que la '
      + 'bicicleta produce solo ~16g/km por '
      + 'emisiones metabólicas ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). '
      + 'Eso supone un ahorro de unos 149g por '
      + 'kilómetro. La bicicleta también reduce '
      + 'la congestión y mejora la calidad del '
      + 'aire urbano ([Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)).',
  },

  bike_medium_trip: {
    en:
      'Cycling a medium trip of 3-10km saves '
      + 'roughly **1,000g of CO2** versus '
      + 'driving the same distance. At an '
      + 'average of 6.5km, the saving is about '
      + '149g per kilometer, totaling ~970g '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Medium-distance cycling is '
      + 'feasible for most commutes and errands '
      + '([Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)). E-bikes make '
      + 'these distances accessible to an even '
      + 'wider range of riders.',
    ja:
      '3〜10kmの中距離を自転車で移動すると'
      + '車と比べ約**1,000gのCO2**を削減'
      + 'できます。平均6.5kmで1kmあたり約'
      + '149gの節約、合計約970gです'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。中距離の自転車移動は多くの'
      + '通勤や用事に実用的です（[Our World '
      + 'in Data](https://ourworldindata.org'
      + '/travel-carbon-footprint)）。'
      + '電動アシスト自転車ならより多くの人が'
      + 'この距離を快適に走れます。',
    es:
      'Ir en bicicleta en un trayecto medio '
      + 'de 3-10km ahorra aproximadamente '
      + '**1.000g de CO2** frente a conducir. '
      + 'Con un promedio de 6,5km, el ahorro es '
      + 'de unos 149g por kilómetro, totalizando '
      + '~970g ([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). El ciclismo de media distancia '
      + 'es viable para la mayoría de trayectos '
      + '([Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)). Las bicicletas '
      + 'eléctricas hacen estas distancias '
      + 'accesibles para más personas.',
  },

  public_transport: {
    en:
      'Taking public transit instead of '
      + 'driving saves roughly **1,000g of '
      + 'CO2** on an average 10km commute. '
      + 'Buses and trains emit 60-104g/km less '
      + 'per passenger than a solo car trip '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Public transit also reduces '
      + 'traffic congestion and urban air '
      + 'pollution ([Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)). Ridership growth '
      + 'supports more frequent service, '
      + 'creating a positive feedback loop.',
    ja:
      '車の代わりに公共交通機関を利用すると'
      + '平均10kmの通勤で約**1,000gのCO2**を'
      + '削減できます。バスや電車は1人あたり'
      + 'の排出量が自家用車より60〜104g/km'
      + '少なくなります（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。'
      + '公共交通は渋滞緩和や都市の大気汚染'
      + '改善にも貢献します（[Our World in '
      + 'Data](https://ourworldindata.org/travel'
      + '-carbon-footprint)）。利用者が増える'
      + 'ほど運行頻度も上がり好循環が生まれ'
      + 'ます。',
    es:
      'Usar transporte público en vez de '
      + 'conducir ahorra aproximadamente '
      + '**1.000g de CO2** en un trayecto '
      + 'promedio de 10km. Autobuses y trenes '
      + 'emiten 60-104g/km menos por pasajero '
      + 'que un auto individual ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). '
      + 'El transporte público también reduce '
      + 'la congestión y la contaminación '
      + 'urbana ([Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)). Más usuarios '
      + 'permiten un servicio más frecuente, '
      + 'creando un ciclo positivo.',
  },

  carpool: {
    en:
      'Carpooling halves per-person emissions '
      + 'to about 82g/km, saving roughly '
      + '**800g of CO2** on a 10km trip '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Sharing rides reduces the '
      + 'total number of vehicles on the road, '
      + 'easing congestion and wear on '
      + 'infrastructure. Carpooling also cuts '
      + 'individual fuel and parking costs. '
      + 'With three or more passengers, the '
      + 'per-person footprint drops below that '
      + 'of most bus routes.',
    ja:
      '相乗りすると1人あたりの排出量が約'
      + '82g/kmに半減し、10kmの移動で約'
      + '**800gのCO2**を節約できます'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。ライドシェアは道路上の'
      + '車両総数を減らし渋滞やインフラの'
      + '摩耗を軽減します。燃料費や駐車場代'
      + 'の個人負担も削減できます。3人以上で'
      + '乗ると1人あたりの排出量はほとんどの'
      + 'バス路線を下回ります。',
    es:
      'Compartir auto reduce las emisiones '
      + 'por persona a unos 82g/km, ahorrando '
      + 'aproximadamente **800g de CO2** en un '
      + 'viaje de 10km ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). Compartir '
      + 'viajes reduce el número total de '
      + 'vehículos en la carretera, aliviando '
      + 'la congestión. También reduce los '
      + 'costos de combustible y estacionamiento '
      + 'individuales. Con tres o más pasajeros, '
      + 'la huella por persona cae por debajo de '
      + 'la mayoría de rutas de autobús.',
  },

  electric_car_purchase: {
    en:
      'Choosing an electric vehicle over a '
      + 'comparable petrol car avoids roughly '
      + '**3.4 tonnes of CO2 per year** in '
      + 'tailpipe and fuel-cycle emissions. '
      + 'Over a typical 12-year ownership '
      + 'period the cumulative saving exceeds '
      + '40 tonnes ([IEA Global EV Outlook]'
      + '(https://www.iea.org/reports'
      + '/global-ev-outlook)). While '
      + 'manufacturing an EV has a higher '
      + 'upfront carbon cost, most studies '
      + 'show breakeven within 1-3 years of '
      + 'driving ([Carbon Brief]'
      + '(https://www.carbonbrief.org/)). '
      + 'Pairing an EV with renewable-energy '
      + 'charging maximises the climate '
      + 'benefit.',
    ja:
      '同等のガソリン車の代わりに電気自動車'
      + 'を選ぶと、排気ガスと燃料サイクルの'
      + '排出を合わせ年間約**3.4トンのCO2**'
      + 'を回避できます。12年間の一般的な'
      + '保有期間で累計40トン以上の削減に'
      + 'なります（[IEA Global EV Outlook]'
      + '(https://www.iea.org/reports'
      + '/global-ev-outlook)）。EVの製造時'
      + 'の炭素コストは高いものの、多くの'
      + '研究で1〜3年の走行で損益分岐点に'
      + '達するとされています（[Carbon '
      + 'Brief](https://www.carbonbrief.org'
      + '/)）。再生可能エネルギーでの充電'
      + 'を組み合わせると気候面の効果を'
      + '最大化できます。',
    es:
      'Elegir un vehículo eléctrico en vez '
      + 'de un coche de gasolina comparable '
      + 'evita unas **3,4 toneladas de CO2 '
      + 'al año** en emisiones del tubo de '
      + 'escape y del ciclo de combustible. '
      + 'A lo largo de un período típico de '
      + 'propiedad de 12 años, el ahorro '
      + 'acumulado supera las 40 toneladas '
      + '([IEA Global EV Outlook]'
      + '(https://www.iea.org/reports'
      + '/global-ev-outlook)). Aunque la '
      + 'fabricación de un VE tiene un costo '
      + 'de carbono inicial mayor, la mayoría '
      + 'de estudios muestran un punto de '
      + 'equilibrio en 1-3 años de uso '
      + '([Carbon Brief]'
      + '(https://www.carbonbrief.org/)). '
      + 'Combinar un VE con carga de energía '
      + 'renovable maximiza el beneficio '
      + 'climático.',
  },

  train_vs_flight: {
    en:
      'Choosing a train over a domestic flight '
      + 'for a 500km journey saves roughly '
      + '**110,000g (110kg) of CO2**. Trains '
      + 'emit about 37g/km while domestic '
      + 'flights produce ~273g/km per passenger '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). This makes rail travel about '
      + '7 times cleaner than flying '
      + '([Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)). A single trip '
      + 'swap equals removing a car from the '
      + 'road for nearly a month.',
    ja:
      '500kmの移動で国内線の代わりに鉄道を'
      + '選ぶと約**110,000g（110kg）のCO2**'
      + 'を削減できます。鉄道は約37g/km、'
      + '国内線は乗客1人あたり約273g/km排出'
      + 'します（[DEFRA 2024](https://www.gov'
      + '.uk/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。鉄道は飛行機より約7倍'
      + 'クリーンです（[Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)）。1回の変更で'
      + '約1ヶ月間車を使わないのと同等の効果'
      + 'があります。',
    es:
      'Elegir tren en vez de vuelo doméstico '
      + 'para un viaje de 500km ahorra '
      + 'aproximadamente **110.000g (110kg) de '
      + 'CO2**. Los trenes emiten unos 37g/km '
      + 'mientras que los vuelos domésticos '
      + 'producen ~273g/km por pasajero '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Esto hace al tren unas 7 '
      + 'veces más limpio que volar '
      + '([Our World in Data]'
      + '(https://ourworldindata.org/travel'
      + '-carbon-footprint)). Un solo cambio '
      + 'equivale a sacar un auto de la '
      + 'carretera por casi un mes.',
  },

  take_bus: {
    en:
      'Taking the bus instead of driving '
      + 'saves roughly **500g of CO2** on an '
      + '8km commute. Buses emit about 104g/km '
      + 'per passenger compared to 164g/km for '
      + 'a solo car ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). '
      + 'Modern bus fleets are increasingly '
      + 'electrified, further reducing their '
      + 'carbon footprint. Regular bus ridership '
      + 'supports route expansion and service '
      + 'improvements for the whole community.',
    ja:
      '車の代わりにバスを利用すると8kmの'
      + '通勤で約**500gのCO2**を節約でき'
      + 'ます。バスは乗客1人あたり約104g/km、'
      + '自家用車は164g/kmの排出です'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。最新のバス車両は電動化が'
      + '進みカーボンフットプリントがさらに'
      + '小さくなっています。バスの定期利用は'
      + '路線拡充やサービス改善を支えます。',
    es:
      'Tomar el autobús en vez de conducir '
      + 'ahorra aproximadamente **500g de CO2** '
      + 'en un trayecto de 8km. Los autobuses '
      + 'emiten unos 104g/km por pasajero '
      + 'frente a 164g/km de un auto individual '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Las flotas modernas son cada '
      + 'vez más eléctricas, reduciendo aún más '
      + 'su huella de carbono. El uso regular '
      + 'del autobús apoya la expansión de '
      + 'rutas y mejoras de servicio para toda '
      + 'la comunidad.',
  },

  escooter_trip: {
    en:
      'Riding an e-scooter instead of '
      + 'driving saves roughly **375g of CO2** '
      + 'on a short urban trip. E-scooters emit '
      + 'about 27-40g/km compared to 164g/km '
      + 'for a petrol car ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). '
      + 'They are ideal for last-mile '
      + 'transportation connecting transit stops '
      + 'to final destinations. Shared e-scooter '
      + 'programs have expanded rapidly in '
      + 'cities worldwide, making them easily '
      + 'accessible.',
    ja:
      '車の代わりに電動キックボードで移動'
      + 'すると短距離の都市移動で約**375gの'
      + 'CO2**を削減できます。電動キック'
      + 'ボードは約27〜40g/km、ガソリン車は'
      + '164g/kmの排出です（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。'
      + '公共交通の駅から目的地までのラスト'
      + 'マイル移動に最適です。シェアリング'
      + 'サービスが世界中の都市で急速に普及し'
      + '手軽に利用できるようになっています。',
    es:
      'Usar un patinete eléctrico en vez de '
      + 'conducir ahorra aproximadamente '
      + '**375g de CO2** en un viaje urbano '
      + 'corto. Los patinetes emiten unos '
      + '27-40g/km frente a 164g/km de un coche '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Son ideales para el transporte '
      + 'de última milla conectando paradas de '
      + 'tránsito con destinos finales. Los '
      + 'programas compartidos se han expandido '
      + 'rápidamente en ciudades de todo el '
      + 'mundo.',
  },

  ev_charging_green: {
    en:
      'Charging your electric vehicle with '
      + 'renewable energy saves about **400g '
      + 'of CO2** per charge session by '
      + 'eliminating grid electricity '
      + 'emissions. Standard grid-charged EVs '
      + 'still emit ~43g/km from fossil fuel '
      + 'power generation ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). '
      + 'Green energy charging makes your EV '
      + 'effectively zero-emission during '
      + 'operation. Solar panels, wind energy '
      + 'tariffs, or green-certified charging '
      + 'stations all qualify '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '再生可能エネルギーでEVを充電すると'
      + '1回の充電あたり約**400gのCO2**を'
      + '削減でき、送電網の化石燃料由来の'
      + '排出を排除できます。通常のEVは'
      + '火力発電由来で約43g/kmを排出します'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。グリーンエネルギー充電に'
      + 'より走行中の実質ゼロエミッションを'
      + '実現できます。太陽光パネルや風力'
      + 'エネルギー、グリーン認証済み充電'
      + 'ステーションが対象です（[Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)）。',
    es:
      'Cargar tu vehículo eléctrico con '
      + 'energía renovable ahorra unos **400g '
      + 'de CO2** por sesión de carga al '
      + 'eliminar emisiones de la red. Los VE '
      + 'cargados con red estándar aún emiten '
      + '~43g/km por generación con '
      + 'combustibles fósiles ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). '
      + 'La carga verde hace que tu VE sea '
      + 'efectivamente cero emisiones durante '
      + 'la operación. Paneles solares, tarifas '
      + 'de energía eólica o estaciones '
      + 'certificadas verdes califican '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  combine_errands: {
    en:
      'Combining multiple errands into a '
      + 'single car trip saves about **300g '
      + 'of CO2** by eliminating cold-start '
      + 'emissions and reducing total mileage. '
      + 'A cold engine produces up to 2x more '
      + 'emissions per kilometer during the '
      + 'first few minutes of driving '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)). Planning efficient routes '
      + 'also saves fuel and time. This simple '
      + 'habit is one of the easiest transport '
      + 'changes to adopt.',
    ja:
      '複数の用事を1回の車移動にまとめると'
      + 'コールドスタート時の排出削減と総走行'
      + '距離の短縮で約**300gのCO2**を節約'
      + 'できます。冷えたエンジンは走行開始'
      + '数分間、通常の最大2倍のCO2を排出'
      + 'します（[DEFRA 2024](https://www.gov'
      + '.uk/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。効率的なルート計画は燃料と'
      + '時間の節約にもなります。この簡単な'
      + '習慣は最も取り入れやすい交通手段の'
      + '改善の一つです。',
    es:
      'Combinar varias tareas en un solo '
      + 'viaje en auto ahorra unos **300g de '
      + 'CO2** al eliminar emisiones de '
      + 'arranque en frío y reducir el '
      + 'kilometraje total. Un motor frío '
      + 'produce hasta 2 veces más emisiones '
      + 'por kilómetro durante los primeros '
      + 'minutos ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). '
      + 'Planificar rutas eficientes también '
      + 'ahorra combustible y tiempo. Este '
      + 'simple hábito es uno de los cambios '
      + 'de transporte más fáciles de adoptar.',
  },

  // -------------------------------------------------------
  // FOOD (15 actions)
  // -------------------------------------------------------
  skip_high_impact_food: {
    en:
      'Replacing one beef-based meal with a '
      + 'plant-based alternative avoids '
      + 'roughly **6,000g (6kg) of CO2 '
      + 'equivalent**. Beef carries the '
      + 'heaviest climate footprint of any '
      + 'common food, requiring vast land, '
      + 'water, and feed inputs '
      + '([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/food-choice-vs-eating-local)). '
      + 'A single kilogram of beef produces '
      + '60-100kg of CO2eq across its supply '
      + 'chain, compared to just 1-3kg for '
      + 'most plant proteins '
      + '([Poore & Nemecek, Science 2018]'
      + '(https://www.science.org/doi/10.1126'
      + '/science.aaq0216)). Choosing to skip '
      + 'high-impact animal products even '
      + 'once a week compounds into hundreds '
      + 'of kilograms of savings per year.',
    ja:
      '牛肉の1食分を植物性に替えると約'
      + '**6,000g（6kg）のCO2相当**を回避'
      + 'できます。牛肉は一般的な食品の中で'
      + '最大の気候フットプリントを持ち、'
      + '膨大な土地、水、飼料を必要とします'
      + '（[Our World in Data]'
      + '(https://ourworldindata.org'
      + '/food-choice-vs-eating-local)）。'
      + '牛肉1kgあたりサプライチェーン全体'
      + 'で60〜100kgのCO2eqを排出し、'
      + '大半の植物性タンパクの1〜3kgと'
      + '対照的です（[Poore & Nemecek, '
      + 'Science 2018](https://www.science'
      + '.org/doi/10.1126/science.aaq0216)）。'
      + '週1回でも高インパクトな動物性食品'
      + 'を避ければ年間数百kgの削減に'
      + 'つながります。',
    es:
      'Evitar una porción de 100g de carne '
      + 'de res evita aproximadamente **6.000g '
      + '(6kg) de CO2 equivalente**. La carne '
      + 'de res tiene la mayor huella de '
      + 'carbono entre alimentos comunes: 60kg '
      + 'CO2e/kg en su ciclo de vida '
      + '([Poore & Nemecek 2018]'
      + '(https://ourworldindata.org/food-choice'
      + '-vs-eating-local)). Esto incluye '
      + 'metano del ganado, producción de '
      + 'pienso y cambio de uso del suelo. '
      + 'Reemplazar la res con proteína vegetal '
      + 'una vez por semana ahorra más de 300kg '
      + 'de CO2 al año ([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)).',
  },

  skip_medium_impact_food: {
    en:
      'Replacing a meal of chicken, pork, '
      + 'or fish with a plant-based option '
      + 'saves roughly **1,000g of CO2 '
      + 'equivalent**. While these proteins '
      + 'carry a lighter footprint than beef, '
      + 'they still require significant land, '
      + 'water, and feed resources '
      + '([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/food-choice-vs-eating-local)). '
      + 'Chicken produces about 6kg CO2eq per '
      + 'kilogram, pork about 7kg, and farmed '
      + 'fish 5-13kg, versus 1-3kg for most '
      + 'plant proteins '
      + '([Poore & Nemecek, Science 2018]'
      + '(https://www.science.org/doi/10.1126'
      + '/science.aaq0216)). Swapping a few '
      + 'medium-impact meals per week is a '
      + 'practical way to lower your dietary '
      + 'carbon footprint without going fully '
      + 'vegetarian.',
    ja:
      '鶏肉、豚肉、魚の1食分を植物性の'
      + '選択肢に替えると約**1,000gのCO2'
      + '相当**を削減できます。牛肉ほどでは'
      + 'ないものの相当な土地、水、飼料資源'
      + 'を必要とします（[Our World in Data]'
      + '(https://ourworldindata.org'
      + '/food-choice-vs-eating-local)）。'
      + '鶏肉は約6kg CO2eq/kg、豚肉は約'
      + '7kg、養殖魚は5〜13kgで植物性'
      + 'タンパクの1〜3kgと比較されます'
      + '（[Poore & Nemecek, Science 2018]'
      + '(https://www.science.org/doi/10.1126'
      + '/science.aaq0216)）。週に数食を'
      + '中程度インパクトの食品から替えるのは'
      + '完全菜食にならずとも食事のカーボン'
      + 'フットプリントを下げる実用的な'
      + '方法です。',
    es:
      'Reemplazar una comida de pollo, cerdo '
      + 'o pescado por una opción vegetal '
      + 'ahorra aproximadamente **1.000g de '
      + 'CO2 equivalente**. Aunque estas '
      + 'proteínas tienen menor huella que la '
      + 'carne de res, aún requieren '
      + 'importantes recursos de tierra, agua '
      + 'y pienso ([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/food-choice-vs-eating-local)). '
      + 'El pollo produce unos 6kg CO2eq/kg, '
      + 'el cerdo 7kg y el pescado de '
      + 'acuicultura 5-13kg, frente a 1-3kg '
      + 'de la mayoría de proteínas vegetales '
      + '([Poore & Nemecek, Science 2018]'
      + '(https://www.science.org/doi/10.1126'
      + '/science.aaq0216)). Sustituir '
      + 'algunas comidas de impacto medio por '
      + 'semana es una forma práctica de '
      + 'reducir la huella de carbono '
      + 'alimentaria sin ser completamente '
      + 'vegetariano.',
  },

  no_food_waste: {
    en:
      'Preventing daily food waste avoids '
      + 'roughly **400g of CO2 equivalent** '
      + 'by keeping organic matter out of '
      + 'landfills. The [EPA](https://www.epa'
      + '.gov/land-research/quantifying-methane'
      + '-emissions-landfilled-food-waste) '
      + 'reports that 58% of fugitive methane '
      + 'from landfills originates from food '
      + 'waste. Planning meals, using shopping '
      + 'lists, and storing food properly are '
      + 'effective strategies. Globally, about '
      + 'one-third of all food produced is '
      + 'wasted, making this a critical area '
      + 'for climate action.',
    ja:
      '毎日の食品ロスを防ぐと約**400gの'
      + 'CO2相当**を回避できます。有機物を'
      + '埋立地から遠ざけるためです。[EPA]'
      + '(https://www.epa.gov/land-research'
      + '/quantifying-methane-emissions-'
      + 'landfilled-food-waste)によると埋立地'
      + 'からの逸散メタンの58%は食品廃棄物'
      + '由来です。献立計画、買い物リストの'
      + '活用、適切な食品保存が有効な対策です。'
      + '世界で生産される食料の約3分の1が廃棄'
      + 'されており、気候変動対策の重要な分野'
      + 'です。',
    es:
      'Evitar el desperdicio diario de '
      + 'alimentos previene aproximadamente '
      + '**400g de CO2 equivalente** al '
      + 'mantener materia orgánica fuera de '
      + 'vertederos. La [EPA](https://www.epa'
      + '.gov/land-research/quantifying-methane'
      + '-emissions-landfilled-food-waste) '
      + 'informa que el 58% del metano fugitivo '
      + 'de vertederos proviene de residuos '
      + 'alimentarios. Planificar comidas, usar '
      + 'listas de compras y almacenar '
      + 'correctamente son estrategias '
      + 'efectivas. Globalmente, un tercio de '
      + 'los alimentos producidos se desperdicia.',
  },

  plant_milk: {
    en:
      'Choosing plant milk over dairy saves '
      + 'roughly **460g of CO2** per 250ml '
      + 'serving. Dairy milk emits about 3.2kg '
      + 'CO2 per liter versus 0.4-1.0kg for '
      + 'plant alternatives ([Poore & '
      + 'Nemecek 2018](https://ourworldindata'
      + '.org/food-choice-vs-eating-local)). '
      + 'Oat milk has the lowest footprint '
      + 'among plant milks, followed by soy '
      + '([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)). '
      + 'Dairy also requires 10x more land and '
      + '2-3x more water per liter than most '
      + 'plant milks.',
    ja:
      '乳製品の代わりに植物性ミルクを選ぶと'
      + '250mlあたり約**460gのCO2**を削減'
      + 'できます。牛乳は1リットルあたり約'
      + '3.2kgのCO2を排出するのに対し、'
      + '植物性は0.4〜1.0kgです（[Poore & '
      + 'Nemecek 2018](https://ourworldindata'
      + '.org/food-choice-vs-eating-local)）。'
      + 'オーツミルクが植物性ミルクの中で最も'
      + '環境負荷が低く、次に豆乳です'
      + '（[Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)）。'
      + '乳製品は植物性に比べ土地は10倍、水は'
      + '2〜3倍必要です。',
    es:
      'Elegir leche vegetal en vez de láctea '
      + 'ahorra aproximadamente **460g de CO2** '
      + 'por porción de 250ml. La leche láctea '
      + 'emite unos 3,2kg de CO2 por litro '
      + 'frente a 0,4-1,0kg para alternativas '
      + 'vegetales ([Poore & Nemecek 2018]'
      + '(https://ourworldindata.org/food-choice'
      + '-vs-eating-local)). La leche de avena '
      + 'tiene la menor huella entre las '
      + 'vegetales, seguida por la de soja '
      + '([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)). '
      + 'Los lácteos requieren 10 veces más '
      + 'tierra y 2-3 veces más agua por litro.',
  },

  seasonal_produce: {
    en:
      'Buying seasonal produce saves roughly '
      + '**500g of CO2** per purchase by '
      + 'avoiding energy-intensive greenhouse '
      + 'cultivation. Out-of-season fruits and '
      + 'vegetables grown in heated greenhouses '
      + 'use 5-10x more energy than seasonal '
      + 'outdoor farming ([Carbon Brief]'
      + '(https://interactive.carbonbrief.org'
      + '/what-is-the-climate-impact-of-eating'
      + '-meat-and-dairy/index.html)). '
      + 'Seasonal produce is also typically '
      + 'fresher and more nutritious. Eating '
      + 'with the seasons connects you to '
      + 'local agricultural rhythms.',
    ja:
      '旬の農産物を買うと1回の購入で約'
      + '**500gのCO2**を削減できます。'
      + 'エネルギー集約的なハウス栽培を避ける'
      + 'ためです。旬でない果物や野菜を加温'
      + 'ハウスで栽培すると、露地の季節栽培'
      + 'より5〜10倍のエネルギーを使います'
      + '（[Carbon Brief]'
      + '(https://interactive.carbonbrief.org'
      + '/what-is-the-climate-impact-of-eating'
      + '-meat-and-dairy/index.html)）。'
      + '旬の食材は鮮度も栄養価も高いのが'
      + '一般的です。旬を意識した食生活は地域'
      + 'の農業リズムとのつながりを生みます。',
    es:
      'Comprar productos de temporada ahorra '
      + 'aproximadamente **500g de CO2** por '
      + 'compra al evitar el cultivo intensivo '
      + 'en invernaderos. Las frutas y verduras '
      + 'fuera de temporada cultivadas en '
      + 'invernaderos calefactados usan 5-10 '
      + 'veces más energía ([Carbon Brief]'
      + '(https://interactive.carbonbrief.org'
      + '/what-is-the-climate-impact-of-eating'
      + '-meat-and-dairy/index.html)). '
      + 'Los productos de temporada son '
      + 'típicamente más frescos y nutritivos. '
      + 'Comer con las estaciones te conecta '
      + 'con los ritmos agrícolas locales.',
  },

  skip_food_delivery: {
    en:
      'Skipping a food delivery order and '
      + 'eating from your own kitchen avoids '
      + 'roughly **600g of CO2** from extra '
      + 'vehicle trips, disposable packaging, '
      + 'and commercial cooking energy. '
      + 'Delivery services add a last-mile '
      + 'transport leg that home cooking '
      + 'eliminates entirely '
      + '([Carbon Trust]'
      + '(https://www.carbontrust.com/)). '
      + 'Single-use containers, cutlery, and '
      + 'bags from delivery orders generate '
      + 'additional waste and embedded '
      + 'emissions. Cooking at home also tends '
      + 'to produce less food waste, since '
      + 'portions are self-managed.',
    ja:
      'フードデリバリーをやめて自炊すると'
      + '約**600gのCO2**を回避できます。'
      + '配達車両の追加移動、使い捨て包装、'
      + '業務用調理のエネルギーが原因です。'
      + 'デリバリーには自炊では不要なラスト'
      + 'マイル輸送が加わります'
      + '（[Carbon Trust]'
      + '(https://www.carbontrust.com/)）。'
      + '使い捨て容器、カトラリー、袋は'
      + '追加の廃棄物と内包排出を生みます。'
      + '自炊は量を自分で管理できるため'
      + '食品ロスの削減にもつながります。',
    es:
      'Saltarse un pedido de comida a '
      + 'domicilio y comer de tu propia '
      + 'cocina evita unas **600g de CO2** '
      + 'por viajes adicionales de vehículos, '
      + 'empaques desechables y energía de '
      + 'cocción comercial. Los servicios de '
      + 'entrega añaden un tramo de transporte '
      + 'de última milla que cocinar en casa '
      + 'elimina por completo '
      + '([Carbon Trust]'
      + '(https://www.carbontrust.com/)). '
      + 'Los envases, cubiertos y bolsas '
      + 'desechables de los pedidos generan '
      + 'residuos adicionales y emisiones '
      + 'incorporadas. Cocinar en casa también '
      + 'suele producir menos desperdicio de '
      + 'alimentos, ya que las porciones se '
      + 'gestionan personalmente.',
  },

  vegan_day: {
    en:
      'Eating fully plant-based for a day '
      + 'saves roughly **7,000g (7kg) of CO2 '
      + 'equivalent** compared to a standard '
      + 'omnivore diet. This accounts for '
      + 'avoided emissions from meat, dairy, '
      + 'and eggs across all meals '
      + '([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)). '
      + 'A vegan diet uses 75% less land and '
      + '50% less water than a meat-heavy diet '
      + '([Poore & Nemecek 2018]'
      + '(https://ourworldindata.org/food-choice'
      + '-vs-eating-local)). Even one vegan day '
      + 'per week saves over 350kg of CO2 '
      + 'annually.',
    ja:
      '1日完全に植物性の食事にすると標準的な'
      + '雑食と比べ約**7,000g（7kg）のCO2'
      + '相当**を削減できます。全食事での肉、'
      + '乳製品、卵の回避分を含みます'
      + '（[Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)）。'
      + 'ビーガン食は肉食中心の食事より土地を'
      + '75%、水を50%少なく使います'
      + '（[Poore & Nemecek 2018]'
      + '(https://ourworldindata.org/food-choice'
      + '-vs-eating-local)）。週1日でも年間'
      + '350kg以上のCO2を節約できます。',
    es:
      'Comer completamente vegetal por un día '
      + 'ahorra aproximadamente **7.000g (7kg) '
      + 'de CO2 equivalente** comparado con una '
      + 'dieta omnívora estándar. Esto incluye '
      + 'las emisiones evitadas de carne, '
      + 'lácteos y huevos en todas las comidas '
      + '([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)). '
      + 'Una dieta vegana usa 75% menos tierra '
      + 'y 50% menos agua ([Poore & '
      + 'Nemecek 2018](https://ourworldindata'
      + '.org/food-choice-vs-eating-local)). '
      + 'Incluso un día vegano por semana ahorra '
      + 'más de 350kg de CO2 al año.',
  },

  bring_lunch: {
    en:
      'Bringing lunch from home saves '
      + 'roughly **300g of CO2** by avoiding '
      + 'takeout packaging and delivery '
      + 'emissions. Restaurant and delivery '
      + 'meals use single-use containers, '
      + 'plastic cutlery, and bags that each '
      + 'carry their own carbon footprint. '
      + 'A reusable lunch container eliminates '
      + 'this waste stream entirely. Over a '
      + 'year of workdays (~230), bringing '
      + 'lunch can save nearly 70kg of CO2 '
      + '([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)).',
    ja:
      'お弁当を持参すると約**300gのCO2**を'
      + '削減でき、テイクアウトの包装や配達の'
      + '排出を回避できます。外食やデリバリー'
      + 'は使い捨て容器、プラスチック製カト'
      + 'ラリー、袋を使い各々にカーボンフット'
      + 'プリントがあります。再利用可能な弁当'
      + '箱でこの廃棄物を完全になくせます。'
      + '年間約230日のお弁当持参で約70kgの'
      + 'CO2を削減できます（[Our World in '
      + 'Data](https://ourworldindata.org'
      + '/environmental-impacts-of-food)）。',
    es:
      'Llevar almuerzo de casa ahorra '
      + 'aproximadamente **300g de CO2** al '
      + 'evitar empaques de comida para llevar '
      + 'y emisiones de entrega. Las comidas de '
      + 'restaurante usan envases desechables, '
      + 'cubiertos de plástico y bolsas, cada '
      + 'uno con su propia huella de carbono. '
      + 'Un recipiente reutilizable elimina '
      + 'estos residuos por completo. En un año '
      + 'laboral (~230 días), llevar almuerzo '
      + 'puede ahorrar casi 70kg de CO2 '
      + '([Our World in Data]'
      + '(https://ourworldindata.org'
      + '/environmental-impacts-of-food)).',
  },

};

module.exports = descriptions;
