/**
 * Long descriptions for eco-actions:
 * COMMUNITY, ADVOCACY, SDG-TARGETED.
 *
 * Each description is 3-5 sentences with markdown
 * formatting, bold CO2 figures, and source links.
 *
 * This is a partial file merged into the final
 * descriptions module.
 */

const descriptions = {
  // ---------------------------------------------------
  // COMMUNITY (10 actions)
  // ---------------------------------------------------
  tree_planting: {
    en:
      'A single tree absorbs roughly '
      + '**15kg of CO2 per year** through '
      + 'photosynthesis, accumulating '
      + '150-250kg over its first decade '
      + '([EPA GHG Equivalencies]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)). '
      + 'Trees also filter air pollutants, '
      + 'reduce urban heat islands, and '
      + 'provide critical habitat for '
      + 'wildlife ([UN SDG 15]'
      + '(https://sdgs.un.org/goals'
      + '/goal15)). '
      + 'Planting even one tree is a '
      + 'lasting investment in your '
      + 'community and the climate for '
      + 'decades to come.',
    ja:
      '1本の木は光合成により年間約'
      + '**15kgのCO2**を吸収し、最初の'
      + '10年間で150〜250kgを蓄積します'
      + '（[EPA温室効果ガス換算]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)）。'
      + '樹木はまた大気汚染物質を濾過し、'
      + '都市のヒートアイランドを緩和し、'
      + '野生生物の重要な生息地を提供します'
      + '（[国連SDG 15]'
      + '(https://sdgs.un.org/goals'
      + '/goal15)）。'
      + '1本の植樹でも、地域社会と気候への'
      + '長期的な投資になります。',
    es:
      'Un solo árbol absorbe aproximadamente '
      + '**15kg de CO2 al año** mediante la '
      + 'fotosíntesis, acumulando 150-250kg '
      + 'en su primera década '
      + '([EPA Equivalencias GEI]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)). '
      + 'Los árboles también filtran '
      + 'contaminantes, reducen las islas de '
      + 'calor urbanas y proporcionan hábitat '
      + 'para la vida silvestre '
      + '([ONU ODS 15]'
      + '(https://sdgs.un.org/goals'
      + '/goal15)). '
      + 'Plantar un árbol es una inversión '
      + 'duradera en tu comunidad y el clima.',
  },

  beach_cleanup: {
    en:
      'Beach and park cleanups prevent '
      + 'plastic waste from degrading into '
      + 'microplastics that contaminate '
      + 'marine ecosystems and damage ocean '
      + 'carbon sinks. Healthy oceans '
      + 'absorb roughly 30% of human-produced '
      + 'CO2 ([IPCC](https://www.ipcc.ch/)). '
      + 'The carbon benefit is indirect and '
      + 'hard to quantify per cleanup, so '
      + 'this action is logged for its '
      + 'ecological value rather than a '
      + 'specific CO2 figure ([UN SDG 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)). '
      + 'Removing debris directly protects '
      + 'sea turtles, birds, and fish from '
      + 'ingestion and entanglement.',
    ja:
      'ビーチや公園の清掃は、プラスチックが'
      + 'マイクロプラスチックに分解されて'
      + '海洋生態系を汚染し、海の炭素吸収源を'
      + '損なうのを防ぎます。健全な海洋は'
      + '人為的CO2の約30%を吸収しています'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '炭素への効果は間接的で1回ごとに'
      + '定量化しにくいため、このアクション'
      + 'は特定のCO2削減量ではなく生態系への'
      + '貢献として記録します'
      + '（[国連SDG 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)）。'
      + 'ゴミの除去はウミガメや鳥、魚を'
      + '誤飲や絡まりから直接守ります。',
    es:
      'Las limpiezas de playas y parques '
      + 'evitan que el plástico se degrade '
      + 'en microplásticos que contaminan '
      + 'los ecosistemas marinos y dañan los '
      + 'sumideros de carbono oceánicos. '
      + 'Los océanos sanos absorben el 30% '
      + 'del CO2 humano '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'El beneficio en carbono es indirecto '
      + 'y difícil de cuantificar por '
      + 'limpieza, por eso esta acción se '
      + 'registra por su valor ecológico y no '
      + 'por una cifra concreta de CO2 '
      + '([ONU ODS 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)). '
      + 'Retirar residuos protege directamente '
      + 'a tortugas, aves y peces de la '
      + 'ingestión y el enredo.',
  },

  buy_local_produce: {
    en:
      'Buying locally grown food from a '
      + 'farmers market, farm stand, or '
      + 'local supplier saves roughly '
      + '**300g of CO2 per trip** because '
      + 'local food travels about 80km '
      + 'versus 2,400km for typical '
      + 'supermarket produce. Shorter '
      + 'supply chains mean less '
      + 'refrigerated transport, less '
      + 'packaging, and fresher food '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Shopping locally also supports '
      + 'small-scale farmers and '
      + 'strengthens regional food security '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Every local purchase is a vote '
      + 'for a more sustainable food '
      + 'system.',
    ja:
      'ファーマーズマーケットや直売所、'
      + '地元の生産者から地場産の食材を'
      + '買うと1回の買い物で約**300gの'
      + 'CO2**を削減できます。地場産食品の'
      + '輸送距離は約80kmで一般的なスーパー'
      + 'の約2,400kmと比べ大幅に短いため'
      + 'です。短いサプライチェーンは冷蔵'
      + '輸送と包装を減らしより新鮮な食品'
      + 'を届けます（[WRAP UK]'
      + '(https://wrap.org.uk/)）。地元での'
      + '購入は小規模農家の支援と地域の食料'
      + '安全保障の強化にもつながります'
      + '（[国連SDG 12](https://sdgs.un.org'
      + '/goals/goal12)）。地元での購入は'
      + 'より持続可能な食料システムへの一票'
      + 'です。',
    es:
      'Comprar alimentos cultivados '
      + 'localmente en un mercado de '
      + 'agricultores, puesto de granja o '
      + 'proveedor local ahorra '
      + 'aproximadamente **300g de CO2 por '
      + 'visita** porque los alimentos locales '
      + 'viajan unos 80km frente a los 2.400km '
      + 'típicos del supermercado. Cadenas de '
      + 'suministro más cortas significan '
      + 'menos transporte refrigerado, menos '
      + 'empaquetado y alimentos más frescos '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Comprar local también apoya a '
      + 'pequeños agricultores y fortalece la '
      + 'seguridad alimentaria regional '
      + '([ODS 12 de la ONU]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). Cada compra local es un '
      + 'voto por un sistema alimentario más '
      + 'sostenible.',
  },

  share_sustainability_tip: {
    en:
      'Sharing sustainability tips costs '
      + 'nothing but can multiply your impact '
      + 'exponentially. Research shows that '
      + 'eco-friendly habits are socially '
      + 'contagious and spread through '
      + 'personal networks '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'When you share a practical tip, you '
      + 'lower the barrier for others to act '
      + 'on climate ([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'One conversation can inspire a '
      + 'chain of behavior change that far '
      + 'exceeds any single action.',
    ja:
      'サステナビリティのヒントを共有する'
      + 'ことはコストゼロで、影響を指数関数'
      + '的に拡大できます。研究によると、'
      + 'エコフレンドリーな習慣は社会的に'
      + '伝染し、個人ネットワークを通じて'
      + '広がります'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '実用的なヒントを共有することで、'
      + '他の人が気候変動対策に取り組む'
      + 'ハードルを下げられます'
      + '（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + '1つの会話が、個別の行動をはるかに'
      + '超える行動変容の連鎖を生みます。',
    es:
      'Compartir consejos de sostenibilidad '
      + 'no cuesta nada pero puede multiplicar'
      + ' tu impacto exponencialmente. Las '
      + 'investigaciones muestran que los '
      + 'hábitos ecológicos son socialmente '
      + 'contagiosos '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Cuando compartes un consejo práctico,'
      + ' reduces la barrera para que otros '
      + 'actúen por el clima '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Una conversación puede inspirar una '
      + 'cadena de cambio de comportamiento.',
  },

  community_garden: {
    en:
      'Participating in a community garden '
      + 'saves an estimated **200g of CO2** '
      + 'per session by reducing food miles '
      + 'and supporting local composting. '
      + 'Community gardens also build social '
      + 'cohesion, provide fresh produce to '
      + 'food-insecure neighborhoods, and '
      + 'increase urban green space '
      + '([UN SDG 11]'
      + '(https://sdgs.un.org/goals'
      + '/goal11)). '
      + 'Gardens act as carbon sinks and '
      + 'help manage stormwater runoff '
      + '([EPA GHG Equivalencies]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)). '
      + 'Growing food together fosters '
      + 'environmental stewardship across '
      + 'generations.',
    ja:
      'コミュニティガーデンへの参加は、'
      + 'フードマイルの削減と地域の堆肥化'
      + '支援により1回あたり推定**200gの'
      + 'CO2**を削減します。'
      + 'コミュニティガーデンは社会的結束を'
      + '築き、食料不安のある地域に新鮮な'
      + '農産物を提供し、都市の緑地を増やし'
      + 'ます（[国連SDG 11]'
      + '(https://sdgs.un.org/goals'
      + '/goal11)）。'
      + '菜園は炭素吸収源として機能し、'
      + '雨水流出の管理にも役立ちます'
      + '（[EPA温室効果ガス換算]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)）。'
      + '一緒に食べ物を育てることは、世代を'
      + '超えた環境保全意識を育みます。',
    es:
      'Participar en un huerto comunitario '
      + 'ahorra unas **200g de CO2** por '
      + 'sesión al reducir los kilómetros '
      + 'alimentarios y apoyar el compostaje '
      + 'local. Los huertos comunitarios '
      + 'fortalecen la cohesión social y '
      + 'proporcionan productos frescos '
      + '([ONU ODS 11]'
      + '(https://sdgs.un.org/goals'
      + '/goal11)). '
      + 'Funcionan como sumideros de carbono '
      + 'y ayudan a gestionar la escorrentía '
      + '([EPA Equivalencias GEI]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)). '
      + 'Cultivar juntos fomenta la '
      + 'responsabilidad ambiental.',
  },

  volunteer_environment: {
    en:
      'Volunteering for an environmental '
      + 'cause channels hands-on effort into '
      + 'ecological restoration — planting '
      + 'trees, restoring wetlands, monitoring '
      + 'wildlife, and educating communities. '
      + 'The carbon benefit is indirect and '
      + 'hard to quantify per session, so this '
      + 'action is logged for its systemic and '
      + 'ecological value rather than a '
      + 'specific CO2 figure '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Collective action amplifies impact '
      + 'far beyond what any individual can '
      + 'achieve alone '
      + '([IPCC](https://www.ipcc.ch/)), '
      + 'strengthening long-term environmental '
      + 'resilience in your community.',
    ja:
      '環境ボランティアは、植樹、湿地の復元、'
      + '野生生物の監視、地域教育といった'
      + '現場での生態系復元活動に時間と労力'
      + 'を直接投じる行動です。炭素への効果は'
      + '間接的で1回ごとに定量化しにくいため、'
      + 'このアクションは特定のCO2削減量では'
      + 'なく、システム的・生態系への貢献'
      + 'として記録します'
      + '（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + '集団行動は個人単独では達成できない'
      + '規模の影響を生み出し'
      + '（[IPCC](https://www.ipcc.ch/)）、'
      + '地域の長期的な環境回復力を'
      + '強化します。',
    es:
      'El voluntariado ambiental canaliza '
      + 'esfuerzo directo en restauración '
      + 'ecológica: plantar árboles, restaurar '
      + 'humedales, monitorear fauna y educar '
      + 'comunidades. El beneficio en carbono '
      + 'es indirecto y difícil de cuantificar '
      + 'por sesión, por eso esta acción se '
      + 'registra por su valor sistémico y '
      + 'ecológico y no por una cifra concreta '
      + 'de CO2 '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'La acción colectiva amplifica el '
      + 'impacto mucho más allá de lo que '
      + 'cualquier individuo puede lograr solo '
      + '([IPCC](https://www.ipcc.ch/)), '
      + 'fortaleciendo la resiliencia ambiental '
      + 'local a largo plazo.',
  },

  teach_child_eco: {
    en:
      'Teaching a child about sustainability '
      + 'creates lifelong eco-conscious '
      + 'habits that compound over decades. '
      + 'Environmental education in childhood '
      + 'is one of the strongest predictors '
      + 'of adult pro-environmental behavior '
      + '([UN SDG 4]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)). '
      + 'Children who learn about ecosystems '
      + 'early become advocates who influence '
      + 'their families and peers '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'The next generation holds the key '
      + 'to long-term climate solutions.',
    ja:
      '子供にサステナビリティを教えること'
      + 'は、何十年にもわたって複利的に'
      + '増える生涯にわたるエコ意識の習慣を'
      + '作ります。幼少期の環境教育は、成人'
      + 'の環境配慮行動の最も強い予測因子の'
      + '一つです（[国連SDG 4]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)）。'
      + '生態系について早くから学んだ子供は'
      + '家族や仲間に影響を与える提唱者に'
      + 'なります'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '次の世代が長期的な気候ソリューション'
      + 'の鍵を握っています。',
    es:
      'Enseñar a un niño sobre '
      + 'sostenibilidad crea hábitos '
      + 'ecológicos de por vida que se '
      + 'acumulan durante décadas. La '
      + 'educación ambiental infantil es uno '
      + 'de los predictores más fuertes del '
      + 'comportamiento proambiental adulto '
      + '([ONU ODS 4]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)). '
      + 'Los niños que aprenden sobre '
      + 'ecosistemas se convierten en '
      + 'defensores que influyen en familias '
      + 'y compañeros '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'La próxima generación tiene la '
      + 'clave de las soluciones climáticas.',
  },

  support_eco_business: {
    en:
      'Supporting an eco-friendly business '
      + 'saves an estimated **200g of CO2** '
      + 'per purchase by directing demand '
      + 'toward sustainable production '
      + 'methods. Consumer spending is a '
      + 'powerful market signal that drives '
      + 'companies to adopt greener practices '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Sustainable businesses often use '
      + 'renewable energy, ethical sourcing, '
      + 'and circular design principles '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Every purchase is a vote for the '
      + 'kind of economy you want to see.',
    ja:
      'エコフレンドリーなビジネスを支援'
      + 'すると、持続可能な生産方法への需要'
      + 'を向けることで1回の購入あたり推定'
      + '**200gのCO2**を削減します。'
      + '消費者支出は企業にグリーンな慣行を'
      + '採用させる強力な市場シグナルです'
      + '（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。'
      + '持続可能な企業は再生可能エネルギー、'
      + '倫理的な調達、循環型設計原則を'
      + '使用することが多いです'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + 'すべての購入は、望む経済への一票'
      + 'です。',
    es:
      'Apoyar un negocio ecológico ahorra '
      + 'unas **200g de CO2** por compra al '
      + 'dirigir la demanda hacia métodos de '
      + 'producción sostenibles. El gasto '
      + 'del consumidor es una señal de '
      + 'mercado poderosa que impulsa a las '
      + 'empresas a adoptar prácticas verdes '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Los negocios sostenibles suelen usar '
      + 'energía renovable y diseño circular '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Cada compra es un voto por la '
      + 'economía que quieres ver.',
  },

  organize_swap: {
    en:
      'Organizing a clothing or item swap '
      + 'prevents an estimated **1,000g of '
      + 'CO2** by keeping usable goods out '
      + 'of landfills. A single new garment '
      + 'generates roughly 14kg of CO2 '
      + 'during production, so each swapped '
      + 'item avoids significant emissions '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Swaps promote a circular economy '
      + 'where resources are reused rather '
      + 'than discarded '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'They also build community and make '
      + 'sustainable living fun and '
      + 'accessible.',
    ja:
      '衣類やアイテムのスワップを企画する'
      + 'ことで、使用可能な物を埋立地から'
      + '守り、推定**1,000gのCO2**を削減'
      + 'します。新しい衣服1着の生産では約'
      + '14kgのCO2が発生するため、交換される'
      + '各アイテムは大幅な排出を回避します'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + 'スワップは資源を廃棄するのではなく'
      + '再利用する循環型経済を促進します'
      + '（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。'
      + 'コミュニティを築き、持続可能な生活'
      + 'を楽しく身近にします。',
    es:
      'Organizar un intercambio de ropa o '
      + 'artículos evita unas **1.000g de '
      + 'CO2** al mantener bienes útiles '
      + 'fuera de los vertederos. Una prenda '
      + 'nueva genera unos 14kg de CO2 '
      + 'durante su producción, así que cada '
      + 'artículo intercambiado evita '
      + 'emisiones significativas '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Los intercambios promueven una '
      + 'economía circular donde los recursos '
      + 'se reutilizan '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'También crean comunidad y hacen '
      + 'la vida sostenible accesible.',
  },

  use_library: {
    en:
      'Borrowing a book, movie, or other '
      + 'media from the library instead of '
      + 'buying new saves roughly '
      + '**1,000g of CO2** per item from '
      + 'manufacturing, packaging, and '
      + 'shipping. A single paperback book '
      + 'generates about 1kg of CO2 to '
      + 'produce and ship '
      + '([Carbon Trust]'
      + '(https://www.carbontrust.com/)). '
      + 'Libraries maximise the useful '
      + 'life of each item by sharing it '
      + 'among hundreds of readers. Beyond '
      + 'carbon savings, libraries '
      + 'strengthen communities, promote '
      + 'literacy, and provide free access '
      + 'to knowledge ([UN SDG 4]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)).',
    ja:
      '新品を買う代わりに図書館で本や映画'
      + 'などを借りると1点あたり約**1,000g'
      + 'のCO2**を削減できます。製造、梱包、'
      + '配送を回避するためです。ペーパー'
      + 'バック1冊の製造・配送で約1kgのCO2'
      + 'が発生します（[Carbon Trust]'
      + '(https://www.carbontrust.com/)）。'
      + '図書館は1つの品を何百人もの利用者'
      + 'で共有し有効寿命を最大化します。'
      + 'CO2削減に加えコミュニティの強化、'
      + 'リテラシーの促進、知識への無料'
      + 'アクセスを提供します（[国連SDG 4]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)）。',
    es:
      'Tomar prestado un libro, película u '
      + 'otro medio de la biblioteca en lugar '
      + 'de comprar nuevo ahorra '
      + 'aproximadamente **1.000g de CO2** por '
      + 'artículo de fabricación, empaquetado '
      + 'y envío. Un solo libro de bolsillo '
      + 'genera alrededor de 1kg de CO2 al '
      + 'producirse y enviarse ([Carbon Trust]'
      + '(https://www.carbontrust.com/)). '
      + 'Las bibliotecas maximizan la vida '
      + 'útil de cada artículo compartiéndolo '
      + 'entre cientos de lectores. Además '
      + 'del ahorro de carbono, fortalecen '
      + 'comunidades, promueven la '
      + 'alfabetización y brindan acceso '
      + 'gratuito al conocimiento '
      + '([ODS 4 de la ONU]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)).',
  },

  pick_up_litter: {
    en:
      'Picking up litter prevents plastic '
      + 'and other waste from entering '
      + 'waterways that lead to the ocean. '
      + 'Oceans are the planet\'s largest '
      + 'carbon sink, absorbing about 30% of '
      + 'human CO2 emissions, and plastic '
      + 'pollution threatens this capacity '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Even small cleanup efforts protect '
      + 'local ecosystems and wildlife '
      + '([UN SDG 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)). '
      + 'Visible action also inspires others '
      + 'to care for shared spaces and reduce '
      + 'their own waste.',
    ja:
      'ゴミ拾いはプラスチックやその他の'
      + '廃棄物が海につながる水路に入るのを'
      + '防ぎます。海洋は地球最大の炭素吸収'
      + '源で人為的CO2排出の約30%を吸収して'
      + 'おり、プラスチック汚染はこの能力を'
      + '脅かしています'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '小さなクリーンアップ活動でも地域の'
      + '生態系と野生生物を保護します'
      + '（[国連SDG 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)）。'
      + '目に見える行動は他の人にも共有空間'
      + 'を大切にし、ゴミを減らすよう促し'
      + 'ます。',
    es:
      'Recoger basura evita que plásticos '
      + 'y otros residuos lleguen a las vías '
      + 'fluviales que desembocan en el '
      + 'océano. Los océanos son el mayor '
      + 'sumidero de carbono del planeta, '
      + 'absorbiendo el 30% del CO2 humano, '
      + 'y la contaminación plástica amenaza '
      + 'esta capacidad '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Incluso pequeños esfuerzos protegen '
      + 'los ecosistemas locales '
      + '([ONU ODS 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)). '
      + 'La acción visible inspira a otros '
      + 'a cuidar los espacios compartidos.',
  },

  // ---------------------------------------------------
  // ADVOCACY (8 actions)
  // ---------------------------------------------------
  sign_petition: {
    en:
      'Signing an environmental petition '
      + 'adds your voice to collective '
      + 'demands for systemic change. Policy '
      + 'reform has orders of magnitude more '
      + 'impact on emissions than any single '
      + 'individual action '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Petitions that reach critical mass '
      + 'have driven landmark legislation '
      + 'like the EU Green Deal '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Your signature costs nothing but '
      + 'contributes to the democratic '
      + 'pressure that shapes climate policy.',
    ja:
      '環境署名に参加することで、体制的な'
      + '変革を求める集団的な声にあなたの声'
      + 'を加えます。政策改革は個人の行動'
      + 'よりも桁違いに大きな排出削減効果が'
      + 'あります'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + 'クリティカルマスに達した署名はEU'
      + 'グリーンディールなどの画期的な法律'
      + 'を推進してきました'
      + '（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + 'あなたの署名は無料ですが、気候政策'
      + 'を形作る民主的な圧力に貢献します。',
    es:
      'Firmar una petición ambiental suma '
      + 'tu voz a las demandas colectivas de '
      + 'cambio sistémico. La reforma '
      + 'política tiene ordenes de magnitud '
      + 'más impacto en las emisiones que '
      + 'cualquier acción individual '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Las peticiones que alcanzan masa '
      + 'crítica han impulsado leyes como '
      + 'el Pacto Verde de la UE '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Tu firma no cuesta nada pero '
      + 'contribuye a la presión democrática '
      + 'que moldea la política climática.',
  },

  contact_representative: {
    en:
      'Contacting your elected '
      + 'representative is the most effective '
      + 'form of political advocacy for '
      + 'climate action. Representatives '
      + 'track constituent contacts and '
      + 'prioritize issues accordingly '
      + '([UN SDG 16]'
      + '(https://sdgs.un.org/goals'
      + '/goal16)). '
      + 'A single thoughtful message can '
      + 'influence votes on critical '
      + 'environmental legislation '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Systemic policy change remains the '
      + 'most powerful lever for reducing '
      + 'emissions at scale.',
    ja:
      '選出された代表者に連絡することは、'
      + '気候行動のための最も効果的な政治的'
      + '提唱形態です。代表者は有権者からの'
      + '連絡を記録し、それに応じて問題の'
      + '優先順位を決定します'
      + '（[国連SDG 16]'
      + '(https://sdgs.un.org/goals'
      + '/goal16)）。'
      + '1つの思慮深いメッセージが重要な環境'
      + '法案の投票に影響を与えることができ'
      + 'ます（[IPCC]'
      + '(https://www.ipcc.ch/)）。'
      + '体制的な政策変更は、排出削減の最も'
      + '強力な手段であり続けています。',
    es:
      'Contactar a tu representante electo '
      + 'es la forma más efectiva de '
      + 'incidencia política por la acción '
      + 'climática. Los representantes '
      + 'registran los contactos de sus '
      + 'electores y priorizan los temas '
      + 'en consecuencia '
      + '([ONU ODS 16]'
      + '(https://sdgs.un.org/goals'
      + '/goal16)). '
      + 'Un solo mensaje reflexivo puede '
      + 'influir en votos sobre legislación '
      + 'ambiental crítica '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'El cambio político sistémico sigue '
      + 'siendo la palanca más poderosa para '
      + 'reducir emisiones a escala.',
  },

  share_eco_content: {
    en:
      'Sharing eco-friendly content on '
      + 'social media amplifies environmental '
      + 'awareness to your entire network. '
      + 'Visible sustainable behavior on '
      + 'social platforms influences peers '
      + 'and normalizes green choices '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Studies show that social influence '
      + 'is a top driver of behavior change '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'A single shared post can reach '
      + 'hundreds and inspire real-world '
      + 'action beyond the screen.',
    ja:
      'エコフレンドリーなコンテンツをSNSで'
      + '共有することで、ネットワーク全体に'
      + '環境意識を拡大します。ソーシャル'
      + 'プラットフォーム上の目に見える持続'
      + '可能な行動は仲間に影響を与え、'
      + 'グリーンな選択を普通にします'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '研究により、社会的影響は行動変容の'
      + '最大の推進力の一つであることが示さ'
      + 'れています（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + '1つの投稿が何百人にも届き、画面の'
      + '向こうの現実の行動を促します。',
    es:
      'Compartir contenido ecológico en '
      + 'redes sociales amplifica la '
      + 'conciencia ambiental a toda tu red. '
      + 'El comportamiento sostenible visible '
      + 'en plataformas sociales influye en '
      + 'los compañeros y normaliza las '
      + 'elecciones verdes '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Los estudios muestran que la '
      + 'influencia social es un motor clave '
      + 'del cambio de comportamiento '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Una publicación puede llegar a '
      + 'cientos e inspirar acción real.',
  },

  attend_climate_event: {
    en:
      'Attending a climate rally, march, or '
      + 'event adds to the mass mobilization '
      + 'that drives policy change. The Paris '
      + 'Agreement was shaped significantly '
      + 'by sustained public pressure '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Large turnout at climate events '
      + 'signals to lawmakers that voters '
      + 'prioritize environmental action '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Being physically present strengthens '
      + 'solidarity and amplifies the '
      + 'collective voice for change.',
    ja:
      '気候集会やイベントに参加することで、'
      + '政策変更を推進する大衆動員に加わり'
      + 'ます。パリ協定は持続的な市民の圧力'
      + 'によって大きく形作られました'
      + '（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + '気候イベントへの大規模な参加は、'
      + '有権者が環境行動を優先することを'
      + '立法者に示すシグナルです'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '物理的に存在することで連帯が強化'
      + 'され、変革のための集団的な声が'
      + '増幅されます。',
    es:
      'Asistir a una marcha o evento '
      + 'climático se suma a la movilización '
      + 'masiva que impulsa cambios '
      + 'políticos. El Acuerdo de París fue '
      + 'moldeado significativamente por la '
      + 'presión pública sostenida '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'La gran asistencia a eventos '
      + 'climáticos indica a los legisladores '
      + 'que los votantes priorizan la acción '
      + 'ambiental '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Estar presente fortalece la '
      + 'solidaridad y amplifica la voz '
      + 'colectiva por el cambio.',
  },

  support_green_policy: {
    en:
      'Supporting renewable energy and '
      + 'green policy initiatives could '
      + 'eliminate gigatons of CO2 emissions '
      + 'annually at the systemic level. '
      + 'Policy frameworks like carbon '
      + 'pricing and clean energy standards '
      + 'are the most scalable tools for '
      + 'decarbonization '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Public support gives lawmakers the '
      + 'mandate to pass ambitious climate '
      + 'legislation ([UN SDG 7]'
      + '(https://sdgs.un.org/goals'
      + '/goal7)). '
      + 'Voicing support for green policy is '
      + 'one of the highest-leverage actions '
      + 'any citizen can take.',
    ja:
      '再生可能エネルギーやグリーン政策の'
      + '取り組みを支援することで、体制的'
      + 'レベルで年間ギガトン単位のCO2排出を'
      + '削減できる可能性があります。炭素'
      + '価格付けやクリーンエネルギー基準'
      + 'などの政策枠組みは脱炭素化の最も'
      + '拡張性のあるツールです'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '市民の支持は立法者に野心的な気候'
      + '法案を可決する権限を与えます'
      + '（[国連SDG 7]'
      + '(https://sdgs.un.org/goals'
      + '/goal7)）。'
      + 'グリーン政策への支持表明は、市民が'
      + 'できる最も影響力の大きい行動の一つ'
      + 'です。',
    es:
      'Apoyar las políticas de energía '
      + 'renovable e iniciativas verdes '
      + 'podría eliminar gigatoneladas de '
      + 'emisiones de CO2 anualmente a nivel '
      + 'sistémico. Marcos políticos como la '
      + 'fijación de precios del carbono y '
      + 'los estándares de energía limpia '
      + 'son las '
      + 'herramientas más escalables para la '
      + 'descarbonización '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'El apoyo público da a los '
      + 'legisladores el mandato para aprobar '
      + 'leyes climáticas ambiciosas '
      + '([ONU ODS 7]'
      + '(https://sdgs.un.org/goals'
      + '/goal7)). '
      + 'Expresar apoyo a la política verde '
      + 'es una de las acciones de mayor '
      + 'impacto que un ciudadano puede '
      + 'tomar.',
  },

  write_eco_review: {
    en:
      'Writing a review that highlights a '
      + 'company\'s sustainability practices '
      + 'influences other consumers and '
      + 'rewards eco-conscious businesses. '
      + 'Consumer feedback drives market '
      + 'transformation by making green '
      + 'performance visible to buyers '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Positive reviews for sustainable '
      + 'products create a feedback loop '
      + 'that incentivizes better practices '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Your words help others make informed '
      + 'and planet-friendly choices.',
    ja:
      '企業のサステナビリティ実践を強調'
      + 'するレビューを書くことで、他の消費'
      + '者に影響を与え、エコ意識の高い企業'
      + 'に報いることができます。消費者の'
      + 'フィードバックは、グリーンな実績を'
      + '購入者に見えるようにすることで市場'
      + '変革を推進します（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。'
      + '持続可能な製品への肯定的なレビューは'
      + 'より良い慣行を促すフィードバック'
      + 'ループを作ります'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + 'あなたの言葉が他の人の情報に基づいた'
      + '環境に優しい選択を助けます。',
    es:
      'Escribir una reseña que destaque las '
      + 'prácticas de sostenibilidad de una '
      + 'empresa influye en otros consumidores'
      + ' y recompensa a los negocios '
      + 'ecoconscientes. La retroalimentación'
      + ' del consumidor impulsa la '
      + 'transformación del mercado '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Las reseñas positivas de productos '
      + 'sostenibles crean un ciclo de '
      + 'retroalimentación que incentiva '
      + 'mejores prácticas '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Tus palabras ayudan a otros a tomar '
      + 'decisiones informadas y ecológicas.',
  },

  attend_eco_meeting: {
    en:
      'Attending an eco-group meeting or '
      + 'environmental workshop amplifies '
      + 'your impact by connecting you with '
      + 'like-minded advocates and '
      + 'multiplying your knowledge. '
      + 'Research shows that collective '
      + 'action and community engagement '
      + 'are key drivers of systemic '
      + 'environmental change '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Regular participation keeps you '
      + 'informed about local environmental '
      + 'issues and policy developments '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Each meeting is an opportunity to '
      + 'learn, share ideas, and coordinate '
      + 'community-level action.',
    ja:
      'エコグループの集まりや環境ワーク'
      + 'ショップに参加すると、志を同じく'
      + 'する仲間とつながり知識を広げること'
      + 'で、あなたの影響力が高まります。'
      + '研究によると、集団行動とコミュニティ'
      + '参加は体制的な環境変化の重要な推進力'
      + 'です'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '定期的な参加は地域の環境問題や政策'
      + '動向について最新情報を得る助けになり'
      + 'ます（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + '各回の集まりが学び、アイデアの共有、'
      + '地域レベルの行動を調整する機会'
      + 'です。',
    es:
      'Asistir a una reunión de un grupo '
      + 'ecológico o taller ambiental '
      + 'amplifica tu impacto al conectarte '
      + 'con personas afines y multiplicar '
      + 'tu conocimiento. Las investigaciones '
      + 'muestran que la acción colectiva y '
      + 'la participación comunitaria son '
      + 'motores clave del cambio ambiental '
      + 'sistémico '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'La participación regular te mantiene '
      + 'informado sobre problemas ambientales '
      + 'locales y desarrollos políticos '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Cada reunión es una oportunidad '
      + 'para aprender, compartir ideas y '
      + 'coordinar acciones comunitarias.',
  },

  request_green_option: {
    en:
      'Requesting a green option from a '
      + 'business signals consumer demand '
      + 'for sustainable alternatives. When '
      + 'companies hear directly from '
      + 'customers, they are more likely to '
      + 'invest in eco-friendly options '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'This demand-side pressure has driven '
      + 'companies to adopt sustainable '
      + 'packaging, plant-based menus, and '
      + 'renewable energy '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Every request plants a seed that '
      + 'can grow into lasting corporate '
      + 'change.',
    ja:
      '企業にグリーンオプションを要求する'
      + 'ことは、持続可能な代替品への消費者'
      + '需要を示すシグナルです。企業は顧客'
      + 'から直接要望を聞くと、エコフレンド'
      + 'リーな選択肢に投資する可能性が高く'
      + 'なります（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。'
      + 'この需要側の圧力により、企業は持続'
      + '可能な包装、植物由来メニュー、再生'
      + '可能エネルギーを採用してきました'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + 'すべての要求が、持続的な企業変革に'
      + '成長する種を蒔きます。',
    es:
      'Solicitar una opción verde a una '
      + 'empresa indica la demanda del '
      + 'consumidor por alternativas '
      + 'sostenibles. Cuando las empresas '
      + 'escuchan directamente de los '
      + 'clientes, es más probable que '
      + 'inviertan en opciones ecológicas '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Esta presión del lado de la demanda '
      + 'ha impulsado embalajes sostenibles, '
      + 'menús vegetales y energía renovable '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Cada solicitud planta una semilla '
      + 'que puede convertirse en un cambio '
      + 'corporativo duradero.',
  },

  // ---------------------------------------------------
  // SDG-TARGETED (5 actions)
  // ---------------------------------------------------
  buy_fair_trade: {
    en:
      'Fair Trade certification ensures '
      + 'producers in developing countries '
      + 'receive a guaranteed minimum price '
      + 'above market rates. Research from '
      + 'Cote d\'Ivoire shows Fair Trade '
      + 'increased household consumption by '
      + '**13.6%** for poor farmers '
      + '([Fairtrade Impact]'
      + '(https://www.fairtrade.net/en'
      + '/why-fairtrade/impact)). '
      + 'Since 2016, Fair Trade farmers have '
      + 'earned over **$1 billion** in '
      + 'premiums for community development '
      + '([Fairtrade Smallholders]'
      + '(https://www.fairtrade.net/us-en'
      + '/why-fairtrade/why-we-do-it'
      + '/smallholder-farmers.html)). '
      + 'Choosing Fair Trade also supports '
      + 'climate-resilient farming practices '
      + 'like agroforestry and crop rotation.',
    ja:
      'フェアトレード認証は、途上国の生産者が'
      + '市場価格を上回る最低保証価格を受け取る'
      + 'ことを保証します。コートジボワールの'
      + '研究では、フェアトレードにより貧困層の'
      + '家計消費が**13.6%増加**しました'
      + '（[フェアトレード影響]'
      + '(https://www.fairtrade.net/en'
      + '/why-fairtrade/impact)）。'
      + '2016年以降、フェアトレード農家は'
      + 'コミュニティ開発のために**10億ドル以上'
      + '**のプレミアムを獲得しています'
      + '（[フェアトレード小規模農家]'
      + '(https://www.fairtrade.net/us-en'
      + '/why-fairtrade/why-we-do-it'
      + '/smallholder-farmers.html)）。'
      + 'フェアトレードは農林業や輪作など気候に'
      + '強い農業も支援しています。',
    es:
      'La certificación de comercio justo '
      + 'garantiza que los productores de '
      + 'países en desarrollo reciban un '
      + 'precio mínimo garantizado. Una '
      + 'investigación en Costa de Marfil '
      + 'muestra que el comercio justo '
      + 'aumentó el consumo de los hogares '
      + 'pobres un **13,6%** '
      + '([Impacto Fairtrade]'
      + '(https://www.fairtrade.net/en'
      + '/why-fairtrade/impact)). '
      + 'Desde 2016, los agricultores han '
      + 'ganado más de **$1,000 millones** en '
      + 'primas para desarrollo comunitario '
      + '([Fairtrade Pequeños Productores]'
      + '(https://www.fairtrade.net/us-en'
      + '/why-fairtrade/why-we-do-it'
      + '/smallholder-farmers.html)). '
      + 'Elegir comercio justo también apoya '
      + 'prácticas agrícolas resilientes al '
      + 'clima.',
  },

  fund_micro_loan: {
    en:
      'Micro-lending channels capital '
      + 'directly to entrepreneurs excluded '
      + 'from traditional banking. Kiva '
      + 'reports a **96.3% repayment rate** '
      + 'across $1.68 billion in loans to '
      + '4.1 million borrowers in 77 '
      + 'countries, with **89% reporting '
      + 'improved quality of life** '
      + '([Kiva Impact]'
      + '(https://www.kiva.org/impact)). '
      + 'Because loans are repaid, a single '
      + '$25 contribution can fund multiple '
      + 'entrepreneurs over time. Randomized '
      + 'trials show microfinance can '
      + 'increase incomes by up to 46% and '
      + 'decrease poverty by 17%.',
    ja:
      'マイクロレンディングは、従来の銀行から'
      + '排除された起業家に直接資本を届けます。'
      + 'Kivaは77カ国の410万人の借り手に'
      + '16.8億ドルの融資で**96.3%の返済率**'
      + 'を報告しており、**89%が生活の質の'
      + '向上**を報告しています'
      + '（[Kivaインパクト]'
      + '(https://www.kiva.org/impact)）。'
      + '融資は返済されるため、1回の25ドルの'
      + '出資で複数の起業家を支援できます。'
      + '無作為化試験では、マイクロファイナンス'
      + 'が所得を最大46%増加させ、貧困を17%'
      + '削減できることが示されています。',
    es:
      'Los micropréstamos canalizan capital '
      + 'directamente a emprendedores '
      + 'excluidos de la banca tradicional. '
      + 'Kiva reporta una **tasa de '
      + 'devolución del 96,3%** en $1.680 '
      + 'millones prestados a 4,1 millones '
      + 'de prestatarios en 77 países, con '
      + '**89% reportando mejor calidad de '
      + 'vida** ([Impacto Kiva]'
      + '(https://www.kiva.org/impact)). '
      + 'Como los préstamos se devuelven, una '
      + 'contribución de $25 puede financiar '
      + 'múltiples emprendedores. Ensayos '
      + 'aleatorizados muestran que las '
      + 'microfinanzas pueden aumentar los '
      + 'ingresos hasta un 46% y reducir la '
      + 'pobreza en un 17%.',
  },

  support_women_owned_business: {
    en:
      'Women-owned businesses make up 39% '
      + 'of all US businesses but receive '
      + 'only **1% of corporate procurement '
      + 'spending** ([UN Women]'
      + '(https://www.unwomen.org/en/what-we'
      + '-do/economic-empowerment)). '
      + 'Women reinvest up to **90% of '
      + 'income** back into their families '
      + 'and communities, compared to 30-40% '
      + 'for men. Organizations with more '
      + 'women managers reduce carbon '
      + 'emissions by approximately **5%** '
      + '([WEF 2022](https://www.weforum.org'
      + '/stories/2022/06/women-organizations'
      + '-reduce-greenhouse-gas-emissions/)). '
      + 'Supporting women-owned businesses '
      + 'drives both gender equality and '
      + 'climate progress.',
    ja:
      '女性が経営する企業はアメリカの全企業の'
      + '39%を占めますが、企業調達の**わずか'
      + '1%**しか受けていません（[UN Women]'
      + '(https://www.unwomen.org/en/what-we'
      + '-do/economic-empowerment)）。'
      + '女性は収入の最大**90%**を家族や'
      + 'コミュニティに再投資します。男性の'
      + '30〜40%と比較すると大きな差です。'
      + '女性管理職'
      + 'が多い組織は炭素排出を約**5%削減**'
      + 'します（[WEF 2022]'
      + '(https://www.weforum.org/stories'
      + '/2022/06/women-organizations-reduce'
      + '-greenhouse-gas-emissions/)）。'
      + '女性経営のビジネスを支援することは、'
      + 'ジェンダー平等と気候対策の両方を'
      + '推進します。',
    es:
      'Los negocios de mujeres representan '
      + 'el 39% de las empresas en EEUU pero '
      + 'reciben solo el **1% del gasto de '
      + 'adquisiciones corporativas** '
      + '([ONU Mujeres](https://www.unwomen'
      + '.org/en/what-we-do/economic'
      + '-empowerment)). '
      + 'Las mujeres reinvierten hasta el '
      + '**90% de sus ingresos** en sus '
      + 'familias y comunidades. Las '
      + 'organizaciones con más mujeres '
      + 'gerentes reducen emisiones de '
      + 'carbono aproximadamente un **5%** '
      + '([WEF 2022](https://www.weforum.org'
      + '/stories/2022/06/women-organizations'
      + '-reduce-greenhouse-gas-emissions/)). '
      + 'Apoyar negocios de mujeres impulsa '
      + 'tanto la igualdad de género como el '
      + 'progreso climático.',
  },

  take_on_household_task: {
    en:
      'Taking on a specific household '
      + 'task like cooking, cleaning, or '
      + 'childcare today supports equitable '
      + 'division of domestic work, a core '
      + 'target of UN SDG 5 on gender '
      + 'equality. Unpaid care and domestic '
      + 'work disproportionately falls on '
      + 'women, limiting their economic '
      + 'participation and well-being '
      + '([UN Women]'
      + '(https://www.unwomen.org/)). '
      + 'Logging this action builds '
      + 'awareness of daily contributions '
      + 'and encourages more balanced '
      + 'sharing within households '
      + '([UN SDG 5]'
      + '(https://sdgs.un.org/goals'
      + '/goal5)). '
      + 'Equity at home is a foundation '
      + 'for equity everywhere.',
    ja:
      '料理や掃除、育児などの家事を'
      + '引き受けることは、家庭内の公平な'
      + '分担を支える行動であり、ジェンダー'
      + '平等に関する国連SDG 5の重要な'
      + 'ターゲットです。無償のケア・家事'
      + '労働は女性に不均衡にのしかかり、'
      + '経済参加と幸福を制限しています'
      + '（[UN Women]'
      + '(https://www.unwomen.org/)）。'
      + 'この行動を記録することで日々の'
      + '貢献への意識が高まり、家庭内での'
      + 'よりバランスの取れた分担を促します'
      + '（[国連SDG 5]'
      + '(https://sdgs.un.org/goals'
      + '/goal5)）。'
      + '家庭での公平は、あらゆる場所での'
      + '公平の基盤です。',
    es:
      'Asumir una tarea doméstica '
      + 'específica como cocinar, limpiar o '
      + 'cuidar niños hoy apoya la división '
      + 'equitativa del trabajo doméstico, '
      + 'un objetivo central del ODS 5 de la '
      + 'ONU sobre igualdad de género. El '
      + 'trabajo de cuidado y doméstico no '
      + 'remunerado recae de forma '
      + 'desproporcionada en las mujeres, '
      + 'limitando su participación económica '
      + 'y bienestar '
      + '([ONU Mujeres]'
      + '(https://www.unwomen.org/)). '
      + 'Registrar esta acción crea '
      + 'conciencia sobre las contribuciones '
      + 'diarias y fomenta un reparto más '
      + 'equilibrado en los hogares '
      + '([ONU ODS 5]'
      + '(https://sdgs.un.org/goals'
      + '/goal5)). '
      + 'La equidad en el hogar es la base '
      + 'de la equidad en todas partes.',
  },

  support_community_business: {
    en:
      'Directing purchases to minority-owned '
      + 'and underrepresented community '
      + 'businesses builds economic equity. '
      + 'If minority businesses reached '
      + 'population parity, **757,000 new '
      + 'businesses** could emerge with 6.3 '
      + 'million jobs and $824 billion in '
      + 'revenue ([Brookings]'
      + '(https://www.brookings.edu/articles'
      + '/reaping-the-unrealized-gains-of'
      + '-black-businesses/)). '
      + 'Minority-owned businesses already '
      + 'generate nearly **$2 trillion in '
      + 'annual revenue** ([SCORE]'
      + '(https://www.score.org)). '
      + 'Conscious consumer choice is one of '
      + 'the most direct individual levers '
      + 'for reducing economic inequality.',
    ja:
      'マイノリティや地域のビジネスへの購入は'
      + '経済的公平性を築きます。マイノリティ'
      + 'ビジネスが人口比率に達すれば、'
      + '**757,000の新規事業**が生まれ、'
      + '630万の雇用と8,240億ドルの収益が'
      + '生まれる可能性があります'
      + '（[ブルッキングス]'
      + '(https://www.brookings.edu/articles'
      + '/reaping-the-unrealized-gains-of'
      + '-black-businesses/)）。'
      + 'マイノリティ経営のビジネスは既に年間'
      + '約**2兆ドルの収益**を生み出しています'
      + '（[SCORE](https://www.score.org)）。'
      + '意識的な消費は、経済的不平等を縮小する'
      + '最も直接的な個人の手段の一つです。',
    es:
      'Dirigir compras a negocios de '
      + 'minorías y comunidades '
      + 'subrepresentadas construye equidad '
      + 'económica. Si los negocios de '
      + 'minorías alcanzaran la paridad '
      + 'poblacional, podrían surgir '
      + '**757.000 nuevos negocios** con 6,3 '
      + 'millones de empleos y $824 mil '
      + 'millones en ingresos ([Brookings]'
      + '(https://www.brookings.edu/articles'
      + '/reaping-the-unrealized-gains-of'
      + '-black-businesses/)). '
      + 'Los negocios de minorías ya generan '
      + 'casi **$2 billones en ingresos '
      + 'anuales** '
      + '([SCORE](https://www.score.org)). '
      + 'La elección consciente del '
      + 'consumidor es una de las palancas '
      + 'individuales más directas para '
      + 'reducir la desigualdad económica.',
  },

  citizen_science_project: {
    en:
      'Platforms like iNaturalist have '
      + 'gathered over **250 million '
      + 'observations** of wildlife worldwide, '
      + 'contributing to more than **5,000 '
      + 'peer-reviewed scientific papers** '
      + '([BioScience]'
      + '(https://academic.oup.com/bioscience'
      + '/article/75/11/953/8185761)). '
      + 'The 2025 City Nature Challenge '
      + 'mobilized **102,945 participants** '
      + 'across 669 cities in 62 countries, '
      + 'recording 3.3 million observations '
      + 'of over 73,000 species '
      + '([City Nature Challenge]'
      + '(https://www.citynaturechallenge'
      + '.org/)). '
      + 'A study in Nature Sustainability '
      + 'found that citizen scientists can '
      + 'help monitor **over half** of the '
      + '365 indicators in the UN Global '
      + 'Biodiversity Framework '
      + '([Nature Sustainability]'
      + '(https://www.nature.com/articles'
      + '/s41893-024-01447-y)). '
      + 'Every observation you log helps '
      + 'researchers track species, detect '
      + 'ecological change, and inform '
      + 'conservation policy.',
    ja:
      'iNaturalistなどのプラットフォームは'
      + '世界中で**2億5,000万件以上の生物'
      + '観察**を集め、**5,000本以上の査読'
      + '付き論文**に貢献しています'
      + '（[BioScience]'
      + '(https://academic.oup.com/bioscience'
      + '/article/75/11/953/8185761)）。'
      + '2025年のシティ・ネイチャー・'
      + 'チャレンジでは、62カ国669都市から'
      + '**102,945人**が参加し、73,000種'
      + '以上の330万件の観察が記録されました'
      + '（[City Nature Challenge]'
      + '(https://www.citynaturechallenge'
      + '.org/)）。'
      + 'Nature Sustainability誌の研究では、'
      + '市民科学者が国連生物多様性枠組みの'
      + '365指標の**半数以上**のモニタリング'
      + 'に貢献できることが示されています'
      + '（[Nature Sustainability]'
      + '(https://www.nature.com/articles'
      + '/s41893-024-01447-y)）。'
      + 'あなたの一つの観察が、種の追跡や'
      + '生態系変化の検出、保全政策の策定に'
      + '役立ちます。',
    es:
      'Plataformas como iNaturalist han '
      + 'reunido más de **250 millones de '
      + 'observaciones** de vida silvestre en '
      + 'todo el mundo, contribuyendo a más '
      + 'de **5.000 artículos científicos** '
      + 'revisados por pares '
      + '([BioScience]'
      + '(https://academic.oup.com/bioscience'
      + '/article/75/11/953/8185761)). '
      + 'El City Nature Challenge 2025 '
      + 'movilizó a **102.945 participantes** '
      + 'en 669 ciudades de 62 países, '
      + 'registrando 3,3 millones de '
      + 'observaciones de más de 73.000 '
      + 'especies ([City Nature Challenge]'
      + '(https://www.citynaturechallenge'
      + '.org/)). '
      + 'Un estudio en Nature Sustainability '
      + 'demostró que los ciudadanos pueden '
      + 'ayudar a monitorear **más de la '
      + 'mitad** de los 365 indicadores del '
      + 'Marco Global de Biodiversidad de la '
      + 'ONU ([Nature Sustainability]'
      + '(https://www.nature.com/articles'
      + '/s41893-024-01447-y)). '
      + 'Cada observación que registras ayuda '
      + 'a rastrear especies, detectar '
      + 'cambios ecológicos e informar '
      + 'políticas de conservación.',
  },

  volunteer_nature_walk: {
    en:
      'Guided nature walks connect '
      + 'communities with local ecosystems '
      + 'and inspire lasting environmental '
      + 'stewardship. A meta-analysis of '
      + '**169 studies** across 43 countries '
      + 'found that environmental education '
      + 'nearly doubled participants\' '
      + 'ecological knowledge and '
      + 'significantly increased pro-'
      + 'environmental behavior '
      + '([Journal of Environmental '
      + 'Psychology](https://doi.org/10.1016'
      + '/j.jenvp.2022.101782)). '
      + 'Organizations like The Nature '
      + 'Conservancy and the National Park '
      + 'Service rely on volunteers to run '
      + 'these walks -- the NPS alone engages '
      + 'nearly **300,000 volunteers** for '
      + 'over 6.5 million hours of service '
      + 'each year '
      + '([NPS](https://www.nps.gov/subjects'
      + '/volunteer/index.htm)). '
      + 'By volunteering, you help others '
      + 'build the emotional connection to '
      + 'nature that research shows is the '
      + 'strongest driver of lifelong '
      + 'conservation habits '
      + '([NEEF](https://www.neefusa.org'
      + '/what-we-do/k-12-education'
      + '/benefits-environmental-education)).',
    ja:
      'ガイド付き自然散策は地域社会と地元の'
      + '生態系をつなぎ、持続的な環境保全意識'
      + 'を育みます。43カ国**169件の研究**を'
      + '分析したメタアナリシスでは、環境教育が'
      + '参加者の生態学的知識をほぼ倍増させ、'
      + '環境配慮行動を有意に向上させることが'
      + '判明しました'
      + '（[Journal of Environmental '
      + 'Psychology](https://doi.org/10.1016'
      + '/j.jenvp.2022.101782)）。'
      + '米国国立公園局だけでも毎年約**30万人'
      + 'のボランティア**が650万時間以上の'
      + 'サービスを提供しています'
      + '（[NPS](https://www.nps.gov/subjects'
      + '/volunteer/index.htm)）。'
      + '自然散策のボランティアに参加することで、'
      + '生涯にわたる保全習慣の最も強い原動力と'
      + 'なる自然への感情的なつながりを他者に'
      + '築く手助けができます'
      + '（[NEEF](https://www.neefusa.org'
      + '/what-we-do/k-12-education'
      + '/benefits-environmental-education)）。',
    es:
      'Las caminatas guiadas por la '
      + 'naturaleza conectan a las '
      + 'comunidades con los ecosistemas '
      + 'locales e inspiran una conciencia '
      + 'ambiental duradera. Un metaanálisis '
      + 'de **169 estudios** en 43 países '
      + 'demostró que la educación ambiental '
      + 'casi duplicó el conocimiento '
      + 'ecológico de los participantes y '
      + 'aumentó significativamente su '
      + 'comportamiento proambiental '
      + '([Journal of Environmental '
      + 'Psychology](https://doi.org/10.1016'
      + '/j.jenvp.2022.101782)). '
      + 'Solo el Servicio de Parques '
      + 'Nacionales de EE.UU. moviliza casi '
      + '**300.000 voluntarios** que aportan '
      + 'más de 6,5 millones de horas de '
      + 'servicio al año '
      + '([NPS](https://www.nps.gov/subjects'
      + '/volunteer/index.htm)). '
      + 'Al ser voluntario en una caminata '
      + 'por la naturaleza, ayudas a otros '
      + 'a construir la conexión emocional '
      + 'con el entorno que, según la '
      + 'investigación, es el motor más '
      + 'fuerte de hábitos de conservación '
      + 'de por vida '
      + '([NEEF](https://www.neefusa.org'
      + '/what-we-do/k-12-education'
      + '/benefits-environmental-education)).',
  },

  donate_women_climate_org: {
    en:
      'Only **0.2% of all foundation '
      + 'funding** goes to the intersection '
      + 'of women and the environment, '
      + 'despite women reinvesting up to '
      + '**90% of their income** back into '
      + 'families and communities '
      + '([Global Greengrants Fund]'
      + '(https://www.bothends.org/en'
      + '/Whats-new/News/Only-0-2-of-all'
      + '-foundation-funding-for-women'
      + '-environment/)). '
      + 'Women hold only **35% of national '
      + 'delegate seats** at UN climate '
      + 'negotiations, yet a 2024 study '
      + 'across 146 countries found that '
      + 'gender equality explains **86% of '
      + 'the variation** in climate '
      + 'adaptation readiness '
      + '([BMC Public Health]'
      + '(https://bmcpublichealth'
      + '.biomedcentral.com/articles'
      + '/10.1186/s12889-024-18880-5)). '
      + 'Organizations like Women\'s Earth '
      + 'Alliance have trained over '
      + '**52,000 women** in 31 countries '
      + 'to lead environmental justice '
      + 'projects since 2006 '
      + '([WEA](https://womensearthalliance'
      + '.org/)). '
      + 'Your donation directly empowers '
      + 'women-led climate solutions at the '
      + 'grassroots level, where they '
      + 'deliver outsized impact.',
    ja:
      '女性と環境の交差領域に向けられる助成金'
      + 'は全体のわずか**0.2%**に過ぎません。'
      + 'それにもかかわらず、女性は収入の最大'
      + '**90%**を家族やコミュニティに還元して'
      + 'います'
      + '（[Global Greengrants Fund]'
      + '(https://www.bothends.org/en'
      + '/Whats-new/News/Only-0-2-of-all'
      + '-foundation-funding-for-women'
      + '-environment/)）。'
      + '国連気候交渉における女性の代表は'
      + '**わずか35%**ですが、2024年の146カ国'
      + 'を対象とした研究では、ジェンダー平等が'
      + '気候適応力の差異の**86%を説明する**'
      + 'ことが判明しました'
      + '（[BMC Public Health]'
      + '(https://bmcpublichealth'
      + '.biomedcentral.com/articles'
      + '/10.1186/s12889-024-18880-5)）。'
      + 'Women\'s Earth Allianceは2006年以来、'
      + '31カ国で**52,000人以上の女性**に'
      + '環境正義プロジェクトの研修を実施して'
      + 'います'
      + '（[WEA](https://womensearthalliance'
      + '.org/)）。'
      + 'あなたの寄付は、最も大きなインパクトを'
      + '生む草の根レベルの女性主導の気候変動'
      + '対策を直接支援します。',
    es:
      'Solo el **0,2% de toda la '
      + 'financiación de fundaciones** se '
      + 'destina a la intersección entre '
      + 'mujeres y medio ambiente, a pesar '
      + 'de que las mujeres reinvierten '
      + 'hasta el **90% de sus ingresos** '
      + 'en sus familias y comunidades '
      + '([Global Greengrants Fund]'
      + '(https://www.bothends.org/en'
      + '/Whats-new/News/Only-0-2-of-all'
      + '-foundation-funding-for-women'
      + '-environment/)). '
      + 'Las mujeres ocupan solo el **35% '
      + 'de los puestos de delegadas** en '
      + 'las negociaciones climáticas de la '
      + 'ONU, pero un estudio de 2024 en '
      + '146 países reveló que la igualdad '
      + 'de género explica el **86% de la '
      + 'variación** en la capacidad de '
      + 'adaptación climática '
      + '([BMC Public Health]'
      + '(https://bmcpublichealth'
      + '.biomedcentral.com/articles'
      + '/10.1186/s12889-024-18880-5)). '
      + 'Organizaciones como Women\'s Earth '
      + 'Alliance han capacitado a más de '
      + '**52.000 mujeres** en 31 países '
      + 'para liderar proyectos de justicia '
      + 'ambiental desde 2006 '
      + '([WEA](https://womensearthalliance'
      + '.org/)). '
      + 'Tu donación impulsa directamente '
      + 'soluciones climáticas lideradas '
      + 'por mujeres a nivel comunitario, '
      + 'donde generan el mayor impacto.',
  },
};

module.exports = descriptions;
