/**
 * Long descriptions for eco-actions:
 * ENERGY, WATER categories.
 *
 * Each description is 3-5 sentences with markdown
 * formatting, bold CO2 figures, and source links.
 *
 * This is a partial file merged into the final
 * descriptions module.
 */

const descriptions = {
  // -------------------------------------------------------
  // ENERGY (12 actions)
  // -------------------------------------------------------
  air_dry_clothes: {
    en:
      'Air drying your laundry instead of '
      + 'using a tumble dryer saves roughly '
      + '**1,700g of CO2** per load. A typical '
      + 'dryer consumes about 4.5 kWh per '
      + 'cycle, making it one of the most '
      + 'energy-hungry household appliances '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Over a year of weekly loads, air '
      + 'drying avoids nearly 90 kg of CO2. '
      + 'Clotheslines and drying racks cost '
      + 'nothing to operate and also extend '
      + 'the lifespan of your garments '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '乾燥機の代わりに洗濯物を自然乾燥'
      + 'すると1回あたり約**1,700gのCO2**を'
      + '削減できます。一般的な乾燥機は1回で'
      + '約4.5kWhを消費し、家庭で最も電力を'
      + '使う機器の一つです（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。週1回の洗濯を年間通して'
      + '自然乾燥にすると約90kgのCO2を回避'
      + 'できます。物干しや乾燥ラックは運転'
      + 'コストがゼロで衣類の寿命も延ばします'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Secar la ropa al aire en vez de usar '
      + 'secadora ahorra aproximadamente '
      + '**1.700g de CO2** por carga. Una '
      + 'secadora típica consume unos 4,5 kWh '
      + 'por ciclo, siendo uno de los '
      + 'electrodomésticos de mayor consumo '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'En un año de cargas semanales, el '
      + 'secado al aire evita casi 90 kg de '
      + 'CO2. Los tendederos no tienen costo '
      + 'operativo y además prolongan la vida '
      + 'de la ropa ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)).',
  },

  cold_wash: {
    en:
      'Washing clothes in cold water saves '
      + 'about **600g of CO2** per load '
      + 'because roughly 90% of the energy '
      + 'a washing machine uses goes to '
      + 'heating water ([US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)). '
      + 'Modern detergents are formulated to '
      + 'clean effectively at low temperatures. '
      + 'Cold washing also prevents colour '
      + 'fading and fabric shrinkage, keeping '
      + 'clothes looking new longer '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Over a year of weekly washes, this '
      + 'simple switch avoids over 30 kg '
      + 'of CO2.',
    ja:
      '洗濯を冷水で行うと1回あたり約'
      + '**600gのCO2**を削減できます。'
      + '洗濯機のエネルギーの約90%は水の加熱'
      + 'に使われるためです（[米国エネルギー省]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)）。'
      + '最新の洗剤は低温でも効果的に洗浄'
      + 'できるよう設計されています。冷水洗い'
      + 'は色落ちや縮みも防ぎ衣類を長持ちさせ'
      + 'ます（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。週1回の洗濯で年間30kg'
      + '以上のCO2を回避できます。',
    es:
      'Lavar la ropa con agua fría ahorra '
      + 'unos **600g de CO2** por carga, ya '
      + 'que aproximadamente el 90% de la '
      + 'energía de una lavadora se destina a '
      + 'calentar el agua ([US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)). '
      + 'Los detergentes modernos están '
      + 'formulados para limpiar eficazmente a '
      + 'bajas temperaturas. El lavado en frío '
      + 'también previene la decoloración y '
      + 'el encogimiento ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'En un año de lavados semanales, este '
      + 'simple cambio evita más de 30 kg '
      + 'de CO2.',
  },

  install_led_bulb: {
    en:
      'Installing an LED bulb to replace an '
      + 'incandescent saves roughly '
      + '**28,000g (28kg) of CO2** in its '
      + 'first year alone. LEDs consume 75% '
      + 'less energy than incandescent bulbs '
      + 'and last up to 25 times longer '
      + '([US DOE](https://www.energy.gov'
      + '/energysaver/lighting-choices-save'
      + '-you-money)). Over a bulb\'s '
      + '15,000-hour lifespan the cumulative '
      + 'savings exceed 280kg of CO2 '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). LEDs also produce less '
      + 'heat, reducing summer cooling '
      + 'loads.',
    ja:
      'LED電球を白熱電球の代わりに設置する'
      + 'と初年度だけで約**28,000g（28kg）の'
      + 'CO2**を削減できます。LEDは白熱電球'
      + 'より75%少ないエネルギーで済み寿命は'
      + '最大25倍です（[US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)）。'
      + '15,000時間の寿命を通じて累積の削減量'
      + 'は280kgを超えます（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。LEDは発熱も少なく夏の'
      + '冷房負荷の軽減にもつながります。',
    es:
      'Instalar una bombilla LED en lugar de '
      + 'una incandescente ahorra '
      + 'aproximadamente **28.000g (28kg) de '
      + 'CO2** solo en su primer año. Los LED '
      + 'consumen un 75% menos de energía que '
      + 'las bombillas incandescentes y duran '
      + 'hasta 25 veces más ([US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)). '
      + 'A lo largo de las 15.000 horas de '
      + 'vida útil de la bombilla, el ahorro '
      + 'acumulado supera los 280 kg de CO2 '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). Los LED también generan '
      + 'menos calor, reduciendo la carga de '
      + 'refrigeración en verano.',
  },

  unplug_devices: {
    en:
      'Unplugging idle devices across your '
      + 'home saves about **45g of CO2 per '
      + 'day**. Standby mode draws 1-5 watts '
      + 'per device continuously, and the '
      + 'average home has 20-40 devices on '
      + 'standby ([Lawrence Berkeley National '
      + 'Lab](https://standby.lbl.gov/)). '
      + 'Collectively, standby power accounts '
      + 'for 5-10% of residential electricity '
      + 'use. A smart power strip can '
      + 'automate this by cutting phantom '
      + 'loads when devices are off '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). Small daily habits like '
      + 'this compound into meaningful '
      + 'annual savings.',
    ja:
      '家中の待機機器のプラグを抜くと1日'
      + 'あたり約**45gのCO2**を節約できます。'
      + '待機モードは1台あたり1〜5Wを常時消費'
      + 'し、一般家庭では20〜40台が待機状態'
      + 'です（[Lawrence Berkeley National '
      + 'Lab](https://standby.lbl.gov/)）。'
      + '待機電力は家庭の電力消費全体の5〜10%'
      + 'を占めます。スマート電源タップなら'
      + '機器オフ時の待機電力を自動でカット'
      + 'できます（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。毎日の小さな習慣が'
      + '年間では大きな節約になります。',
    es:
      'Desconectar los dispositivos inactivos '
      + 'de tu hogar ahorra unos **45g de CO2 '
      + 'al día**. El modo de espera consume '
      + '1-5 vatios por dispositivo de forma '
      + 'continua, y un hogar promedio tiene '
      + '20-40 aparatos en espera ([Lawrence '
      + 'Berkeley National Lab]'
      + '(https://standby.lbl.gov/)). En '
      + 'conjunto, la energía en espera '
      + 'representa el 5-10% del consumo '
      + 'eléctrico residencial. Una regleta '
      + 'inteligente puede automatizar esto '
      + 'cortando las cargas fantasma cuando '
      + 'los dispositivos están apagados '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). Pequeños hábitos diarios '
      + 'como este se acumulan en ahorros '
      + 'anuales significativos.',
  },

  turn_off_lights: {
    en:
      'Making a habit of turning off lights '
      + 'in empty rooms saves roughly '
      + '**60g of CO2 per day** across a '
      + 'typical home. Lights left on in '
      + 'unoccupied rooms are among the most '
      + 'common sources of wasted household '
      + 'energy ([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). A household that '
      + 'consistently switches off unused '
      + 'lights can save 5-10% on its '
      + 'electricity bill annually. Pairing '
      + 'this habit with motion sensors or '
      + 'timers maximises the effect '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '空き部屋の照明を消す習慣をつけると'
      + '一般家庭で1日あたり約**60gのCO2**を'
      + '削減できます。誰もいない部屋の'
      + '点けっぱなしは家庭のエネルギー浪費'
      + 'で最も多い原因の一つです（[Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)）。使わない照明'
      + 'をこまめに消す家庭は年間の電気代を'
      + '5〜10%節約できます。人感センサーや'
      + 'タイマーと組み合わせると効果を最大化'
      + 'できます（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。',
    es:
      'Crear el hábito de apagar las luces en '
      + 'habitaciones vacías ahorra '
      + 'aproximadamente **60g de CO2 al día** '
      + 'en un hogar típico. Las luces '
      + 'encendidas en habitaciones desocupadas '
      + 'son una de las fuentes más comunes de '
      + 'desperdicio energético doméstico '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). Un hogar que apaga '
      + 'sistemáticamente las luces que no usa '
      + 'puede ahorrar un 5-10% en su factura '
      + 'eléctrica anual. Combinar este hábito '
      + 'con sensores de movimiento o '
      + 'temporizadores maximiza el efecto '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  lower_thermostat: {
    en:
      'Lowering your heating thermostat by '
      + 'just 1 degree Celsius saves roughly '
      + '**450g of CO2** per day. This single '
      + 'adjustment can reduce heating energy '
      + 'consumption by about 10% '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Over a six-month heating season, '
      + 'that amounts to over 80 kg of CO2 '
      + 'avoided. Wearing an extra layer '
      + 'indoors makes the difference barely '
      + 'noticeable while the planet benefits '
      + 'significantly ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)).',
    ja:
      '暖房の設定温度を1度下げるだけで1日'
      + 'あたり約**450gのCO2**を削減できます。'
      + 'この調整だけで暖房のエネルギー消費を'
      + '約10%減らせます（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。6ヶ月の暖房シーズンで'
      + '80kg以上のCO2を回避できます。室内で'
      + '1枚多く着るだけで違いはほとんど感じ'
      + 'ませんが地球への効果は大きいです'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Bajar el termostato de calefacción '
      + 'solo 1 grado Celsius ahorra '
      + 'aproximadamente **450g de CO2** por '
      + 'día. Este único ajuste puede reducir '
      + 'el consumo energético de calefacción '
      + 'en un 10% ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'En una temporada de calefacción de '
      + 'seis meses, eso equivale a más de '
      + '80 kg de CO2 evitados. Usar una capa '
      + 'extra de ropa hace la diferencia '
      + 'apenas perceptible mientras el '
      + 'planeta se beneficia '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  raise_ac_thermostat: {
    en:
      'Raising your air conditioning '
      + 'thermostat by 1 degree Celsius saves '
      + 'roughly **350g of CO2** per day. '
      + 'Each degree higher reduces cooling '
      + 'energy by 3-5%, a significant saving '
      + 'over a full summer ([Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)). Ceiling fans can '
      + 'supplement the AC, making a room feel '
      + '3-4 degrees cooler at a fraction of '
      + 'the energy cost. Programmable '
      + 'thermostats help maintain the higher '
      + 'setting automatically when you are '
      + 'away ([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      'エアコンの設定温度を1度上げると1日'
      + 'あたり約**350gのCO2**を削減できます。'
      + '1度上げるごとに冷房エネルギーが3〜5%'
      + '減り、夏全体では大きな節約になります'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。シーリングファンを併用'
      + 'すると体感温度を3〜4度下げられ、消費'
      + 'エネルギーはわずかです。プログラム式'
      + 'サーモスタットなら外出時に自動で設定'
      + '温度を維持できます（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。',
    es:
      'Subir el termostato del aire '
      + 'acondicionado 1 grado Celsius ahorra '
      + 'aproximadamente **350g de CO2** por '
      + 'día. Cada grado más alto reduce la '
      + 'energía de refrigeración en un 3-5%, '
      + 'un ahorro significativo en todo el '
      + 'verano ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Los ventiladores de techo pueden '
      + 'complementar el AC, haciendo sentir '
      + '3-4 grados menos con una fracción de '
      + 'la energía. Los termostatos '
      + 'programables mantienen el ajuste '
      + 'automáticamente cuando no estás '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  use_natural_light: {
    en:
      'Opening curtains and blinds to use '
      + 'daylight instead of electric '
      + 'lighting saves roughly **90g of '
      + 'CO2 per day**. Natural light can '
      + 'replace several bulbs worth of '
      + 'electricity for 8-10 hours during '
      + 'daytime ([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). Beyond energy savings, '
      + 'exposure to natural light improves '
      + 'circadian rhythm and productivity. '
      + 'Strategic use of mirrors and light-'
      + 'coloured walls can further amplify '
      + 'natural light deeper into your home '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      'カーテンやブラインドを開けて電気照明'
      + 'の代わりに自然光を使うと1日あたり約'
      + '**90gのCO2**を削減できます。自然光は'
      + '日中8〜10時間にわたり複数の電球分の'
      + '電力を代替できます（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。省エネだけでなく自然光'
      + 'は体内時計の改善や生産性の向上にも'
      + '効果があります。鏡や明るい色の壁を'
      + '活用すると自然光を室内の奥まで届ける'
      + 'ことができます（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。',
    es:
      'Abrir cortinas y persianas para '
      + 'aprovechar la luz natural en vez de '
      + 'la iluminación eléctrica ahorra '
      + 'aproximadamente **90g de CO2 al '
      + 'día**. La luz natural puede sustituir '
      + 'varias bombillas durante 8-10 horas '
      + 'del día ([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). Más allá del ahorro '
      + 'energético, la exposición a la luz '
      + 'natural mejora el ritmo circadiano y '
      + 'la productividad. El uso estratégico '
      + 'de espejos y paredes claras amplifica '
      + 'la luz natural hacia el interior del '
      + 'hogar ([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  full_laundry_load: {
    en:
      'Running a full laundry load instead '
      + 'of a half load saves about **300g of '
      + 'CO2** per wash. Half loads waste '
      + 'roughly 50% of the water and energy '
      + 'used, since the machine runs a nearly '
      + 'identical cycle regardless of load '
      + 'size ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Waiting until you have a full load '
      + 'also means fewer total cycles per '
      + 'year, extending machine life. This '
      + 'reduces both your carbon footprint '
      + 'and utility bills ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)).',
    ja:
      '半分の量ではなく満杯で洗濯すると'
      + '1回あたり約**300gのCO2**を節約でき'
      + 'ます。半量の洗濯は水とエネルギーの約'
      + '50%を無駄にします。洗濯機は量に'
      + 'かかわらずほぼ同じサイクルを回すため'
      + 'です（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。満杯になるまで待つことで'
      + '年間の総サイクル数が減り洗濯機の寿命'
      + 'も延びます。カーボンフットプリントと'
      + '光熱費の両方を削減できます'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Poner una carga completa de lavadora '
      + 'en vez de media ahorra unos **300g de '
      + 'CO2** por lavado. Las medias cargas '
      + 'desperdician aproximadamente el 50% '
      + 'del agua y la energía, ya que la '
      + 'máquina ejecuta un ciclo casi '
      + 'idéntico sin importar la cantidad '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Esperar a tener carga completa '
      + 'también significa menos ciclos al '
      + 'año, prolongando la vida de la '
      + 'máquina. Esto reduce tanto la huella '
      + 'de carbono como las facturas '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  eco_mode_appliance: {
    en:
      'Using the eco mode on your appliance '
      + 'saves roughly **200g of CO2** per '
      + 'cycle. Eco programmes typically '
      + 'reduce energy consumption by about '
      + '30% through lower temperatures and '
      + 'optimised water usage ([Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)). Dishwashers and washing '
      + 'machines both benefit significantly '
      + 'from eco settings. While eco cycles '
      + 'may run slightly longer, they use '
      + 'far less electricity and water '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '家電のエコモードを使うと1サイクル'
      + 'あたり約**200gのCO2**を削減できます。'
      + 'エコプログラムは低温運転と最適な水量'
      + 'で消費エネルギーを約30%削減します'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。食洗機も洗濯機もエコ'
      + 'モードの恩恵は大きいです。エコサイクル'
      + 'は少し長くなることがありますが電力と'
      + '水の使用量は大幅に減ります'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Usar el modo eco de tu electrodoméstico '
      + 'ahorra aproximadamente **200g de '
      + 'CO2** por ciclo. Los programas eco '
      + 'reducen el consumo energético en un '
      + '30% mediante temperaturas más bajas y '
      + 'uso optimizado de agua ([Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)). Tanto '
      + 'lavavajillas como lavadoras se '
      + 'benefician significativamente del '
      + 'modo eco. Aunque los ciclos eco '
      + 'pueden durar un poco más, usan mucha '
      + 'menos electricidad y agua '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  microwave_vs_oven: {
    en:
      'Using a microwave instead of a '
      + 'conventional oven saves roughly '
      + '**150g of CO2** per cooking session. '
      + 'Microwaves use 70-80% less energy '
      + 'than ovens because they heat food '
      + 'directly rather than warming an '
      + 'entire cavity ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'They also reach cooking temperature '
      + 'almost instantly, eliminating '
      + 'preheating waste. For reheating and '
      + 'small portions, the microwave is the '
      + 'clear winner for efficiency '
      + '([US DOE](https://www.energy.gov'
      + '/energysaver/lighting-choices-save'
      + '-you-money)).',
    ja:
      'オーブンの代わりに電子レンジを使うと'
      + '1回の調理で約**150gのCO2**を削減でき'
      + 'ます。電子レンジはオーブンより70〜80%'
      + '少ないエネルギーで済みます。庫内全体'
      + 'を温めるのではなく食品を直接加熱する'
      + 'ためです（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。予熱もほぼ不要で待ち時間'
      + 'の無駄もありません。温め直しや少量の'
      + '調理では電子レンジが効率面で圧倒的'
      + 'です（[米国エネルギー省]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)）。',
    es:
      'Usar el microondas en vez del horno '
      + 'convencional ahorra aproximadamente '
      + '**150g de CO2** por sesión de '
      + 'cocción. Los microondas usan 70-80% '
      + 'menos energía que los hornos porque '
      + 'calientan la comida directamente en '
      + 'vez de toda la cavidad ([Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)). Además '
      + 'alcanzan la temperatura de cocción '
      + 'casi al instante, eliminando el '
      + 'desperdicio del precalentamiento. '
      + 'Para recalentar y porciones pequeñas, '
      + 'el microondas es claramente más '
      + 'eficiente ([US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)).',
  },

  use_fan_instead_of_ac: {
    en:
      'Using a ceiling or portable fan '
      + 'instead of air conditioning for a '
      + 'day saves roughly **1,200g of '
      + 'CO2**. A typical fan uses only '
      + '50-75 watts compared to 1,000-3,500 '
      + 'watts for a window or central AC '
      + 'unit ([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). On moderate days, fans '
      + 'combined with cross-ventilation can '
      + 'maintain comfortable temperatures '
      + 'at a fraction of the energy cost. '
      + 'Over a summer season, choosing fans '
      + 'on milder days can avoid over 100kg '
      + 'of CO2 ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas'
      + '-reporting-conversion-factors'
      + '-2024)).',
    ja:
      'エアコンの代わりに天井扇や携帯型'
      + 'ファンを1日使うと約**1,200gのCO2**'
      + 'を削減できます。一般的な扇風機の'
      + '消費電力は50〜75Wで窓型や集中型'
      + 'エアコンの1,000〜3,500Wと比べ'
      + 'ごくわずかです（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。穏やかな日には'
      + '扇風機と風通しの組み合わせで快適な'
      + '温度を維持でき冷房のほんの一部の'
      + 'エネルギーで済みます。夏の間'
      + '涼しい日に扇風機を選べば100kg以上'
      + 'のCO2を回避できます（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas'
      + '-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Usar un ventilador de techo o '
      + 'portátil en lugar del aire '
      + 'acondicionado durante un día ahorra '
      + 'aproximadamente **1.200g de CO2**. '
      + 'Un ventilador típico consume solo '
      + '50-75 vatios frente a los 1.000-3.500 '
      + 'vatios de una unidad de AC '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). En días moderados, los '
      + 'ventiladores combinados con '
      + 'ventilación cruzada pueden mantener '
      + 'temperaturas confortables a una '
      + 'fracción del coste energético. '
      + 'Durante una temporada de verano, '
      + 'elegir ventiladores en días suaves '
      + 'puede evitar más de 100kg de CO2 '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  // -------------------------------------------------------
  // WATER (10 actions)
  // -------------------------------------------------------
  shorter_shower: {
    en:
      'Cutting your shower by four minutes '
      + 'saves roughly **230g of CO2**. A '
      + 'hot shower emits about 55g of CO2 '
      + 'per minute from the energy needed '
      + 'to heat the water ([Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)). Over a year of daily '
      + 'showers, four minutes saved each '
      + 'time avoids over 80 kg of CO2. '
      + 'A shower timer or a favourite short '
      + 'playlist can help keep showers '
      + 'brief ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
    ja:
      'シャワーを4分短くすると約**230gの'
      + 'CO2**を節約できます。温水シャワーは'
      + '水を加熱するエネルギーにより1分あたり'
      + '約55gのCO2を排出します（[Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)）。毎日の'
      + 'シャワーで4分ずつ節約すると年間80kg'
      + '以上のCO2を回避できます。シャワー'
      + 'タイマーやお気に入りの短い曲の'
      + 'プレイリストが時間管理に役立ちます'
      + '（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。',
    es:
      'Reducir la ducha en cuatro minutos '
      + 'ahorra aproximadamente **230g de '
      + 'CO2**. Una ducha caliente emite unos '
      + '55g de CO2 por minuto por la energía '
      + 'necesaria para calentar el agua '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'En un año de duchas diarias, cuatro '
      + 'minutos menos cada vez evitan más de '
      + '80 kg de CO2. Un temporizador o una '
      + 'playlist corta favorita pueden ayudar '
      + 'a mantener duchas breves '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
  },

  turn_off_tap: {
    en:
      'Turning off the tap while brushing '
      + 'your teeth saves roughly **30g of '
      + 'CO2** per session. A running tap '
      + 'wastes about 15 litres in a typical '
      + 'two-minute brushing session '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Treating and pumping that water '
      + 'requires energy, which translates '
      + 'directly into carbon emissions. '
      + 'Twice-daily brushing means this '
      + 'small change saves over 20 kg of '
      + 'CO2 and 10,000 litres of water per '
      + 'year ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '歯磨き中に蛇口を閉めると1回あたり'
      + '約**30gのCO2**を節約できます。'
      + '2分間の歯磨き中に流しっぱなしにする'
      + 'と約15リットルの水が無駄になります'
      + '（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '水の処理とポンプにはエネルギーが必要'
      + 'でそれがCO2排出につながります。1日'
      + '2回の歯磨きでこの小さな変化が年間'
      + '20kg以上のCO2と10,000リットルの水を'
      + '節約します（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Cerrar el grifo al cepillarte los '
      + 'dientes ahorra aproximadamente '
      + '**30g de CO2** por sesión. Un grifo '
      + 'abierto desperdicia unos 15 litros '
      + 'en un cepillado típico de dos '
      + 'minutos ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Tratar y bombear esa agua requiere '
      + 'energía que se traduce directamente '
      + 'en emisiones de carbono. Cepillarse '
      + 'dos veces al día significa que este '
      + 'pequeño cambio ahorra más de 20 kg '
      + 'de CO2 y 10.000 litros de agua al '
      + 'año ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  full_dishwasher: {
    en:
      'Running a full dishwasher instead of '
      + 'a half-empty one saves about **80g '
      + 'of CO2** per cycle. The machine uses '
      + 'nearly the same water and energy '
      + 'regardless of how full it is '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'A full load also beats hand-washing '
      + 'in both water and energy efficiency. '
      + 'Using the eco setting on a full '
      + 'dishwasher maximises savings '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
    ja:
      '食洗機を半分ではなく満杯で回すと'
      + '1サイクルあたり約**80gのCO2**を節約'
      + 'できます。食洗機は容量にかかわらず'
      + 'ほぼ同じ水とエネルギーを使います'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。満杯の食洗機は手洗い'
      + 'より水もエネルギーも効率的です。'
      + '満杯の食洗機にエコ設定を使うと節約を'
      + '最大化できます（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。',
    es:
      'Poner el lavavajillas lleno en vez de '
      + 'medio vacío ahorra unos **80g de '
      + 'CO2** por ciclo. La máquina usa casi '
      + 'la misma agua y energía sin importar '
      + 'lo llena que este ([Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)). Una carga completa '
      + 'también supera al lavado a mano en '
      + 'eficiencia de agua y energía. Usar '
      + 'el modo eco con el lavavajillas lleno '
      + 'maximiza el ahorro ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
  },

  fix_leak: {
    en:
      'Fixing a leaking faucet or toilet '
      + 'prevents roughly **100,000g (100kg) '
      + 'of CO2** over its remaining lifetime '
      + 'by eliminating the continuous energy '
      + 'waste of treating and pumping water '
      + 'that goes straight down the drain. '
      + 'A single dripping faucet can waste '
      + 'over 10,000 litres of water per '
      + 'year ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'The embedded energy in treated water '
      + 'means every wasted litre also wastes '
      + 'electricity. This one-time repair '
      + 'delivers compounding savings for '
      + 'years, making it one of the most '
      + 'impactful home fixes for both your '
      + 'water bill and the climate.',
    ja:
      '水漏れする蛇口やトイレを修理すると'
      + '残りの使用期間で約**100,000g（100kg）'
      + 'のCO2**を防げます。排水に流れるだけ'
      + 'の水の処理・送水に使われる継続的な'
      + 'エネルギー浪費をなくせるためです。'
      + '1箇所の水漏れで年間10,000リットル'
      + '以上の水が無駄になります'
      + '（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '処理水には多くのエネルギーが含まれて'
      + 'おり無駄な1リットルは電力の浪費でも'
      + 'あります。この一度の修理で何年にも'
      + 'わたり節約効果が積み重なり水道代と'
      + '気候の両方に大きな効果があります。',
    es:
      'Reparar un grifo o inodoro con goteo '
      + 'evita aproximadamente **100.000g '
      + '(100 kg) de CO2** durante su vida '
      + 'útil restante, al eliminar el gasto '
      + 'continuo de energía en tratar y '
      + 'bombear agua que se va directamente '
      + 'por el desagüe. Un solo grifo con '
      + 'goteo puede desperdiciar más de '
      + '10.000 litros de agua al año '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'La energía incorporada en el agua '
      + 'tratada implica que cada litro '
      + 'desperdiciado también desperdicia '
      + 'electricidad. Esta reparación única '
      + 'genera ahorros acumulativos durante '
      + 'años, siendo una de las mejoras más '
      + 'impactantes para la factura del agua '
      + 'y el clima.',
  },

  cold_water_rinse: {
    en:
      'Rinsing with cold water instead of '
      + 'hot saves about **30g of CO2** per '
      + 'session. Hot water rinsing wastes '
      + 'energy on heating that provides no '
      + 'cleaning benefit for most tasks '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Cold rinses are equally effective '
      + 'for rinsing soap off dishes, produce, '
      + 'and hands. Over a year of daily '
      + 'rinsing, switching to cold avoids '
      + 'roughly 11 kg of CO2 '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
    ja:
      '温水ではなく冷水ですすぐと1回あたり'
      + '約**30gのCO2**を節約できます。温水'
      + 'でのすすぎはほとんどの作業で洗浄効果'
      + 'に差がなく加熱エネルギーの無駄です'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。食器や食材、手からの'
      + '石鹸のすすぎは冷水で同等に効果的です。'
      + '毎日のすすぎを冷水に切り替えると年間'
      + '約11kgのCO2を回避できます'
      + '（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。',
    es:
      'Enjuagar con agua fría en vez de '
      + 'caliente ahorra unos **30g de CO2** '
      + 'por sesión. El enjuague con agua '
      + 'caliente desperdicia energía en '
      + 'calentamiento que no aporta beneficio '
      + 'de limpieza en la mayoría de tareas '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'El enjuague frío es igualmente '
      + 'efectivo para quitar jabón de platos, '
      + 'alimentos y manos. En un año de '
      + 'enjuagues diarios, cambiar a frío '
      + 'evita aproximadamente 11 kg de CO2 '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
  },

  install_rain_collector: {
    en:
      'Installing a rain barrel or '
      + 'collection system saves roughly '
      + '**750g of CO2** by reducing the '
      + 'energy needed to pump, treat, and '
      + 'distribute municipal water. A '
      + 'typical rain barrel captures '
      + '200-500 litres per storm, providing '
      + 'free irrigation that bypasses the '
      + 'energy-intensive water treatment '
      + 'cycle ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'This is a one-time setup that pays '
      + 'back continuously. Rain collectors '
      + 'also reduce stormwater runoff, '
      + 'protecting local waterways from '
      + 'pollution ([UN SDG 6]'
      + '(https://sdgs.un.org/goals'
      + '/goal6)).',
    ja:
      '雨水タンクや集水システムを設置すると'
      + '水道水の送水・処理・配水に必要な'
      + 'エネルギーを減らし約**750gのCO2**を'
      + '削減できます。一般的な雨水タンクは'
      + '1回の雨で200〜500リットルを貯め、'
      + 'エネルギー集約的な水処理を経ない無料'
      + 'の灌漑用水を確保できます'
      + '（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '一度の設置で継続的に効果を発揮し'
      + 'ます。雨水収集は雨水流出も減らし地域'
      + 'の水路を汚染から守ります（[UN SDG 6]'
      + '(https://sdgs.un.org/goals'
      + '/goal6)）。',
    es:
      'Instalar un barril o sistema de '
      + 'recolección de agua de lluvia ahorra '
      + 'aproximadamente **750g de CO2** al '
      + 'reducir la energía necesaria para '
      + 'bombear, tratar y distribuir agua '
      + 'municipal. Un barril típico captura '
      + '200-500 litros por tormenta, '
      + 'proporcionando riego gratuito que '
      + 'evita el ciclo de tratamiento de agua '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Es una instalación única que se '
      + 'amortiza continuamente. Los '
      + 'recolectores de lluvia también '
      + 'reducen la escorrentía pluvial, '
      + 'protegiendo los cursos de agua '
      + 'locales de la contaminación '
      + '([UN SDG 6](https://sdgs.un.org'
      + '/goals/goal6)).',
  },

  water_plants_morning: {
    en:
      'Watering plants in the early morning '
      + 'saves about **10g of CO2** per '
      + 'session by reducing water waste. '
      + 'Morning watering cuts evaporation by '
      + '25-50% compared to midday, meaning '
      + 'less water needs to be drawn and '
      + 'treated ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Cooler soil also absorbs water more '
      + 'effectively, benefiting plant roots. '
      + 'This simple timing adjustment costs '
      + 'nothing and keeps your garden '
      + 'healthier ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '早朝に水やりをすると1回あたり約'
      + '**10gのCO2**を節約でき水の無駄を減ら'
      + 'せます。朝の水やりは日中と比べ蒸発量'
      + 'が25〜50%少なく必要な水の取水量と処理'
      + '量が減ります（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '涼しい土壌は水をより効果的に吸収し'
      + '根に恩恵をもたらします。このタイミング'
      + 'の調整はコストゼロで庭をより健康に'
      + '保てます（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Regar las plantas temprano en la '
      + 'mañana ahorra unos **10g de CO2** '
      + 'por sesión al reducir el desperdicio '
      + 'de agua. El riego matutino reduce la '
      + 'evaporación en un 25-50% comparado '
      + 'con el mediodía, lo que significa '
      + 'menos agua extraída y tratada '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'El suelo fresco absorbe el agua más '
      + 'eficazmente, beneficiando las raíces. '
      + 'Este simple ajuste de horario no '
      + 'cuesta nada y mantiene tu jardín más '
      + 'saludable ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  reuse_cooking_water: {
    en:
      'Reusing cooking water for plants or '
      + 'other purposes saves about **5g of '
      + 'CO2** per use. This avoids running '
      + 'fresh mains water, which requires '
      + 'energy for treatment and pumping '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Cooled pasta or vegetable water is '
      + 'rich in nutrients that benefit garden '
      + 'soil. This zero-cost habit reduces '
      + 'total household water consumption '
      + 'and gives plants a nutritional boost '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '料理に使った水を植物などに再利用'
      + 'すると1回あたり約**5gのCO2**を節約'
      + 'できます。水道水を新たに使うのを避け、'
      + '処理やポンプに必要なエネルギーを削減'
      + 'します（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '冷ましたパスタや野菜の茹で汁は栄養が'
      + '豊富で庭の土壌に良い影響を与えます。'
      + 'この費用ゼロの習慣で家庭の総水使用量'
      + 'を減らし植物に栄養も与えられます'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Reutilizar el agua de cocción para '
      + 'plantas u otros usos ahorra unos '
      + '**5g de CO2** por uso. Esto evita '
      + 'usar agua potable fresca que requiere '
      + 'energía para su tratamiento y bombeo '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'El agua enfriada de pasta o verduras '
      + 'es rica en nutrientes que benefician '
      + 'el suelo del jardín. Este hábito sin '
      + 'costo reduce el consumo total de agua '
      + 'del hogar y da un impulso nutricional '
      + 'a las plantas ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  turn_off_tap_dishes: {
    en:
      'Turning off the tap between rinsing '
      + 'dishes saves about **25g of CO2** '
      + 'per wash session. Leaving the tap '
      + 'running while scrubbing wastes '
      + 'roughly 12 litres of treated water '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Using a basin to collect rinse water '
      + 'is even more efficient. Over a year '
      + 'of daily dish-washing, this habit '
      + 'saves about 9 kg of CO2 and over '
      + '4,000 litres of water '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '食器洗い中に蛇口を閉めると1回の洗い'
      + '物で約**25gのCO2**を節約できます。'
      + 'こすり洗いの間に流しっぱなしにすると'
      + '約12リットルの処理済み水が無駄になり'
      + 'ます（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '洗い桶にすすぎ水を溜めるとさらに効率'
      + '的です。毎日の食器洗いで年間約9kgの'
      + 'CO2と4,000リットル以上の水を節約でき'
      + 'ます（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Cerrar el grifo entre enjuagues al '
      + 'lavar platos ahorra unos **25g de '
      + 'CO2** por sesión de lavado. Dejar el '
      + 'grifo abierto mientras se friega '
      + 'desperdicia unos 12 litros de agua '
      + 'tratada ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Usar un recipiente para recoger el '
      + 'agua de enjuague es aún más '
      + 'eficiente. En un año de lavado '
      + 'diario, este hábito ahorra unos 9 kg '
      + 'de CO2 y más de 4.000 litros de agua '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  shorter_bath: {
    en:
      'Taking a shorter bath or switching to '
      + 'a quick shower saves roughly **300g '
      + 'of CO2** per session. A standard bath '
      + 'uses about 80 litres of hot water '
      + 'compared to 40 litres for a five-'
      + 'minute shower ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Halving the bath water cuts heating '
      + 'energy proportionally. If a full bath '
      + 'is needed, filling it only two-thirds '
      + 'full still provides comfort while '
      + 'significantly reducing emissions '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '入浴時間を短くするかシャワーに切り'
      + '替えると1回あたり約**300gのCO2**を'
      + '削減できます。一般的な入浴は約80'
      + 'リットルの温水を使うのに対し5分の'
      + 'シャワーは約40リットルです（[Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)）。湯量を半分に'
      + 'すれば加熱エネルギーも比例して減り'
      + 'ます。入浴が必要な場合でも3分の2まで'
      + 'のお湯なら快適さを保ちながら排出量を'
      + '大幅に削減できます（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。',
    es:
      'Tomar un baño más corto o cambiar a '
      + 'una ducha rápida ahorra '
      + 'aproximadamente **300g de CO2** por '
      + 'sesión. Un baño estándar usa unos 80 '
      + 'litros de agua caliente frente a 40 '
      + 'litros de una ducha de cinco minutos '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Reducir el agua del baño a la mitad '
      + 'reduce la energía de calentamiento '
      + 'proporcionalmente. Si se necesita un '
      + 'baño completo, llenarlo solo dos '
      + 'tercios ofrece comodidad reduciendo '
      + 'significativamente las emisiones '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },
};

module.exports = descriptions;
