/**
 * Long descriptions for eco-actions:
 * ENERGY, WATER categories.
 *
 * Each description is 3-5 sentences with markdown
 * formatting, bold CO2 figures, and source links.
 *
 * This is a partial file merged into the final
 * descriptions module.
 */

const descriptions = {
  // -------------------------------------------------------
  // ENERGY (12 actions)
  // -------------------------------------------------------
  air_dry_clothes: {
    en:
      'Air drying your laundry instead of '
      + 'using a tumble dryer saves roughly '
      + '**1,700g of CO2** per load. A typical '
      + 'dryer consumes about 4.5 kWh per '
      + 'cycle, making it one of the most '
      + 'energy-hungry household appliances '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Over a year of weekly loads, air '
      + 'drying avoids nearly 90 kg of CO2. '
      + 'Clotheslines and drying racks cost '
      + 'nothing to operate and also extend '
      + 'the lifespan of your garments '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '乾燥機の代わりに洗濯物を自然乾燥'
      + 'すると1回あたり約**1,700gのCO2**を'
      + '削減できます。一般的な乾燥機は1回で'
      + '約4.5kWhを消費し、家庭で最も電力を'
      + '使う機器の一つです（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。週1回の洗濯を年間通して'
      + '自然乾燥にすると約90kgのCO2を回避'
      + 'できます。物干しや乾燥ラックは運転'
      + 'コストがゼロで衣類の寿命も延ばします'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Secar la ropa al aire en vez de usar '
      + 'secadora ahorra aproximadamente '
      + '**1.700g de CO2** por carga. Una '
      + 'secadora típica consume unos 4,5 kWh '
      + 'por ciclo, siendo uno de los '
      + 'electrodomésticos de mayor consumo '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'En un año de cargas semanales, el '
      + 'secado al aire evita casi 90 kg de '
      + 'CO2. Los tendederos no tienen costo '
      + 'operativo y además prolongan la vida '
      + 'de la ropa ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)).',
  },

  cold_wash: {
    en:
      'Washing clothes in cold water saves '
      + 'about **600g of CO2** per load '
      + 'because roughly 90% of the energy '
      + 'a washing machine uses goes to '
      + 'heating water ([US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)). '
      + 'Modern detergents are formulated to '
      + 'clean effectively at low temperatures. '
      + 'Cold washing also prevents colour '
      + 'fading and fabric shrinkage, keeping '
      + 'clothes looking new longer '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Over a year of weekly washes, this '
      + 'simple switch avoids over 30 kg '
      + 'of CO2.',
    ja:
      '洗濯を冷水で行うと1回あたり約'
      + '**600gのCO2**を削減できます。'
      + '洗濯機のエネルギーの約90%は水の加熱'
      + 'に使われるためです（[米国エネルギー省]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)）。'
      + '最新の洗剤は低温でも効果的に洗浄'
      + 'できるよう設計されています。冷水洗い'
      + 'は色落ちや縮みも防ぎ衣類を長持ちさせ'
      + 'ます（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。週1回の洗濯で年間30kg'
      + '以上のCO2を回避できます。',
    es:
      'Lavar la ropa con agua fria ahorra '
      + 'unos **600g de CO2** por carga, ya '
      + 'que aproximadamente el 90% de la '
      + 'energia de una lavadora se destina a '
      + 'calentar el agua ([US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)). '
      + 'Los detergentes modernos estan '
      + 'formulados para limpiar eficazmente a '
      + 'bajas temperaturas. El lavado en frio '
      + 'tambien previene la decoloracion y '
      + 'el encogimiento ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'En un ano de lavados semanales, este '
      + 'simple cambio evita mas de 30 kg '
      + 'de CO2.',
  },

  install_led_bulb: {
    en:
      'Installing an LED bulb to replace an '
      + 'incandescent saves roughly '
      + '**28,000g (28kg) of CO2** in its '
      + 'first year alone. LEDs consume 75% '
      + 'less energy than incandescent bulbs '
      + 'and last up to 25 times longer '
      + '([US DOE](https://www.energy.gov'
      + '/energysaver/lighting-choices-save'
      + '-you-money)). Over a bulb\'s '
      + '15,000-hour lifespan the cumulative '
      + 'savings exceed 280kg of CO2 '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). LEDs also produce less '
      + 'heat, reducing summer cooling '
      + 'loads.',
    ja:
      'LED電球に交換すると一般的な使用で'
      + '1日あたり約**75gのCO2**を削減でき'
      + 'ます。LEDは白熱電球より75%少ない'
      + 'エネルギーで済み寿命は最大25倍です'
      + '（[米国エネルギー省]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)）。'
      + 'LED1時間の使用で従来の60W電球と比べ'
      + '約19gのCO2を節約できます。15,000時間'
      + 'の寿命を通じて累積280kg以上のCO2を'
      + '削減します（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。発熱も少なく夏の冷房'
      + '負荷の軽減にもなります。',
    es:
      'Cambiar a una bombilla LED ahorra '
      + 'unos **75g de CO2** por dia de uso '
      + 'tipico. Los LED consumen 75% menos '
      + 'energia que las incandescentes y '
      + 'duran hasta 25 veces mas ([US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)). '
      + 'Cada hora de uso LED ahorra unos 19g '
      + 'de CO2 frente a una bombilla de 60W. '
      + 'En su vida util de 15.000 horas, el '
      + 'ahorro acumulado supera los 280 kg '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Los LED tambien producen menos calor, '
      + 'reduciendo la carga de refrigeracion.',
  },

  unplug_devices: {
    en:
      'Unplugging idle devices across your '
      + 'home saves about **45g of CO2 per '
      + 'day**. Standby mode draws 1-5 watts '
      + 'per device continuously, and the '
      + 'average home has 20-40 devices on '
      + 'standby ([Lawrence Berkeley National '
      + 'Lab](https://standby.lbl.gov/)). '
      + 'Collectively, standby power accounts '
      + 'for 5-10% of residential electricity '
      + 'use. A smart power strip can '
      + 'automate this by cutting phantom '
      + 'loads when devices are off '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). Small daily habits like '
      + 'this compound into meaningful '
      + 'annual savings.',
    ja:
      '待機中の機器のプラグを抜くと1台'
      + 'あたり1日約**10gのCO2**を節約でき'
      + 'ます。待機電力は1〜5Wを常時消費し、'
      + '一般家庭では20〜40台が待機状態です'
      + '（[ローレンスバークレー国立研究所]'
      + '(https://standby.lbl.gov/)）。'
      + '待機電力は家庭の電力消費の5〜10%を'
      + '占めます。スマート電源タップなら機器'
      + 'オフ時の待機電力を自動でカットできます'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。毎日の小さな習慣が年間'
      + 'では大きな節約になります。',
    es:
      'Desconectar dispositivos en espera '
      + 'ahorra unos **10g de CO2** por '
      + 'aparato al dia. El modo espera '
      + 'consume 1-5 vatios continuamente, y '
      + 'un hogar promedio tiene 20-40 '
      + 'dispositivos en espera ([Lawrence '
      + 'Berkeley National Lab]'
      + '(https://standby.lbl.gov/)). '
      + 'En conjunto, la energia en espera '
      + 'representa el 5-10% del consumo '
      + 'electrico residencial. Una regleta '
      + 'inteligente puede automatizar esto '
      + 'cortando cargas fantasma '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Pequenos habitos diarios se acumulan '
      + 'en ahorros anuales significativos.',
  },

  turn_off_lights: {
    en:
      'Making a habit of turning off lights '
      + 'in empty rooms saves roughly '
      + '**60g of CO2 per day** across a '
      + 'typical home. Lights left on in '
      + 'unoccupied rooms are among the most '
      + 'common sources of wasted household '
      + 'energy ([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). A household that '
      + 'consistently switches off unused '
      + 'lights can save 5-10% on its '
      + 'electricity bill annually. Pairing '
      + 'this habit with motion sensors or '
      + 'timers maximises the effect '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '60Wの照明を1時間消すと約**30gの'
      + 'CO2**を節約できます。小さく見えます'
      + 'が空き部屋の点けっぱなしは家庭の'
      + 'エネルギー浪費の最も一般的な原因です'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。使わない照明をこまめに'
      + '消す家庭は年間の電気代を5〜10%節約'
      + 'できます。人感センサーやタイマーと'
      + '組み合わせると効果を最大化できます'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Apagar una luz de 60W durante una '
      + 'hora ahorra aproximadamente **30g de '
      + 'CO2**. Aunque parece poco, las luces '
      + 'encendidas en habitaciones vacias son '
      + 'una de las fuentes mas comunes de '
      + 'desperdicio energetico en el hogar '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Un hogar que apaga sistematicamente '
      + 'las luces puede ahorrar 5-10% en su '
      + 'factura electrica anual. Combinar '
      + 'este habito con sensores de '
      + 'movimiento o temporizadores maximiza '
      + 'el efecto ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)).',
  },

  lower_thermostat: {
    en:
      'Lowering your heating thermostat by '
      + 'just 1 degree Celsius saves roughly '
      + '**450g of CO2** per day. This single '
      + 'adjustment can reduce heating energy '
      + 'consumption by about 10% '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Over a six-month heating season, '
      + 'that amounts to over 80 kg of CO2 '
      + 'avoided. Wearing an extra layer '
      + 'indoors makes the difference barely '
      + 'noticeable while the planet benefits '
      + 'significantly ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)).',
    ja:
      '暖房の設定温度を1度下げるだけで1日'
      + 'あたり約**450gのCO2**を削減できます。'
      + 'この調整だけで暖房のエネルギー消費を'
      + '約10%減らせます（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。6ヶ月の暖房シーズンで'
      + '80kg以上のCO2を回避できます。室内で'
      + '1枚多く着るだけで違いはほとんど感じ'
      + 'ませんが地球への効果は大きいです'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Bajar el termostato de calefaccion '
      + 'solo 1 grado Celsius ahorra '
      + 'aproximadamente **450g de CO2** por '
      + 'dia. Este unico ajuste puede reducir '
      + 'el consumo energetico de calefaccion '
      + 'en un 10% ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'En una temporada de calefaccion de '
      + 'seis meses, eso equivale a mas de '
      + '80 kg de CO2 evitados. Usar una capa '
      + 'extra de ropa hace la diferencia '
      + 'apenas perceptible mientras el '
      + 'planeta se beneficia '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  raise_ac_thermostat: {
    en:
      'Raising your air conditioning '
      + 'thermostat by 1 degree Celsius saves '
      + 'roughly **350g of CO2** per day. '
      + 'Each degree higher reduces cooling '
      + 'energy by 3-5%, a significant saving '
      + 'over a full summer ([Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)). Ceiling fans can '
      + 'supplement the AC, making a room feel '
      + '3-4 degrees cooler at a fraction of '
      + 'the energy cost. Programmable '
      + 'thermostats help maintain the higher '
      + 'setting automatically when you are '
      + 'away ([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      'エアコンの設定温度を1度上げると1日'
      + 'あたり約**350gのCO2**を削減できます。'
      + '1度上げるごとに冷房エネルギーが3〜5%'
      + '減り、夏全体では大きな節約になります'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。シーリングファンを併用'
      + 'すると体感温度を3〜4度下げられ、消費'
      + 'エネルギーはわずかです。プログラム式'
      + 'サーモスタットなら外出時に自動で設定'
      + '温度を維持できます（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。',
    es:
      'Subir el termostato del aire '
      + 'acondicionado 1 grado Celsius ahorra '
      + 'aproximadamente **350g de CO2** por '
      + 'dia. Cada grado mas alto reduce la '
      + 'energia de refrigeracion en un 3-5%, '
      + 'un ahorro significativo en todo el '
      + 'verano ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Los ventiladores de techo pueden '
      + 'complementar el AC, haciendo sentir '
      + '3-4 grados menos con una fraccion de '
      + 'la energia. Los termostatos '
      + 'programables mantienen el ajuste '
      + 'automaticamente cuando no estas '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  use_natural_light: {
    en:
      'Opening curtains and blinds to use '
      + 'daylight instead of electric '
      + 'lighting saves roughly **90g of '
      + 'CO2 per day**. Natural light can '
      + 'replace several bulbs worth of '
      + 'electricity for 8-10 hours during '
      + 'daytime ([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). Beyond energy savings, '
      + 'exposure to natural light improves '
      + 'circadian rhythm and productivity. '
      + 'Strategic use of mirrors and light-'
      + 'coloured walls can further amplify '
      + 'natural light deeper into your home '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '電気の代わりに自然光を使うと1回'
      + 'あたり約**20gのCO2**を節約できます。'
      + '電球の代わりに自然光を1時間使うごとに'
      + '約3.7gの排出を回避できます'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。カーテンを開けてデスクを'
      + '窓際に配置すると自然光を最大限活用'
      + 'できます。日光は気分の向上や生産性の'
      + '改善にも効果があるとされています'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Usar luz natural en vez de luces '
      + 'electricas ahorra aproximadamente '
      + '**20g de CO2** por sesion. Cada hora '
      + 'de luz solar usada en lugar de una '
      + 'bombilla evita unos 3,7g de '
      + 'emisiones ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)). '
      + 'Abrir cortinas y colocar escritorios '
      + 'cerca de ventanas maximiza la '
      + 'penetracion de luz natural. Estudios '
      + 'muestran que la exposicion a luz '
      + 'solar mejora el animo y la '
      + 'productividad ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  full_laundry_load: {
    en:
      'Running a full laundry load instead '
      + 'of a half load saves about **300g of '
      + 'CO2** per wash. Half loads waste '
      + 'roughly 50% of the water and energy '
      + 'used, since the machine runs a nearly '
      + 'identical cycle regardless of load '
      + 'size ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Waiting until you have a full load '
      + 'also means fewer total cycles per '
      + 'year, extending machine life. This '
      + 'reduces both your carbon footprint '
      + 'and utility bills ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)).',
    ja:
      '半分の量ではなく満杯で洗濯すると'
      + '1回あたり約**300gのCO2**を節約でき'
      + 'ます。半量の洗濯は水とエネルギーの約'
      + '50%を無駄にします。洗濯機は量に'
      + 'かかわらずほぼ同じサイクルを回すため'
      + 'です（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。満杯になるまで待つことで'
      + '年間の総サイクル数が減り洗濯機の寿命'
      + 'も延びます。カーボンフットプリントと'
      + '光熱費の両方を削減できます'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Poner una carga completa de lavadora '
      + 'en vez de media ahorra unos **300g de '
      + 'CO2** por lavado. Las medias cargas '
      + 'desperdician aproximadamente el 50% '
      + 'del agua y la energia, ya que la '
      + 'maquina ejecuta un ciclo casi '
      + 'identico sin importar la cantidad '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Esperar a tener carga completa '
      + 'tambien significa menos ciclos al '
      + 'ano, prolongando la vida de la '
      + 'maquina. Esto reduce tanto la huella '
      + 'de carbono como las facturas '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  eco_mode_appliance: {
    en:
      'Using the eco mode on your appliance '
      + 'saves roughly **200g of CO2** per '
      + 'cycle. Eco programmes typically '
      + 'reduce energy consumption by about '
      + '30% through lower temperatures and '
      + 'optimised water usage ([Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)). Dishwashers and washing '
      + 'machines both benefit significantly '
      + 'from eco settings. While eco cycles '
      + 'may run slightly longer, they use '
      + 'far less electricity and water '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '家電のエコモードを使うと1サイクル'
      + 'あたり約**200gのCO2**を削減できます。'
      + 'エコプログラムは低温運転と最適な水量'
      + 'で消費エネルギーを約30%削減します'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。食洗機も洗濯機もエコ'
      + 'モードの恩恵は大きいです。エコサイクル'
      + 'は少し長くなることがありますが電力と'
      + '水の使用量は大幅に減ります'
      + '（[DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Usar el modo eco de tu electrodomestico '
      + 'ahorra aproximadamente **200g de '
      + 'CO2** por ciclo. Los programas eco '
      + 'reducen el consumo energetico en un '
      + '30% mediante temperaturas mas bajas y '
      + 'uso optimizado de agua ([Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)). Tanto '
      + 'lavavajillas como lavadoras se '
      + 'benefician significativamente del '
      + 'modo eco. Aunque los ciclos eco '
      + 'pueden durar un poco mas, usan mucha '
      + 'menos electricidad y agua '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  microwave_vs_oven: {
    en:
      'Using a microwave instead of a '
      + 'conventional oven saves roughly '
      + '**150g of CO2** per cooking session. '
      + 'Microwaves use 70-80% less energy '
      + 'than ovens because they heat food '
      + 'directly rather than warming an '
      + 'entire cavity ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'They also reach cooking temperature '
      + 'almost instantly, eliminating '
      + 'preheating waste. For reheating and '
      + 'small portions, the microwave is the '
      + 'clear winner for efficiency '
      + '([US DOE](https://www.energy.gov'
      + '/energysaver/lighting-choices-save'
      + '-you-money)).',
    ja:
      'オーブンの代わりに電子レンジを使うと'
      + '1回の調理で約**150gのCO2**を削減でき'
      + 'ます。電子レンジはオーブンより70〜80%'
      + '少ないエネルギーで済みます。庫内全体'
      + 'を温めるのではなく食品を直接加熱する'
      + 'ためです（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。予熱もほぼ不要で待ち時間'
      + 'の無駄もありません。温め直しや少量の'
      + '調理では電子レンジが効率面で圧倒的'
      + 'です（[米国エネルギー省]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)）。',
    es:
      'Usar el microondas en vez del horno '
      + 'convencional ahorra aproximadamente '
      + '**150g de CO2** por sesion de '
      + 'coccion. Los microondas usan 70-80% '
      + 'menos energia que los hornos porque '
      + 'calientan la comida directamente en '
      + 'vez de toda la cavidad ([Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)). Ademas '
      + 'alcanzan la temperatura de coccion '
      + 'casi al instante, eliminando el '
      + 'desperdicio del precalentamiento. '
      + 'Para recalentar y porciones pequenas, '
      + 'el microondas es claramente mas '
      + 'eficiente ([US DOE]'
      + '(https://www.energy.gov/energysaver'
      + '/lighting-choices-save-you-money)).',
  },

  use_fan_instead_of_ac: {
    en:
      'Using a ceiling or portable fan '
      + 'instead of air conditioning for a '
      + 'day saves roughly **1,200g of '
      + 'CO2**. A typical fan uses only '
      + '50-75 watts compared to 1,000-3,500 '
      + 'watts for a window or central AC '
      + 'unit ([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). On moderate days, fans '
      + 'combined with cross-ventilation can '
      + 'maintain comfortable temperatures '
      + 'at a fraction of the energy cost. '
      + 'Over a summer season, choosing fans '
      + 'on milder days can avoid over 100kg '
      + 'of CO2 ([DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas'
      + '-reporting-conversion-factors'
      + '-2024)).',
    ja:
      'エアコンの代わりに天井扇や携帯型'
      + 'ファンを1日使うと約**1,200gのCO2**'
      + 'を削減できます。一般的な扇風機の'
      + '消費電力は50〜75Wで窓型や集中型'
      + 'エアコンの1,000〜3,500Wと比べ'
      + 'ごくわずかです（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。穏やかな日には'
      + '扇風機と風通しの組み合わせで快適な'
      + '温度を維持でき冷房のほんの一部の'
      + 'エネルギーで済みます。夏の間'
      + '涼しい日に扇風機を選べば100kg以上'
      + 'のCO2を回避できます（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas'
      + '-reporting-conversion-factors'
      + '-2024)）。',
    es:
      'Usar un ventilador de techo o '
      + 'portatil en lugar del aire '
      + 'acondicionado durante un dia ahorra '
      + 'aproximadamente **1.200g de CO2**. '
      + 'Un ventilador tipico consume solo '
      + '50-75 vatios frente a los 1.000-3.500 '
      + 'vatios de una unidad de AC '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)). En dias moderados, los '
      + 'ventiladores combinados con '
      + 'ventilacion cruzada pueden mantener '
      + 'temperaturas confortables a una '
      + 'fraccion del coste energetico. '
      + 'Durante una temporada de verano, '
      + 'elegir ventiladores en dias suaves '
      + 'puede evitar mas de 100kg de CO2 '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },

  // -------------------------------------------------------
  // WATER (10 actions)
  // -------------------------------------------------------
  shorter_shower: {
    en:
      'Cutting your shower by four minutes '
      + 'saves roughly **230g of CO2**. A '
      + 'hot shower emits about 55g of CO2 '
      + 'per minute from the energy needed '
      + 'to heat the water ([Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)). Over a year of daily '
      + 'showers, four minutes saved each '
      + 'time avoids over 80 kg of CO2. '
      + 'A shower timer or a favourite short '
      + 'playlist can help keep showers '
      + 'brief ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
    ja:
      'シャワーを4分短くすると約**230gの'
      + 'CO2**を節約できます。温水シャワーは'
      + '水を加熱するエネルギーにより1分あたり'
      + '約55gのCO2を排出します（[Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)）。毎日の'
      + 'シャワーで4分ずつ節約すると年間80kg'
      + '以上のCO2を回避できます。シャワー'
      + 'タイマーやお気に入りの短い曲の'
      + 'プレイリストが時間管理に役立ちます'
      + '（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。',
    es:
      'Reducir la ducha en cuatro minutos '
      + 'ahorra aproximadamente **230g de '
      + 'CO2**. Una ducha caliente emite unos '
      + '55g de CO2 por minuto por la energia '
      + 'necesaria para calentar el agua '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'En un ano de duchas diarias, cuatro '
      + 'minutos menos cada vez evitan mas de '
      + '80 kg de CO2. Un temporizador o una '
      + 'playlist corta favorita pueden ayudar '
      + 'a mantener duchas breves '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
  },

  turn_off_tap: {
    en:
      'Turning off the tap while brushing '
      + 'your teeth saves roughly **30g of '
      + 'CO2** per session. A running tap '
      + 'wastes about 15 litres in a typical '
      + 'two-minute brushing session '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Treating and pumping that water '
      + 'requires energy, which translates '
      + 'directly into carbon emissions. '
      + 'Twice-daily brushing means this '
      + 'small change saves over 20 kg of '
      + 'CO2 and 10,000 litres of water per '
      + 'year ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '歯磨き中に蛇口を閉めると1回あたり'
      + '約**30gのCO2**を節約できます。'
      + '2分間の歯磨き中に流しっぱなしにする'
      + 'と約15リットルの水が無駄になります'
      + '（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '水の処理とポンプにはエネルギーが必要'
      + 'でそれがCO2排出につながります。1日'
      + '2回の歯磨きでこの小さな変化が年間'
      + '20kg以上のCO2と10,000リットルの水を'
      + '節約します（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Cerrar el grifo al cepillarte los '
      + 'dientes ahorra aproximadamente '
      + '**30g de CO2** por sesion. Un grifo '
      + 'abierto desperdicia unos 15 litros '
      + 'en un cepillado tipico de dos '
      + 'minutos ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Tratar y bombear esa agua requiere '
      + 'energia que se traduce directamente '
      + 'en emisiones de carbono. Cepillarse '
      + 'dos veces al dia significa que este '
      + 'pequeno cambio ahorra mas de 20 kg '
      + 'de CO2 y 10.000 litros de agua al '
      + 'ano ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  full_dishwasher: {
    en:
      'Running a full dishwasher instead of '
      + 'a half-empty one saves about **80g '
      + 'of CO2** per cycle. The machine uses '
      + 'nearly the same water and energy '
      + 'regardless of how full it is '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'A full load also beats hand-washing '
      + 'in both water and energy efficiency. '
      + 'Using the eco setting on a full '
      + 'dishwasher maximises savings '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
    ja:
      '食洗機を半分ではなく満杯で回すと'
      + '1サイクルあたり約**80gのCO2**を節約'
      + 'できます。食洗機は容量にかかわらず'
      + 'ほぼ同じ水とエネルギーを使います'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。満杯の食洗機は手洗い'
      + 'より水もエネルギーも効率的です。'
      + '満杯の食洗機にエコ設定を使うと節約を'
      + '最大化できます（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。',
    es:
      'Poner el lavavajillas lleno en vez de '
      + 'medio vacio ahorra unos **80g de '
      + 'CO2** por ciclo. La maquina usa casi '
      + 'la misma agua y energia sin importar '
      + 'lo llena que este ([Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)). Una carga completa '
      + 'tambien supera al lavado a mano en '
      + 'eficiencia de agua y energia. Usar '
      + 'el modo eco con el lavavajillas lleno '
      + 'maximiza el ahorro ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
  },

  fix_leak: {
    en:
      'Fixing a leaking faucet or toilet '
      + 'prevents roughly **100,000g (100kg) '
      + 'of CO2** over its remaining lifetime '
      + 'by eliminating the continuous energy '
      + 'waste of treating and pumping water '
      + 'that goes straight down the drain. '
      + 'A single dripping faucet can waste '
      + 'over 10,000 litres of water per '
      + 'year ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'The embedded energy in treated water '
      + 'means every wasted litre also wastes '
      + 'electricity. This one-time repair '
      + 'delivers compounding savings for '
      + 'years, making it one of the most '
      + 'impactful home fixes for both your '
      + 'water bill and the climate.',
    ja:
      '水漏れを修理すると月あたり約'
      + '**500gのCO2**を節約できます。'
      + '1箇所のポタポタした水漏れで1日約'
      + '3.8リットル、年間1,300リットル以上が'
      + '無駄になります（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '無駄な水の処理やポンプに使うエネルギー'
      + 'は累積すると大きな排出量になります。'
      + '温水の水漏れは加熱エネルギーも無駄に'
      + 'するため特に深刻です（[Energy Saving '
      + 'Trust](https://energysavingtrust'
      + '.org.uk/)）。多くの場合パッキンの交換'
      + 'だけで修理できます。',
    es:
      'Reparar un grifo o tuberia con goteo '
      + 'puede ahorrar aproximadamente '
      + '**500g de CO2** al mes. Un solo '
      + 'goteo desperdicia unos 3,8 litros '
      + 'por dia, sumando mas de 1.300 litros '
      + 'al ano ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'La energia usada para tratar y '
      + 'bombear agua desperdiciada produce '
      + 'emisiones acumulativas significativas. '
      + 'Las fugas de agua caliente son '
      + 'especialmente costosas ya que tambien '
      + 'desperdician energia de calefaccion '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'La mayoria de goteos requieren solo '
      + 'un simple cambio de arandela.',
  },

  cold_water_rinse: {
    en:
      'Rinsing with cold water instead of '
      + 'hot saves about **30g of CO2** per '
      + 'session. Hot water rinsing wastes '
      + 'energy on heating that provides no '
      + 'cleaning benefit for most tasks '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Cold rinses are equally effective '
      + 'for rinsing soap off dishes, produce, '
      + 'and hands. Over a year of daily '
      + 'rinsing, switching to cold avoids '
      + 'roughly 11 kg of CO2 '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
    ja:
      '温水ではなく冷水ですすぐと1回あたり'
      + '約**30gのCO2**を節約できます。温水'
      + 'でのすすぎはほとんどの作業で洗浄効果'
      + 'に差がなく加熱エネルギーの無駄です'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。食器や食材、手からの'
      + '石鹸のすすぎは冷水で同等に効果的です。'
      + '毎日のすすぎを冷水に切り替えると年間'
      + '約11kgのCO2を回避できます'
      + '（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。',
    es:
      'Enjuagar con agua fria en vez de '
      + 'caliente ahorra unos **30g de CO2** '
      + 'por sesion. El enjuague con agua '
      + 'caliente desperdicia energia en '
      + 'calentamiento que no aporta beneficio '
      + 'de limpieza en la mayoria de tareas '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'El enjuague frio es igualmente '
      + 'efectivo para quitar jabon de platos, '
      + 'alimentos y manos. En un ano de '
      + 'enjuagues diarios, cambiar a frio '
      + 'evita aproximadamente 11 kg de CO2 '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)).',
  },

  install_rain_collector: {
    en:
      'Installing a rain barrel or '
      + 'collection system saves roughly '
      + '**750g of CO2** by reducing the '
      + 'energy needed to pump, treat, and '
      + 'distribute municipal water. A '
      + 'typical rain barrel captures '
      + '200-500 litres per storm, providing '
      + 'free irrigation that bypasses the '
      + 'energy-intensive water treatment '
      + 'cycle ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'This is a one-time setup that pays '
      + 'back continuously. Rain collectors '
      + 'also reduce stormwater runoff, '
      + 'protecting local waterways from '
      + 'pollution ([UN SDG 6]'
      + '(https://sdgs.un.org/goals'
      + '/goal6)).',
    ja:
      '雨水を集めて庭の水やりに使うと1回'
      + 'あたり約**15gのCO2**を節約できます。'
      + '重力式の雨水タンクは水道水の処理、'
      + 'ポンプ、配水に必要なエネルギーを回避'
      + 'できます（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '標準的なタンクは1回の降雨で約200'
      + 'リットルを貯められます。雨水は自然に'
      + '軟水で塩素も含まれておらず植物に最適'
      + 'です（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Recolectar agua de lluvia para el '
      + 'jardin ahorra unos **15g de CO2** '
      + 'por sesion de riego. Los barriles de '
      + 'lluvia por gravedad evitan la energia '
      + 'necesaria para el tratamiento, '
      + 'bombeo y distribucion del agua '
      + 'potable ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Un barril estandar captura unos 200 '
      + 'litros de un solo evento de lluvia. '
      + 'El agua de lluvia es naturalmente '
      + 'blanda y libre de cloro, ideal para '
      + 'plantas ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  water_plants_morning: {
    en:
      'Watering plants in the early morning '
      + 'saves about **10g of CO2** per '
      + 'session by reducing water waste. '
      + 'Morning watering cuts evaporation by '
      + '25-50% compared to midday, meaning '
      + 'less water needs to be drawn and '
      + 'treated ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Cooler soil also absorbs water more '
      + 'effectively, benefiting plant roots. '
      + 'This simple timing adjustment costs '
      + 'nothing and keeps your garden '
      + 'healthier ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '早朝に水やりをすると1回あたり約'
      + '**10gのCO2**を節約でき水の無駄を減ら'
      + 'せます。朝の水やりは日中と比べ蒸発量'
      + 'が25〜50%少なく必要な水の取水量と処理'
      + '量が減ります（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '涼しい土壌は水をより効果的に吸収し'
      + '根に恩恵をもたらします。このタイミング'
      + 'の調整はコストゼロで庭をより健康に'
      + '保てます（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Regar las plantas temprano en la '
      + 'manana ahorra unos **10g de CO2** '
      + 'por sesion al reducir el desperdicio '
      + 'de agua. El riego matutino reduce la '
      + 'evaporacion en un 25-50% comparado '
      + 'con el mediodia, lo que significa '
      + 'menos agua extraida y tratada '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'El suelo fresco absorbe el agua mas '
      + 'eficazmente, beneficiando las raices. '
      + 'Este simple ajuste de horario no '
      + 'cuesta nada y mantiene tu jardin mas '
      + 'saludable ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  reuse_cooking_water: {
    en:
      'Reusing cooking water for plants or '
      + 'other purposes saves about **5g of '
      + 'CO2** per use. This avoids running '
      + 'fresh mains water, which requires '
      + 'energy for treatment and pumping '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Cooled pasta or vegetable water is '
      + 'rich in nutrients that benefit garden '
      + 'soil. This zero-cost habit reduces '
      + 'total household water consumption '
      + 'and gives plants a nutritional boost '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '料理に使った水を植物などに再利用'
      + 'すると1回あたり約**5gのCO2**を節約'
      + 'できます。水道水を新たに使うのを避け、'
      + '処理やポンプに必要なエネルギーを削減'
      + 'します（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '冷ましたパスタや野菜の茹で汁は栄養が'
      + '豊富で庭の土壌に良い影響を与えます。'
      + 'この費用ゼロの習慣で家庭の総水使用量'
      + 'を減らし植物に栄養も与えられます'
      + '（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Reutilizar el agua de coccion para '
      + 'plantas u otros usos ahorra unos '
      + '**5g de CO2** por uso. Esto evita '
      + 'usar agua potable fresca que requiere '
      + 'energia para su tratamiento y bombeo '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'El agua enfriada de pasta o verduras '
      + 'es rica en nutrientes que benefician '
      + 'el suelo del jardin. Este habito sin '
      + 'costo reduce el consumo total de agua '
      + 'del hogar y da un impulso nutricional '
      + 'a las plantas ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  turn_off_tap_dishes: {
    en:
      'Turning off the tap between rinsing '
      + 'dishes saves about **25g of CO2** '
      + 'per wash session. Leaving the tap '
      + 'running while scrubbing wastes '
      + 'roughly 12 litres of treated water '
      + '([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Using a basin to collect rinse water '
      + 'is even more efficient. Over a year '
      + 'of daily dish-washing, this habit '
      + 'saves about 9 kg of CO2 and over '
      + '4,000 litres of water '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
    ja:
      '食器洗い中に蛇口を閉めると1回の洗い'
      + '物で約**25gのCO2**を節約できます。'
      + 'こすり洗いの間に流しっぱなしにすると'
      + '約12リットルの処理済み水が無駄になり'
      + 'ます（[EPA WaterSense]'
      + '(https://www.epa.gov/watersense)）。'
      + '洗い桶にすすぎ水を溜めるとさらに効率'
      + '的です。毎日の食器洗いで年間約9kgの'
      + 'CO2と4,000リットル以上の水を節約でき'
      + 'ます（[Energy Saving Trust]'
      + '(https://energysavingtrust'
      + '.org.uk/)）。',
    es:
      'Cerrar el grifo entre enjuagues al '
      + 'lavar platos ahorra unos **25g de '
      + 'CO2** por sesion de lavado. Dejar el '
      + 'grifo abierto mientras se friega '
      + 'desperdicia unos 12 litros de agua '
      + 'tratada ([EPA WaterSense]'
      + '(https://www.epa.gov/watersense)). '
      + 'Usar un recipiente para recoger el '
      + 'agua de enjuague es aun mas '
      + 'eficiente. En un ano de lavado '
      + 'diario, este habito ahorra unos 9 kg '
      + 'de CO2 y mas de 4.000 litros de agua '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)).',
  },

  shorter_bath: {
    en:
      'Taking a shorter bath or switching to '
      + 'a quick shower saves roughly **300g '
      + 'of CO2** per session. A standard bath '
      + 'uses about 80 litres of hot water '
      + 'compared to 40 litres for a five-'
      + 'minute shower ([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Halving the bath water cuts heating '
      + 'energy proportionally. If a full bath '
      + 'is needed, filling it only two-thirds '
      + 'full still provides comfort while '
      + 'significantly reducing emissions '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
    ja:
      '入浴時間を短くするかシャワーに切り'
      + '替えると1回あたり約**300gのCO2**を'
      + '削減できます。一般的な入浴は約80'
      + 'リットルの温水を使うのに対し5分の'
      + 'シャワーは約40リットルです（[Energy '
      + 'Saving Trust](https://energy'
      + 'savingtrust.org.uk/)）。湯量を半分に'
      + 'すれば加熱エネルギーも比例して減り'
      + 'ます。入浴が必要な場合でも3分の2まで'
      + 'のお湯なら快適さを保ちながら排出量を'
      + '大幅に削減できます（[DEFRA 2024]'
      + '(https://www.gov.uk/government'
      + '/publications/greenhouse-gas-reporting'
      + '-conversion-factors-2024)）。',
    es:
      'Tomar un bano mas corto o cambiar a '
      + 'una ducha rapida ahorra '
      + 'aproximadamente **300g de CO2** por '
      + 'sesion. Un bano estandar usa unos 80 '
      + 'litros de agua caliente frente a 40 '
      + 'litros de una ducha de cinco minutos '
      + '([Energy Saving Trust]'
      + '(https://energysavingtrust.org.uk/)). '
      + 'Reducir el agua del bano a la mitad '
      + 'reduce la energia de calentamiento '
      + 'proporcionalmente. Si se necesita un '
      + 'bano completo, llenarlo solo dos '
      + 'tercios ofrece comodidad reduciendo '
      + 'significativamente las emisiones '
      + '([DEFRA 2024](https://www.gov.uk'
      + '/government/publications/greenhouse'
      + '-gas-reporting-conversion-factors'
      + '-2024)).',
  },
};

module.exports = descriptions;
