/**
 * Long descriptions for eco-actions:
 * COMMUNITY, ADVOCACY, SDG-TARGETED.
 *
 * Each description is 3-5 sentences with markdown
 * formatting, bold CO2 figures, and source links.
 *
 * This is a partial file merged into the final
 * descriptions module.
 */

const descriptions = {
  // ---------------------------------------------------
  // COMMUNITY (10 actions)
  // ---------------------------------------------------
  tree_planting: {
    en:
      'A single tree absorbs roughly '
      + '**15kg of CO2 per year** through '
      + 'photosynthesis, accumulating '
      + '150-250kg over its first decade '
      + '([EPA GHG Equivalencies]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)). '
      + 'Trees also filter air pollutants, '
      + 'reduce urban heat islands, and '
      + 'provide critical habitat for '
      + 'wildlife ([UN SDG 15]'
      + '(https://sdgs.un.org/goals'
      + '/goal15)). '
      + 'Planting even one tree is a '
      + 'lasting investment in your '
      + 'community and the climate for '
      + 'decades to come.',
    ja:
      '1本の木は光合成により年間約'
      + '**15kgのCO2**を吸収し、最初の'
      + '10年間で150〜250kgを蓄積します'
      + '（[EPA温室効果ガス換算]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)）。'
      + '樹木はまた大気汚染物質を濾過し、'
      + '都市のヒートアイランドを緩和し、'
      + '野生生物の重要な生息地を提供します'
      + '（[国連SDG 15]'
      + '(https://sdgs.un.org/goals'
      + '/goal15)）。'
      + '1本の植樹でも、地域社会と気候への'
      + '長期的な投資になります。',
    es:
      'Un solo arbol absorbe aproximadamente '
      + '**15kg de CO2 al ano** mediante la '
      + 'fotosintesis, acumulando 150-250kg '
      + 'en su primera decada '
      + '([EPA Equivalencias GEI]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)). '
      + 'Los arboles tambien filtran '
      + 'contaminantes, reducen las islas de '
      + 'calor urbanas y proporcionan habitat '
      + 'para la vida silvestre '
      + '([ONU ODS 15]'
      + '(https://sdgs.un.org/goals'
      + '/goal15)). '
      + 'Plantar un arbol es una inversion '
      + 'duradera en tu comunidad y el clima.',
  },

  beach_cleanup: {
    en:
      'Beach cleanups prevent plastic waste '
      + 'from degrading into microplastics '
      + 'that contaminate marine ecosystems '
      + 'and damage ocean carbon sinks. '
      + 'Healthy oceans absorb roughly 30% '
      + 'of human-produced CO2 '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Each cleanup saves an estimated '
      + '**100g of CO2** by protecting the '
      + 'marine organisms that sequester '
      + 'carbon ([UN SDG 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)). '
      + 'Beyond carbon, removing debris '
      + 'protects sea turtles, birds, and '
      + 'fish from ingestion and '
      + 'entanglement.',
    ja:
      'ビーチクリーンアップはプラスチック'
      + 'がマイクロプラスチックに分解され、'
      + '海洋生態系を汚染するのを防ぎます。'
      + '健全な海洋は人為的CO2の約30%を吸収'
      + 'しています'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '各クリーンアップは炭素を隔離する'
      + '海洋生物を保護することで推定'
      + '**100gのCO2**を削減します'
      + '（[国連SDG 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)）。'
      + 'ゴミの除去はウミガメや鳥、魚を'
      + '誤飲や絡まりからも守ります。',
    es:
      'Las limpiezas de playas evitan que '
      + 'el plastico se degrade en '
      + 'microplasticos que contaminan los '
      + 'ecosistemas marinos y danan los '
      + 'sumideros de carbono oceanicos. '
      + 'Los oceanos sanos absorben el 30% '
      + 'del CO2 humano '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Cada limpieza ahorra unas '
      + '**100g de CO2** al proteger los '
      + 'organismos marinos que secuestran '
      + 'carbono ([ONU ODS 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)). '
      + 'Ademas, protege tortugas, aves y '
      + 'peces de la ingestion de residuos.',
  },

  farmers_market: {
    en:
      'Buying at a farmers market saves an '
      + 'estimated **300g of CO2 per trip** '
      + 'because local food travels roughly '
      + '80km versus 2,400km for typical '
      + 'supermarket produce. '
      + 'Shorter supply chains mean less '
      + 'refrigerated transport, less '
      + 'packaging, and fresher food '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Shopping locally also supports '
      + 'small-scale farmers and strengthens '
      + 'regional food security '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Every market visit is a vote for a '
      + 'more sustainable food system.',
    ja:
      'ファーマーズマーケットでの買い物は'
      + '1回あたり推定**300gのCO2**を削減'
      + 'します。地元の食品は約80kmしか輸送'
      + 'されませんが、一般的なスーパーの'
      + '農産物は約2,400km移動します。'
      + '短いサプライチェーンは冷蔵輸送、'
      + '包装、食品ロスの削減を意味します'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + '地元で買い物することで小規模農家を'
      + '支援し、地域の食料安全保障を強化'
      + 'します（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。',
    es:
      'Comprar en un mercado de '
      + 'agricultores ahorra unas '
      + '**300g de CO2 por visita** porque '
      + 'los alimentos locales viajan unos '
      + '80km frente a 2.400km de los '
      + 'productos tipicos de supermercado. '
      + 'Las cadenas de suministro cortas '
      + 'implican menos transporte '
      + 'refrigerado y menos embalaje '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Comprar localmente tambien apoya a '
      + 'los pequenos agricultores y fortalece'
      + ' la seguridad alimentaria regional '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)).',
  },

  share_sustainability_tip: {
    en:
      'Sharing sustainability tips costs '
      + 'nothing but can multiply your impact '
      + 'exponentially. Research shows that '
      + 'eco-friendly habits are socially '
      + 'contagious and spread through '
      + 'personal networks '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'When you share a practical tip, you '
      + 'lower the barrier for others to act '
      + 'on climate ([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'One conversation can inspire a '
      + 'chain of behavior change that far '
      + 'exceeds any single action.',
    ja:
      'サステナビリティのヒントを共有する'
      + 'ことはコストゼロで、影響を指数関数'
      + '的に拡大できます。研究によると、'
      + 'エコフレンドリーな習慣は社会的に'
      + '伝染し、個人ネットワークを通じて'
      + '広がります'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '実用的なヒントを共有することで、'
      + '他の人が気候変動対策に取り組む'
      + 'ハードルを下げられます'
      + '（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + '1つの会話が、個別の行動をはるかに'
      + '超える行動変容の連鎖を生みます。',
    es:
      'Compartir consejos de sostenibilidad '
      + 'no cuesta nada pero puede multiplicar'
      + ' tu impacto exponencialmente. Las '
      + 'investigaciones muestran que los '
      + 'habitos ecologicos son socialmente '
      + 'contagiosos '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Cuando compartes un consejo practico,'
      + ' reduces la barrera para que otros '
      + 'actuen por el clima '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Una conversacion puede inspirar una '
      + 'cadena de cambio de comportamiento.',
  },

  community_garden: {
    en:
      'Participating in a community garden '
      + 'saves an estimated **200g of CO2** '
      + 'per session by reducing food miles '
      + 'and supporting local composting. '
      + 'Community gardens also build social '
      + 'cohesion, provide fresh produce to '
      + 'food-insecure neighborhoods, and '
      + 'increase urban green space '
      + '([UN SDG 11]'
      + '(https://sdgs.un.org/goals'
      + '/goal11)). '
      + 'Gardens act as carbon sinks and '
      + 'help manage stormwater runoff '
      + '([EPA GHG Equivalencies]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)). '
      + 'Growing food together fosters '
      + 'environmental stewardship across '
      + 'generations.',
    ja:
      'コミュニティガーデンへの参加は、'
      + 'フードマイルの削減と地域の堆肥化'
      + '支援により1回あたり推定**200gの'
      + 'CO2**を削減します。'
      + 'コミュニティガーデンは社会的結束を'
      + '築き、食料不安のある地域に新鮮な'
      + '農産物を提供し、都市の緑地を増やし'
      + 'ます（[国連SDG 11]'
      + '(https://sdgs.un.org/goals'
      + '/goal11)）。'
      + '菜園は炭素吸収源として機能し、'
      + '雨水流出の管理にも役立ちます'
      + '（[EPA温室効果ガス換算]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)）。',
    es:
      'Participar en un huerto comunitario '
      + 'ahorra unas **200g de CO2** por '
      + 'sesion al reducir los kilometros '
      + 'alimentarios y apoyar el compostaje '
      + 'local. Los huertos comunitarios '
      + 'fortalecen la cohesion social y '
      + 'proporcionan productos frescos '
      + '([ONU ODS 11]'
      + '(https://sdgs.un.org/goals'
      + '/goal11)). '
      + 'Funcionan como sumideros de carbono '
      + 'y ayudan a gestionar la escorrentia '
      + '([EPA Equivalencias GEI]'
      + '(https://www.epa.gov/energy'
      + '/greenhouse-gas-equivalencies'
      + '-calculator)). '
      + 'Cultivar juntos fomenta la '
      + 'responsabilidad ambiental.',
  },

  volunteer_environment: {
    en:
      'Volunteering for an environmental '
      + 'cause saves an estimated **100g of '
      + 'CO2** per session through direct '
      + 'ecological restoration work. '
      + 'Collective action amplifies impact '
      + 'far beyond what any individual can '
      + 'achieve alone '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Volunteers plant trees, restore '
      + 'wetlands, monitor wildlife, and '
      + 'educate communities '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Your time and effort create ripple '
      + 'effects that strengthen local '
      + 'environmental resilience.',
    ja:
      '環境ボランティアは直接的な生態系'
      + '復元作業を通じて1回あたり推定'
      + '**100gのCO2**を削減します。'
      + '集団行動は個人が単独で達成できる'
      + 'ものをはるかに超える影響を生み出し'
      + 'ます（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + 'ボランティアは植樹、湿地の復元、'
      + '野生生物の監視、地域教育を行います'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + 'あなたの時間と労力が地域の環境回復'
      + '力を強化する波及効果を生みます。',
    es:
      'El voluntariado ambiental ahorra '
      + 'unas **100g de CO2** por sesion '
      + 'mediante trabajo directo de '
      + 'restauracion ecologica. La accion '
      + 'colectiva amplifica el impacto mucho '
      + 'mas alla de lo que cualquier '
      + 'individuo puede lograr solo '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Los voluntarios plantan arboles, '
      + 'restauran humedales y educan '
      + 'comunidades '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Tu tiempo crea efectos en cadena '
      + 'que fortalecen la resiliencia '
      + 'ambiental local.',
  },

  teach_child_eco: {
    en:
      'Teaching a child about sustainability '
      + 'creates lifelong eco-conscious '
      + 'habits that compound over decades. '
      + 'Environmental education in childhood '
      + 'is one of the strongest predictors '
      + 'of adult pro-environmental behavior '
      + '([UN SDG 4]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)). '
      + 'Children who learn about ecosystems '
      + 'early become advocates who influence '
      + 'their families and peers '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'The next generation holds the key '
      + 'to long-term climate solutions.',
    ja:
      '子供にサステナビリティを教えること'
      + 'は、何十年にもわたって複利的に'
      + '増える生涯にわたるエコ意識の習慣を'
      + '作ります。幼少期の環境教育は、成人'
      + 'の環境配慮行動の最も強い予測因子の'
      + '一つです（[国連SDG 4]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)）。'
      + '生態系について早くから学んだ子供は'
      + '家族や仲間に影響を与える提唱者に'
      + 'なります'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '次の世代が長期的な気候ソリューション'
      + 'の鍵を握っています。',
    es:
      'Ensenar a un nino sobre '
      + 'sostenibilidad crea habitos '
      + 'ecologicos de por vida que se '
      + 'acumulan durante decadas. La '
      + 'educacion ambiental infantil es uno '
      + 'de los predictores mas fuertes del '
      + 'comportamiento proambiental adulto '
      + '([ONU ODS 4]'
      + '(https://sdgs.un.org/goals'
      + '/goal4)). '
      + 'Los ninos que aprenden sobre '
      + 'ecosistemas se convierten en '
      + 'defensores que influyen en familias '
      + 'y companeros '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'La proxima generacion tiene la '
      + 'clave de las soluciones climaticas.',
  },

  support_eco_business: {
    en:
      'Supporting an eco-friendly business '
      + 'saves an estimated **200g of CO2** '
      + 'per purchase by directing demand '
      + 'toward sustainable production '
      + 'methods. Consumer spending is a '
      + 'powerful market signal that drives '
      + 'companies to adopt greener practices '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Sustainable businesses often use '
      + 'renewable energy, ethical sourcing, '
      + 'and circular design principles '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Every purchase is a vote for the '
      + 'kind of economy you want to see.',
    ja:
      'エコフレンドリーなビジネスを支援'
      + 'すると、持続可能な生産方法への需要'
      + 'を向けることで1回の購入あたり推定'
      + '**200gのCO2**を削減します。'
      + '消費者支出は企業にグリーンな慣行を'
      + '採用させる強力な市場シグナルです'
      + '（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。'
      + '持続可能な企業は再生可能エネルギー、'
      + '倫理的な調達、循環型設計原則を'
      + '使用することが多いです'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + 'すべての購入は、望む経済への一票'
      + 'です。',
    es:
      'Apoyar un negocio ecologico ahorra '
      + 'unas **200g de CO2** por compra al '
      + 'dirigir la demanda hacia metodos de '
      + 'produccion sostenibles. El gasto '
      + 'del consumidor es una senal de '
      + 'mercado poderosa que impulsa a las '
      + 'empresas a adoptar practicas verdes '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Los negocios sostenibles suelen usar '
      + 'energia renovable y diseno circular '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Cada compra es un voto por la '
      + 'economia que quieres ver.',
  },

  organize_swap: {
    en:
      'Organizing a clothing or item swap '
      + 'prevents an estimated **1,000g of '
      + 'CO2** by keeping usable goods out '
      + 'of landfills. A single new garment '
      + 'generates roughly 14kg of CO2 '
      + 'during production, so each swapped '
      + 'item avoids significant emissions '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Swaps promote a circular economy '
      + 'where resources are reused rather '
      + 'than discarded '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'They also build community and make '
      + 'sustainable living fun and '
      + 'accessible.',
    ja:
      '衣類やアイテムのスワップを企画する'
      + 'ことで、使用可能な物を埋立地から'
      + '守り、推定**1,000gのCO2**を削減'
      + 'します。新しい衣服1着の生産では約'
      + '14kgのCO2が発生するため、交換される'
      + '各アイテムは大幅な排出を回避します'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + 'スワップは資源を廃棄するのではなく'
      + '再利用する循環型経済を促進します'
      + '（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。'
      + 'コミュニティを築き、持続可能な生活'
      + 'を楽しく身近にします。',
    es:
      'Organizar un intercambio de ropa o '
      + 'articulos evita unas **1.000g de '
      + 'CO2** al mantener bienes utiles '
      + 'fuera de los vertederos. Una prenda '
      + 'nueva genera unos 14kg de CO2 '
      + 'durante su produccion, asi que cada '
      + 'articulo intercambiado evita '
      + 'emisiones significativas '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Los intercambios promueven una '
      + 'economia circular donde los recursos '
      + 'se reutilizan '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Tambien crean comunidad y hacen '
      + 'la vida sostenible accesible.',
  },

  pick_up_litter: {
    en:
      'Picking up litter prevents plastic '
      + 'and other waste from entering '
      + 'waterways that lead to the ocean. '
      + 'Oceans are the planet\'s largest '
      + 'carbon sink, absorbing about 30% of '
      + 'human CO2 emissions, and plastic '
      + 'pollution threatens this capacity '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Even small cleanup efforts protect '
      + 'local ecosystems and wildlife '
      + '([UN SDG 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)). '
      + 'Visible action also inspires others '
      + 'to care for shared spaces and reduce '
      + 'their own waste.',
    ja:
      'ゴミ拾いはプラスチックやその他の'
      + '廃棄物が海につながる水路に入るのを'
      + '防ぎます。海洋は地球最大の炭素吸収'
      + '源で人為的CO2排出の約30%を吸収して'
      + 'おり、プラスチック汚染はこの能力を'
      + '脅かしています'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '小さなクリーンアップ活動でも地域の'
      + '生態系と野生生物を保護します'
      + '（[国連SDG 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)）。'
      + '目に見える行動は他の人にも共有空間'
      + 'を大切にし、ゴミを減らすよう促し'
      + 'ます。',
    es:
      'Recoger basura evita que plasticos '
      + 'y otros residuos lleguen a las vias '
      + 'fluviales que desembocan en el '
      + 'oceano. Los oceanos son el mayor '
      + 'sumidero de carbono del planeta, '
      + 'absorbiendo el 30% del CO2 humano, '
      + 'y la contaminacion plastica amenaza '
      + 'esta capacidad '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Incluso pequenos esfuerzos protegen '
      + 'los ecosistemas locales '
      + '([ONU ODS 14]'
      + '(https://sdgs.un.org/goals'
      + '/goal14)). '
      + 'La accion visible inspira a otros '
      + 'a cuidar los espacios compartidos.',
  },

  // ---------------------------------------------------
  // ADVOCACY (8 actions)
  // ---------------------------------------------------
  sign_petition: {
    en:
      'Signing an environmental petition '
      + 'adds your voice to collective '
      + 'demands for systemic change. Policy '
      + 'reform has orders of magnitude more '
      + 'impact on emissions than any single '
      + 'individual action '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Petitions that reach critical mass '
      + 'have driven landmark legislation '
      + 'like the EU Green Deal '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Your signature costs nothing but '
      + 'contributes to the democratic '
      + 'pressure that shapes climate policy.',
    ja:
      '環境署名に参加することで、体制的な'
      + '変革を求める集団的な声にあなたの声'
      + 'を加えます。政策改革は個人の行動'
      + 'よりも桁違いに大きな排出削減効果が'
      + 'あります'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + 'クリティカルマスに達した署名はEU'
      + 'グリーンディールなどの画期的な法律'
      + 'を推進してきました'
      + '（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + 'あなたの署名は無料ですが、気候政策'
      + 'を形作る民主的な圧力に貢献します。',
    es:
      'Firmar una peticion ambiental suma '
      + 'tu voz a las demandas colectivas de '
      + 'cambio sistemico. La reforma '
      + 'politica tiene ordenes de magnitud '
      + 'mas impacto en las emisiones que '
      + 'cualquier accion individual '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Las peticiones que alcanzan masa '
      + 'critica han impulsado leyes como '
      + 'el Pacto Verde de la UE '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Tu firma no cuesta nada pero '
      + 'contribuye a la presion democratica '
      + 'que moldea la politica climatica.',
  },

  contact_representative: {
    en:
      'Contacting your elected '
      + 'representative is the most effective '
      + 'form of political advocacy for '
      + 'climate action. Representatives '
      + 'track constituent contacts and '
      + 'prioritize issues accordingly '
      + '([UN SDG 16]'
      + '(https://sdgs.un.org/goals'
      + '/goal16)). '
      + 'A single thoughtful message can '
      + 'influence votes on critical '
      + 'environmental legislation '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Systemic policy change remains the '
      + 'most powerful lever for reducing '
      + 'emissions at scale.',
    ja:
      '選出された代表者に連絡することは、'
      + '気候行動のための最も効果的な政治的'
      + '提唱形態です。代表者は有権者からの'
      + '連絡を記録し、それに応じて問題の'
      + '優先順位を決定します'
      + '（[国連SDG 16]'
      + '(https://sdgs.un.org/goals'
      + '/goal16)）。'
      + '1つの思慮深いメッセージが重要な環境'
      + '法案の投票に影響を与えることができ'
      + 'ます（[IPCC]'
      + '(https://www.ipcc.ch/)）。'
      + '体制的な政策変更は、排出削減の最も'
      + '強力な手段であり続けています。',
    es:
      'Contactar a tu representante electo '
      + 'es la forma mas efectiva de '
      + 'advocacia politica por la accion '
      + 'climatica. Los representantes '
      + 'registran los contactos de sus '
      + 'electores y priorizan los temas '
      + 'en consecuencia '
      + '([ONU ODS 16]'
      + '(https://sdgs.un.org/goals'
      + '/goal16)). '
      + 'Un solo mensaje reflexivo puede '
      + 'influir en votos sobre legislacion '
      + 'ambiental critica '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'El cambio politico sistemico sigue '
      + 'siendo la palanca mas poderosa para '
      + 'reducir emisiones a escala.',
  },

  share_eco_content: {
    en:
      'Sharing eco-friendly content on '
      + 'social media amplifies environmental '
      + 'awareness to your entire network. '
      + 'Visible sustainable behavior on '
      + 'social platforms influences peers '
      + 'and normalizes green choices '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Studies show that social influence '
      + 'is a top driver of behavior change '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'A single shared post can reach '
      + 'hundreds and inspire real-world '
      + 'action beyond the screen.',
    ja:
      'エコフレンドリーなコンテンツをSNSで'
      + '共有することで、ネットワーク全体に'
      + '環境意識を拡大します。ソーシャル'
      + 'プラットフォーム上の目に見える持続'
      + '可能な行動は仲間に影響を与え、'
      + 'グリーンな選択を普通にします'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '研究により、社会的影響は行動変容の'
      + '最大の推進力の一つであることが示さ'
      + 'れています（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + '1つの投稿が何百人にも届き、画面の'
      + '向こうの現実の行動を促します。',
    es:
      'Compartir contenido ecologico en '
      + 'redes sociales amplifica la '
      + 'conciencia ambiental a toda tu red. '
      + 'El comportamiento sostenible visible '
      + 'en plataformas sociales influye en '
      + 'los companeros y normaliza las '
      + 'elecciones verdes '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Los estudios muestran que la '
      + 'influencia social es un motor clave '
      + 'del cambio de comportamiento '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Una publicacion puede llegar a '
      + 'cientos e inspirar accion real.',
  },

  attend_climate_event: {
    en:
      'Attending a climate rally, march, or '
      + 'event adds to the mass mobilization '
      + 'that drives policy change. The Paris '
      + 'Agreement was shaped significantly '
      + 'by sustained public pressure '
      + '([UN SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'Large turnout at climate events '
      + 'signals to lawmakers that voters '
      + 'prioritize environmental action '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Being physically present strengthens '
      + 'solidarity and amplifies the '
      + 'collective voice for change.',
    ja:
      '気候集会やイベントに参加することで、'
      + '政策変更を推進する大衆動員に加わり'
      + 'ます。パリ協定は持続的な市民の圧力'
      + 'によって大きく形作られました'
      + '（[国連SDG 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)）。'
      + '気候イベントへの大規模な参加は、'
      + '有権者が環境行動を優先することを'
      + '立法者に示すシグナルです'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '物理的に存在することで連帯が強化'
      + 'され、変革のための集団的な声が'
      + '増幅されます。',
    es:
      'Asistir a una marcha o evento '
      + 'climatico se suma a la movilizacion '
      + 'masiva que impulsa cambios '
      + 'politicos. El Acuerdo de Paris fue '
      + 'moldeado significativamente por la '
      + 'presion publica sostenida '
      + '([ONU ODS 13]'
      + '(https://sdgs.un.org/goals'
      + '/goal13)). '
      + 'La gran asistencia a eventos '
      + 'climaticos indica a los legisladores '
      + 'que los votantes priorizan la accion '
      + 'ambiental '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Estar presente fortalece la '
      + 'solidaridad y amplifica la voz '
      + 'colectiva por el cambio.',
  },

  support_green_policy: {
    en:
      'Supporting renewable energy and '
      + 'green policy initiatives could '
      + 'eliminate gigatons of CO2 emissions '
      + 'annually at the systemic level. '
      + 'Policy frameworks like carbon '
      + 'pricing and clean energy standards '
      + 'are the most scalable tools for '
      + 'decarbonization '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Public support gives lawmakers the '
      + 'mandate to pass ambitious climate '
      + 'legislation ([UN SDG 7]'
      + '(https://sdgs.un.org/goals'
      + '/goal7)). '
      + 'Voicing support for green policy is '
      + 'one of the highest-leverage actions '
      + 'any citizen can take.',
    ja:
      '再生可能エネルギーやグリーン政策の'
      + '取り組みを支援することで、体制的'
      + 'レベルで年間ギガトン単位のCO2排出を'
      + '削減できる可能性があります。炭素'
      + '価格付けやクリーンエネルギー基準'
      + 'などの政策枠組みは脱炭素化の最も'
      + '拡張性のあるツールです'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + '市民の支持は立法者に野心的な気候'
      + '法案を可決する権限を与えます'
      + '（[国連SDG 7]'
      + '(https://sdgs.un.org/goals'
      + '/goal7)）。'
      + 'グリーン政策への支持表明は、市民が'
      + 'できる最も影響力の大きい行動の一つ'
      + 'です。',
    es:
      'Apoyar las politicas de energia '
      + 'renovable e iniciativas verdes '
      + 'podria eliminar gigatoneladas de '
      + 'emisiones de CO2 anualmente a nivel '
      + 'sistemico. Marcos politicos como el '
      + 'precio del carbono son las '
      + 'herramientas mas escalables para la '
      + 'descarbonizacion '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'El apoyo publico da a los '
      + 'legisladores el mandato para aprobar '
      + 'leyes climaticas ambiciosas '
      + '([ONU ODS 7]'
      + '(https://sdgs.un.org/goals'
      + '/goal7)). '
      + 'Expresar apoyo a la politica verde '
      + 'es una de las acciones de mayor '
      + 'impacto que un ciudadano puede '
      + 'tomar.',
  },

  write_eco_review: {
    en:
      'Writing a review that highlights a '
      + 'company\'s sustainability practices '
      + 'influences other consumers and '
      + 'rewards eco-conscious businesses. '
      + 'Consumer feedback drives market '
      + 'transformation by making green '
      + 'performance visible to buyers '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Positive reviews for sustainable '
      + 'products create a feedback loop '
      + 'that incentivizes better practices '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Your words help others make informed '
      + 'and planet-friendly choices.',
    ja:
      '企業のサステナビリティ実践を強調'
      + 'するレビューを書くことで、他の消費'
      + '者に影響を与え、エコ意識の高い企業'
      + 'に報いることができます。消費者の'
      + 'フィードバックは、グリーンな実績を'
      + '購入者に見えるようにすることで市場'
      + '変革を推進します（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。'
      + '持続可能な製品への肯定的なレビューは'
      + 'より良い慣行を促すフィードバック'
      + 'ループを作ります'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + 'あなたの言葉が他の人の情報に基づいた'
      + '環境に優しい選択を助けます。',
    es:
      'Escribir una resena que destaque las '
      + 'practicas de sostenibilidad de una '
      + 'empresa influye en otros consumidores'
      + ' y recompensa a los negocios '
      + 'ecoconscientes. La retroalimentacion'
      + ' del consumidor impulsa la '
      + 'transformacion del mercado '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Las resenas positivas de productos '
      + 'sostenibles crean un ciclo de '
      + 'retroalimentacion que incentiva '
      + 'mejores practicas '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Tus palabras ayudan a otros a tomar '
      + 'decisiones informadas y ecologicas.',
  },

  join_eco_group: {
    en:
      'Joining an environmental group '
      + 'amplifies your voice through '
      + 'collective action and organized '
      + 'advocacy. Groups coordinate '
      + 'campaigns, pool resources, and '
      + 'engage decision-makers far more '
      + 'effectively than individuals '
      + '([UN SDG 17]'
      + '(https://sdgs.un.org/goals'
      + '/goal17)). '
      + 'Membership in environmental '
      + 'organizations correlates with higher '
      + 'civic engagement overall '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Together, groups create the critical '
      + 'mass needed to shift policies and '
      + 'cultural norms.',
    ja:
      '環境グループに参加することで、集団'
      + '行動と組織的な提唱を通じてあなたの'
      + '声が増幅されます。グループはキャン'
      + 'ペーンを調整し、リソースをプール'
      + 'し、個人よりもはるかに効果的に意思'
      + '決定者に関与します'
      + '（[国連SDG 17]'
      + '(https://sdgs.un.org/goals'
      + '/goal17)）。'
      + '環境団体への加入は全体的な市民参加'
      + 'の増加と相関しています'
      + '（[IPCC](https://www.ipcc.ch/)）。'
      + 'グループが一体となり、政策と文化的'
      + '規範を変えるクリティカルマスを'
      + '生み出します。',
    es:
      'Unirse a un grupo ambiental amplifica'
      + ' tu voz a traves de la accion '
      + 'colectiva y la advocacia organizada. '
      + 'Los grupos coordinan campanas, '
      + 'agrupan recursos e involucran a los '
      + 'tomadores de decisiones mucho mas '
      + 'efectivamente que los individuos '
      + '([ONU ODS 17]'
      + '(https://sdgs.un.org/goals'
      + '/goal17)). '
      + 'La membresia en organizaciones '
      + 'ambientales se correlaciona con '
      + 'mayor participacion civica '
      + '([IPCC](https://www.ipcc.ch/)). '
      + 'Juntos, los grupos crean la masa '
      + 'critica necesaria para cambiar '
      + 'politicas y normas culturales.',
  },

  request_green_option: {
    en:
      'Requesting a green option from a '
      + 'business signals consumer demand '
      + 'for sustainable alternatives. When '
      + 'companies hear directly from '
      + 'customers, they are more likely to '
      + 'invest in eco-friendly options '
      + '([UN SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'This demand-side pressure has driven '
      + 'companies to adopt sustainable '
      + 'packaging, plant-based menus, and '
      + 'renewable energy '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Every request plants a seed that '
      + 'can grow into lasting corporate '
      + 'change.',
    ja:
      '企業にグリーンオプションを要求する'
      + 'ことは、持続可能な代替品への消費者'
      + '需要を示すシグナルです。企業は顧客'
      + 'から直接要望を聞くと、エコフレンド'
      + 'リーな選択肢に投資する可能性が高く'
      + 'なります（[国連SDG 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)）。'
      + 'この需要側の圧力により、企業は持続'
      + '可能な包装、植物由来メニュー、再生'
      + '可能エネルギーを採用してきました'
      + '（[WRAP UK]'
      + '(https://wrap.org.uk/)）。'
      + 'すべての要求が、持続的な企業変革に'
      + '成長する種を蒔きます。',
    es:
      'Solicitar una opcion verde a una '
      + 'empresa indica la demanda del '
      + 'consumidor por alternativas '
      + 'sostenibles. Cuando las empresas '
      + 'escuchan directamente de los '
      + 'clientes, es mas probable que '
      + 'inviertan en opciones ecologicas '
      + '([ONU ODS 12]'
      + '(https://sdgs.un.org/goals'
      + '/goal12)). '
      + 'Esta presion del lado de la demanda '
      + 'ha impulsado embalajes sostenibles, '
      + 'menus vegetales y energia renovable '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Cada solicitud planta una semilla '
      + 'que puede convertirse en un cambio '
      + 'corporativo duradero.',
  },

  // ---------------------------------------------------
  // SDG-TARGETED (5 actions)
  // ---------------------------------------------------
  buy_fair_trade: {
    en:
      'Fair Trade certification ensures '
      + 'producers in developing countries '
      + 'receive a guaranteed minimum price '
      + 'above market rates. Research from '
      + 'Cote d\'Ivoire shows Fair Trade '
      + 'increased household consumption by '
      + '**13.6%** for poor farmers '
      + '([Fairtrade Impact]'
      + '(https://www.fairtrade.net/en'
      + '/why-fairtrade/impact)). '
      + 'Since 2016, Fair Trade farmers have '
      + 'earned over **$1 billion** in '
      + 'premiums for community development '
      + '([Fairtrade Smallholders]'
      + '(https://www.fairtrade.net/us-en'
      + '/why-fairtrade/why-we-do-it'
      + '/smallholder-farmers.html)). '
      + 'Choosing Fair Trade also supports '
      + 'climate-resilient farming practices '
      + 'like agroforestry and crop rotation.',
    ja:
      'フェアトレード認証は、途上国の生産者が'
      + '市場価格を上回る最低保証価格を受け取る'
      + 'ことを保証します。コートジボワールの'
      + '研究では、フェアトレードにより貧困層の'
      + '家計消費が**13.6%増加**しました'
      + '（[フェアトレード影響]'
      + '(https://www.fairtrade.net/en'
      + '/why-fairtrade/impact)）。'
      + '2016年以降、フェアトレード農家は'
      + 'コミュニティ開発のために**10億ドル以上'
      + '**のプレミアムを獲得しています'
      + '（[フェアトレード小規模農家]'
      + '(https://www.fairtrade.net/us-en'
      + '/why-fairtrade/why-we-do-it'
      + '/smallholder-farmers.html)）。'
      + 'フェアトレードは農林業や輪作など気候に'
      + '強い農業も支援しています。',
    es:
      'La certificacion de comercio justo '
      + 'garantiza que los productores de '
      + 'paises en desarrollo reciban un '
      + 'precio minimo garantizado. Una '
      + 'investigacion en Costa de Marfil '
      + 'muestra que el comercio justo '
      + 'aumento el consumo de los hogares '
      + 'pobres un **13,6%** '
      + '([Impacto Fairtrade]'
      + '(https://www.fairtrade.net/en'
      + '/why-fairtrade/impact)). '
      + 'Desde 2016, los agricultores han '
      + 'ganado mas de **$1,000 millones** en '
      + 'primas para desarrollo comunitario '
      + '([Fairtrade Pequenos Productores]'
      + '(https://www.fairtrade.net/us-en'
      + '/why-fairtrade/why-we-do-it'
      + '/smallholder-farmers.html)). '
      + 'Elegir comercio justo tambien apoya '
      + 'practicas agricolas resilientes al '
      + 'clima.',
  },

  fund_micro_loan: {
    en:
      'Micro-lending channels capital '
      + 'directly to entrepreneurs excluded '
      + 'from traditional banking. Kiva '
      + 'reports a **96.3% repayment rate** '
      + 'across $1.68 billion in loans to '
      + '4.1 million borrowers in 77 '
      + 'countries, with **89% reporting '
      + 'improved quality of life** '
      + '([Kiva Impact]'
      + '(https://www.kiva.org/impact)). '
      + 'Because loans are repaid, a single '
      + '$25 contribution can fund multiple '
      + 'entrepreneurs over time. Randomized '
      + 'trials show microfinance can '
      + 'increase incomes by up to 46% and '
      + 'decrease poverty by 17%.',
    ja:
      'マイクロレンディングは、従来の銀行から'
      + '排除された起業家に直接資本を届けます。'
      + 'Kivaは77カ国の410万人の借り手に'
      + '16.8億ドルの融資で**96.3%の返済率**'
      + 'を報告しており、**89%が生活の質の'
      + '向上**を報告しています'
      + '（[Kivaインパクト]'
      + '(https://www.kiva.org/impact)）。'
      + '融資は返済されるため、1回の25ドルの'
      + '出資で複数の起業家を支援できます。'
      + '無作為化試験では、マイクロファイナンス'
      + 'が所得を最大46%増加させ、貧困を17%'
      + '削減できることが示されています。',
    es:
      'Los microprestamos canalizan capital '
      + 'directamente a emprendedores '
      + 'excluidos de la banca tradicional. '
      + 'Kiva reporta una **tasa de '
      + 'devolucion del 96,3%** en $1.680 '
      + 'millones prestados a 4,1 millones '
      + 'de prestatarios en 77 paises, con '
      + '**89% reportando mejor calidad de '
      + 'vida** ([Impacto Kiva]'
      + '(https://www.kiva.org/impact)). '
      + 'Como los prestamos se devuelven, una '
      + 'contribucion de $25 puede financiar '
      + 'multiples emprendedores. Ensayos '
      + 'aleatorizados muestran que las '
      + 'microfinanzas pueden aumentar los '
      + 'ingresos hasta un 46%.',
  },

  support_women_owned_business: {
    en:
      'Women-owned businesses make up 39% '
      + 'of all US businesses but receive '
      + 'only **1% of corporate procurement '
      + 'spending** ([UN Women]'
      + '(https://www.unwomen.org/en/what-we'
      + '-do/economic-empowerment)). '
      + 'Women reinvest up to **90% of '
      + 'income** back into their families '
      + 'and communities, compared to 30-40% '
      + 'for men. Organizations with more '
      + 'women managers reduce carbon '
      + 'emissions by approximately **5%** '
      + '([WEF 2022](https://www.weforum.org'
      + '/stories/2022/06/women-organizations'
      + '-reduce-greenhouse-gas-emissions/)). '
      + 'Supporting women-owned businesses '
      + 'drives both gender equality and '
      + 'climate progress.',
    ja:
      '女性が経営する企業はアメリカの全企業の'
      + '39%を占めますが、企業調達の**わずか'
      + '1%**しか受けていません（[UN Women]'
      + '(https://www.unwomen.org/en/what-we'
      + '-do/economic-empowerment)）。'
      + '女性は収入の最大**90%**を家族や'
      + 'コミュニティに再投資します。女性管理職'
      + 'が多い組織は炭素排出を約**5%削減**'
      + 'します（[WEF 2022]'
      + '(https://www.weforum.org/stories'
      + '/2022/06/women-organizations-reduce'
      + '-greenhouse-gas-emissions/)）。'
      + '女性経営のビジネスを支援することは、'
      + 'ジェンダー平等と気候対策の両方を'
      + '推進します。',
    es:
      'Los negocios de mujeres representan '
      + 'el 39% de las empresas en EEUU pero '
      + 'reciben solo el **1% del gasto de '
      + 'adquisiciones corporativas** '
      + '([ONU Mujeres](https://www.unwomen'
      + '.org/en/what-we-do/economic'
      + '-empowerment)). '
      + 'Las mujeres reinvierten hasta el '
      + '**90% de sus ingresos** en sus '
      + 'familias y comunidades. Las '
      + 'organizaciones con mas mujeres '
      + 'gerentes reducen emisiones de '
      + 'carbono aproximadamente un **5%** '
      + '([WEF 2022](https://www.weforum.org'
      + '/stories/2022/06/women-organizations'
      + '-reduce-greenhouse-gas-emissions/)). '
      + 'Apoyar negocios de mujeres impulsa '
      + 'tanto la igualdad de genero como el '
      + 'progreso climatico.',
  },

  share_domestic_work: {
    en:
      'SDG Target 5.4 calls for shared '
      + 'responsibility in household work. '
      + 'Women globally spend **2.5 times '
      + 'more hours** on unpaid care and '
      + 'domestic work than men '
      + '([UN Women](https://www.unwomen.org'
      + '/en/news/in-focus/csw61'
      + '/redistribute-unpaid-work)). '
      + 'Only **6% of couples** share '
      + 'housework equally. Climate change '
      + 'intensifies this burden through '
      + 'longer walks for water and fuel '
      + '([UN Women Climate-Care Nexus]'
      + '(https://www.unwomen.org/en'
      + '/digital-library/publications/2023'
      + '/11/working-paper-the-climate-care'
      + '-nexus)). '
      + 'Sharing domestic work frees time '
      + 'for education, employment, and '
      + 'leadership.',
    ja:
      'SDGターゲット5.4は家事の共同責任を'
      + '求めています。世界的に女性は男性の'
      + '**2.5倍**の時間を無償のケア・家事労働'
      + 'に費やしています（[UN Women]'
      + '(https://www.unwomen.org/en/news'
      + '/in-focus/csw61/redistribute'
      + '-unpaid-work)）。'
      + '家事を平等に分担しているカップルは'
      + 'わずか**6%**です。気候変動は水や燃料'
      + 'の確保により、この負担をさらに悪化'
      + 'させています（[UN Women気候ケア]'
      + '(https://www.unwomen.org/en'
      + '/digital-library/publications/2023'
      + '/11/working-paper-the-climate-care'
      + '-nexus)）。'
      + '家事の分担は教育、雇用、リーダーシップ'
      + 'のための時間を生み出します。',
    es:
      'La Meta 5.4 del ODS pide '
      + 'responsabilidad compartida en el '
      + 'trabajo domestico. Las mujeres '
      + 'dedican **2,5 veces mas horas** al '
      + 'trabajo domestico y de cuidado no '
      + 'remunerado que los hombres '
      + '([ONU Mujeres](https://www.unwomen'
      + '.org/en/news/in-focus/csw61'
      + '/redistribute-unpaid-work)). '
      + 'Solo el **6% de las parejas** '
      + 'comparten las tareas del hogar por '
      + 'igual. El cambio climatico '
      + 'intensifica esta carga por mayores '
      + 'distancias para agua y combustible '
      + '([ONU Mujeres Nexo Clima-Cuidado]'
      + '(https://www.unwomen.org/en'
      + '/digital-library/publications/2023'
      + '/11/working-paper-the-climate-care'
      + '-nexus)). '
      + 'Compartir las tareas libera tiempo '
      + 'para educacion, empleo y liderazgo.',
  },

  support_community_business: {
    en:
      'Directing purchases to minority-owned '
      + 'and underrepresented community '
      + 'businesses builds economic equity. '
      + 'If minority businesses reached '
      + 'population parity, **757,000 new '
      + 'businesses** could emerge with 6.3 '
      + 'million jobs and $824 billion in '
      + 'revenue ([Brookings]'
      + '(https://www.brookings.edu/articles'
      + '/reaping-the-unrealized-gains-of'
      + '-black-businesses/)). '
      + 'Minority-owned businesses already '
      + 'generate nearly **$2 trillion in '
      + 'annual revenue** ([SCORE]'
      + '(https://www.score.org)). '
      + 'Conscious consumer choice is one of '
      + 'the most direct individual levers '
      + 'for reducing economic inequality.',
    ja:
      'マイノリティや地域のビジネスへの購入は'
      + '経済的公平性を築きます。マイノリティ'
      + 'ビジネスが人口比率に達すれば、'
      + '**757,000の新規事業**が生まれ、'
      + '630万の雇用と8,240億ドルの収益が'
      + '生まれる可能性があります'
      + '（[ブルッキングス]'
      + '(https://www.brookings.edu/articles'
      + '/reaping-the-unrealized-gains-of'
      + '-black-businesses/)）。'
      + 'マイノリティ経営のビジネスは既に年間'
      + '約**2兆ドルの収益**を生み出しています'
      + '（[SCORE](https://www.score.org)）。'
      + '意識的な消費は、経済的不平等を縮小する'
      + '最も直接的な個人の手段の一つです。',
    es:
      'Dirigir compras a negocios de '
      + 'minorias y comunidades '
      + 'subrepresentadas construye equidad '
      + 'economica. Si los negocios de '
      + 'minorias alcanzaran la paridad '
      + 'poblacional, podrian surgir '
      + '**757.000 nuevos negocios** con 6,3 '
      + 'millones de empleos y $824 mil '
      + 'millones en ingresos ([Brookings]'
      + '(https://www.brookings.edu/articles'
      + '/reaping-the-unrealized-gains-of'
      + '-black-businesses/)). '
      + 'Los negocios de minorias ya generan '
      + 'casi **$2 billones en ingresos '
      + 'anuales** '
      + '([SCORE](https://www.score.org)). '
      + 'La eleccion consciente del '
      + 'consumidor es una de las palancas '
      + 'individuales mas directas para '
      + 'reducir la desigualdad economica.',
  },

  citizen_science_project: {
    en:
      'Platforms like iNaturalist have '
      + 'gathered over **250 million '
      + 'observations** of wildlife worldwide, '
      + 'contributing to more than **5,000 '
      + 'peer-reviewed scientific papers** '
      + '([BioScience]'
      + '(https://academic.oup.com/bioscience'
      + '/article/75/11/953/8185761)). '
      + 'The 2025 City Nature Challenge '
      + 'mobilized **102,945 participants** '
      + 'across 669 cities in 62 countries, '
      + 'recording 3.3 million observations '
      + 'of over 73,000 species '
      + '([City Nature Challenge]'
      + '(https://www.citynaturechallenge'
      + '.org/)). '
      + 'A study in Nature Sustainability '
      + 'found that citizen scientists can '
      + 'help monitor **over half** of the '
      + '365 indicators in the UN Global '
      + 'Biodiversity Framework '
      + '([Nature Sustainability]'
      + '(https://www.nature.com/articles'
      + '/s41893-024-01447-y)). '
      + 'Every observation you log helps '
      + 'researchers track species, detect '
      + 'ecological change, and inform '
      + 'conservation policy.',
    ja:
      'iNaturalistなどのプラットフォームは'
      + '世界中で**2億5,000万件以上の生物'
      + '観察**を集め、**5,000本以上の査読'
      + '付き論文**に貢献しています'
      + '（[BioScience]'
      + '(https://academic.oup.com/bioscience'
      + '/article/75/11/953/8185761)）。'
      + '2025年のシティ・ネイチャー・'
      + 'チャレンジでは、62カ国669都市から'
      + '**102,945人**が参加し、73,000種'
      + '以上の330万件の観察が記録されました'
      + '（[City Nature Challenge]'
      + '(https://www.citynaturechallenge'
      + '.org/)）。'
      + 'Nature Sustainability誌の研究では、'
      + '市民科学者が国連生物多様性枠組みの'
      + '365指標の**半数以上**のモニタリング'
      + 'に貢献できることが示されています'
      + '（[Nature Sustainability]'
      + '(https://www.nature.com/articles'
      + '/s41893-024-01447-y)）。'
      + 'あなたの一つの観察が、種の追跡や'
      + '生態系変化の検出、保全政策の策定に'
      + '役立ちます。',
    es:
      'Plataformas como iNaturalist han '
      + 'reunido mas de **250 millones de '
      + 'observaciones** de vida silvestre en '
      + 'todo el mundo, contribuyendo a mas '
      + 'de **5.000 articulos cientificos** '
      + 'revisados por pares '
      + '([BioScience]'
      + '(https://academic.oup.com/bioscience'
      + '/article/75/11/953/8185761)). '
      + 'El City Nature Challenge 2025 '
      + 'movilizo a **102.945 participantes** '
      + 'en 669 ciudades de 62 paises, '
      + 'registrando 3,3 millones de '
      + 'observaciones de mas de 73.000 '
      + 'especies ([City Nature Challenge]'
      + '(https://www.citynaturechallenge'
      + '.org/)). '
      + 'Un estudio en Nature Sustainability '
      + 'demostro que los ciudadanos pueden '
      + 'ayudar a monitorear **mas de la '
      + 'mitad** de los 365 indicadores del '
      + 'Marco Global de Biodiversidad de la '
      + 'ONU ([Nature Sustainability]'
      + '(https://www.nature.com/articles'
      + '/s41893-024-01447-y)). '
      + 'Cada observacion que registras ayuda '
      + 'a rastrear especies, detectar '
      + 'cambios ecologicos e informar '
      + 'politicas de conservacion.',
  },

  volunteer_nature_walk: {
    en:
      'Guided nature walks connect '
      + 'communities with local ecosystems '
      + 'and inspire lasting environmental '
      + 'stewardship. A meta-analysis of '
      + '**169 studies** across 43 countries '
      + 'found that environmental education '
      + 'nearly doubled participants\' '
      + 'ecological knowledge and '
      + 'significantly increased pro-'
      + 'environmental behavior '
      + '([Journal of Environmental '
      + 'Psychology](https://doi.org/10.1016'
      + '/j.jenvp.2022.101782)). '
      + 'Organizations like The Nature '
      + 'Conservancy and the National Park '
      + 'Service rely on volunteers to run '
      + 'these walks -- the NPS alone engages '
      + 'nearly **300,000 volunteers** for '
      + 'over 6.5 million hours of service '
      + 'each year '
      + '([NPS](https://www.nps.gov/subjects'
      + '/volunteer/index.htm)). '
      + 'By volunteering, you help others '
      + 'build the emotional connection to '
      + 'nature that research shows is the '
      + 'strongest driver of lifelong '
      + 'conservation habits '
      + '([NEEF](https://www.neefusa.org'
      + '/what-we-do/k-12-education'
      + '/benefits-environmental-education)).',
    ja:
      'ガイド付き自然散策は地域社会と地元の'
      + '生態系をつなぎ、持続的な環境保全意識'
      + 'を育みます。43カ国**169件の研究**を'
      + '分析したメタアナリシスでは、環境教育が'
      + '参加者の生態学的知識をほぼ倍増させ、'
      + '環境配慮行動を有意に向上させることが'
      + '判明しました'
      + '（[Journal of Environmental '
      + 'Psychology](https://doi.org/10.1016'
      + '/j.jenvp.2022.101782)）。'
      + '米国国立公園局だけでも毎年約**30万人'
      + 'のボランティア**が650万時間以上の'
      + 'サービスを提供しています'
      + '（[NPS](https://www.nps.gov/subjects'
      + '/volunteer/index.htm)）。'
      + '自然散策のボランティアに参加することで、'
      + '生涯にわたる保全習慣の最も強い原動力と'
      + 'なる自然への感情的なつながりを他者に'
      + '築く手助けができます'
      + '（[NEEF](https://www.neefusa.org'
      + '/what-we-do/k-12-education'
      + '/benefits-environmental-education)）。',
    es:
      'Las caminatas guiadas por la '
      + 'naturaleza conectan a las '
      + 'comunidades con los ecosistemas '
      + 'locales e inspiran una conciencia '
      + 'ambiental duradera. Un metaanalisis '
      + 'de **169 estudios** en 43 paises '
      + 'demostro que la educacion ambiental '
      + 'casi duplico el conocimiento '
      + 'ecologico de los participantes y '
      + 'aumento significativamente su '
      + 'comportamiento proambiental '
      + '([Journal of Environmental '
      + 'Psychology](https://doi.org/10.1016'
      + '/j.jenvp.2022.101782)). '
      + 'Solo el Servicio de Parques '
      + 'Nacionales de EE.UU. moviliza casi '
      + '**300.000 voluntarios** que aportan '
      + 'mas de 6,5 millones de horas de '
      + 'servicio al ano '
      + '([NPS](https://www.nps.gov/subjects'
      + '/volunteer/index.htm)). '
      + 'Al ser voluntario en una caminata '
      + 'por la naturaleza, ayudas a otros '
      + 'a construir la conexion emocional '
      + 'con el entorno que, segun la '
      + 'investigacion, es el motor mas '
      + 'fuerte de habitos de conservacion '
      + 'de por vida '
      + '([NEEF](https://www.neefusa.org'
      + '/what-we-do/k-12-education'
      + '/benefits-environmental-education)).',
  },

  donate_women_climate_org: {
    en:
      'Only **0.2% of all foundation '
      + 'funding** goes to the intersection '
      + 'of women and the environment, '
      + 'despite women reinvesting up to '
      + '**90% of their income** back into '
      + 'families and communities '
      + '([Global Greengrants Fund]'
      + '(https://www.bothends.org/en'
      + '/Whats-new/News/Only-0-2-of-all'
      + '-foundation-funding-for-women'
      + '-environment/)). '
      + 'Women hold only **35% of national '
      + 'delegate seats** at UN climate '
      + 'negotiations, yet a 2024 study '
      + 'across 146 countries found that '
      + 'gender equality explains **86% of '
      + 'the variation** in climate '
      + 'adaptation readiness '
      + '([BMC Public Health]'
      + '(https://bmcpublichealth'
      + '.biomedcentral.com/articles'
      + '/10.1186/s12889-024-18880-5)). '
      + 'Organizations like Women\'s Earth '
      + 'Alliance have trained over '
      + '**52,000 women** in 31 countries '
      + 'to lead environmental justice '
      + 'projects since 2006 '
      + '([WEA](https://womensearthalliance'
      + '.org/)). '
      + 'Your donation directly empowers '
      + 'women-led climate solutions at the '
      + 'grassroots level, where they '
      + 'deliver outsized impact.',
    ja:
      '女性と環境の交差領域に向けられる助成金'
      + 'は全体のわずか**0.2%**に過ぎません。'
      + 'それにもかかわらず、女性は収入の最大'
      + '**90%**を家族やコミュニティに還元して'
      + 'います'
      + '（[Global Greengrants Fund]'
      + '(https://www.bothends.org/en'
      + '/Whats-new/News/Only-0-2-of-all'
      + '-foundation-funding-for-women'
      + '-environment/)）。'
      + '国連気候交渉における女性の代表は'
      + '**わずか35%**ですが、2024年の146カ国'
      + 'を対象とした研究では、ジェンダー平等が'
      + '気候適応力の差異の**86%を説明する**'
      + 'ことが判明しました'
      + '（[BMC Public Health]'
      + '(https://bmcpublichealth'
      + '.biomedcentral.com/articles'
      + '/10.1186/s12889-024-18880-5)）。'
      + 'Women\'s Earth Allianceは2006年以来、'
      + '31カ国で**52,000人以上の女性**に'
      + '環境正義プロジェクトの研修を実施して'
      + 'います'
      + '（[WEA](https://womensearthalliance'
      + '.org/)）。'
      + 'あなたの寄付は、最も大きなインパクトを'
      + '生む草の根レベルの女性主導の気候変動'
      + '対策を直接支援します。',
    es:
      'Solo el **0,2% de toda la '
      + 'financiacion de fundaciones** se '
      + 'destina a la interseccion entre '
      + 'mujeres y medio ambiente, a pesar '
      + 'de que las mujeres reinvierten '
      + 'hasta el **90% de sus ingresos** '
      + 'en sus familias y comunidades '
      + '([Global Greengrants Fund]'
      + '(https://www.bothends.org/en'
      + '/Whats-new/News/Only-0-2-of-all'
      + '-foundation-funding-for-women'
      + '-environment/)). '
      + 'Las mujeres ocupan solo el **35% '
      + 'de los puestos de delegadas** en '
      + 'las negociaciones climaticas de la '
      + 'ONU, pero un estudio de 2024 en '
      + '146 paises revelo que la igualdad '
      + 'de genero explica el **86% de la '
      + 'variacion** en la capacidad de '
      + 'adaptacion climatica '
      + '([BMC Public Health]'
      + '(https://bmcpublichealth'
      + '.biomedcentral.com/articles'
      + '/10.1186/s12889-024-18880-5)). '
      + 'Organizaciones como Women\'s Earth '
      + 'Alliance han capacitado a mas de '
      + '**52.000 mujeres** en 31 paises '
      + 'para liderar proyectos de justicia '
      + 'ambiental desde 2006 '
      + '([WEA](https://womensearthalliance'
      + '.org/)). '
      + 'Tu donacion impulsa directamente '
      + 'soluciones climaticas lideradas '
      + 'por mujeres a nivel comunitario, '
      + 'donde generan el mayor impacto.',
  },
};

module.exports = descriptions;
