/**
 * Long descriptions for eco-actions:
 * CONSUMPTION category (15 actions).
 *
 * Each description is 3-5 sentences with markdown
 * formatting, bold CO2 figures, and source links.
 *
 * This is a partial file merged into the final
 * descriptions module.
 */

const descriptions = {
  // -----------------------------------------------------
  // CONSUMPTION (15 actions)
  // -----------------------------------------------------
  reusable_bag: {
    en:
      'Each single-use plastic bag generates '
      + 'roughly **10g of CO2** across its '
      + 'lifecycle, from petroleum extraction '
      + 'through manufacturing to disposal. '
      + 'A [Danish EPA study]'
      + '(https://www2.mst.dk/udgiv'
      + '/publications/2018/02'
      + '/978-87-93614-73-4.pdf) found that '
      + 'a polypropylene reusable bag breaks '
      + 'even after just 10-45 uses depending '
      + 'on environmental metrics. '
      + 'Since most shoppers use hundreds of '
      + 'bags per year, switching to reusable '
      + 'bags compounds into significant '
      + 'savings over time.',
    ja:
      '使い捨てビニール袋1枚あたり、石油'
      + '採掘から製造・廃棄まで約**10gの'
      + 'CO2**が排出されます。'
      + '[デンマーク環境保護庁の研究]'
      + '(https://www2.mst.dk/udgiv'
      + '/publications/2018/02'
      + '/978-87-93614-73-4.pdf)によると、'
      + 'ポリプロピレン製のエコバッグは'
      + '10〜45回の使用で環境負荷を相殺'
      + 'できます。年間数百枚の袋を使う'
      + '買い物客にとって、エコバッグへの'
      + '切り替えは大きなCO2削減に'
      + 'つながります。',
    es:
      'Cada bolsa de plástico de un solo '
      + 'uso genera aproximadamente **10g de '
      + 'CO2** a lo largo de su ciclo de vida. '
      + 'Un [estudio de la EPA danesa]'
      + '(https://www2.mst.dk/udgiv'
      + '/publications/2018/02'
      + '/978-87-93614-73-4.pdf) encontró '
      + 'que una bolsa reutilizable de '
      + 'polipropileno compensa su impacto '
      + 'tras solo 10-45 usos. '
      + 'Como la mayoría de los compradores '
      + 'usan cientos de bolsas al año, el '
      + 'cambio a bolsas reutilizables '
      + 'genera ahorros significativos con '
      + 'el tiempo.',
  },

  reusable_cup: {
    en:
      'A single disposable coffee cup with '
      + 'its sleeve and lid produces roughly '
      + '**60g of CO2** when you factor in '
      + 'paper production, plastic lining, '
      + 'and disposal. According to the '
      + '[Carbon Trust]'
      + '(https://www.carbontrust.com/), '
      + 'a reusable cup breaks even after '
      + 'approximately 20-100 uses depending '
      + 'on the material. Daily coffee '
      + 'drinkers who switch to a reusable '
      + 'cup can avoid over 20kg of CO2 '
      + 'per year.',
    ja:
      '使い捨てコーヒーカップは、スリーブ'
      + 'と蓋を含めて約**60gのCO2**を'
      + '排出します。紙の生産、プラスチック'
      + 'コーティング、廃棄処理が要因です。'
      + '[Carbon Trust]'
      + '(https://www.carbontrust.com/)に'
      + 'よると、マイカップは素材により'
      + '20〜100回の使用で損益分岐点に'
      + '達します。毎日コーヒーを飲む人が'
      + 'マイカップに切り替えると、年間'
      + '20kg以上のCO2を削減できます。',
    es:
      'Un vaso desechable de café con su '
      + 'funda y tapa produce aproximadamente '
      + '**60g de CO2** considerando la '
      + 'producción del papel, el '
      + 'recubrimiento plástico y la '
      + 'eliminación. Según el '
      + '[Carbon Trust]'
      + '(https://www.carbontrust.com/), '
      + 'un vaso reutilizable compensa su '
      + 'impacto tras 20-100 usos según '
      + 'el material. Los bebedores diarios '
      + 'de café que usan su propio vaso '
      + 'pueden evitar más de 20kg de CO2 '
      + 'al año.',
  },

  reusable_water_bottle: {
    en:
      'Carrying a reusable water bottle '
      + 'instead of buying disposable ones '
      + 'saves about **160g of CO2 per '
      + 'day**, assuming two single-use '
      + 'bottles avoided. Each PET bottle '
      + 'generates roughly 80g of CO2 from '
      + 'resin production, molding, and '
      + 'transportation. The '
      + '[Carbon Trust]'
      + '(https://www.carbontrust.com/) '
      + 'notes that reusable bottles break '
      + 'even within 10-30 uses. Over a '
      + 'year, this daily switch prevents '
      + 'nearly 60kg of CO2 and hundreds '
      + 'of bottles from reaching landfills '
      + '([EPA WARM](https://www.epa.gov'
      + '/warm)).',
    ja:
      'マイボトルを持ち歩くだけで、使い捨て'
      + 'ボトル2本分に相当する1日あたり約'
      + '**160gのCO2**を削減できます。'
      + 'PETボトル1本の製造では、樹脂生産'
      + '・成形・輸送を含め約80gのCO2が'
      + '排出されます。[Carbon Trust]'
      + '(https://www.carbontrust.com/)に'
      + 'よると、マイボトルは10〜30回の'
      + '使用で環境負荷を相殺できます。'
      + '毎日続ければ年間約60kgのCO2を'
      + '防ぎ、数百本のボトルを埋立地から'
      + '守れます'
      + '（[EPA WARM](https://www.epa.gov'
      + '/warm)）。',
    es:
      'Llevar una botella reutilizable en '
      + 'lugar de comprar desechables ahorra '
      + 'unos **160g de CO2 al día**, '
      + 'suponiendo dos botellas de un solo '
      + 'uso evitadas. Cada botella PET '
      + 'genera aproximadamente 80g de CO2 '
      + 'por la producción de resina, el '
      + 'moldeo y el transporte. El '
      + '[Carbon Trust]'
      + '(https://www.carbontrust.com/) '
      + 'señala que las botellas '
      + 'reutilizables compensan su impacto '
      + 'en 10-30 usos. A lo largo de un '
      + 'año, este cambio diario evita casi '
      + '60kg de CO2 y cientos de botellas '
      + 'en vertederos '
      + '([EPA WARM](https://www.epa.gov'
      + '/warm)).',
  },

  bring_own_container: {
    en:
      'A single polystyrene takeout container '
      + 'accounts for roughly **100g of CO2** '
      + 'when you include raw material '
      + 'extraction, molding, and landfill '
      + 'decomposition. Bringing your own '
      + 'container eliminates this impact '
      + 'entirely with each use. The '
      + '[EPA WARM model](https://www.epa.gov'
      + '/warm) confirms that polystyrene '
      + 'avoidance yields strong per-unit '
      + 'carbon savings. Over a year of '
      + 'weekly takeout, this adds up to '
      + 'over 5kg of CO2 prevented.',
    ja:
      '発泡スチロール製テイクアウト容器は'
      + '1個あたり、原料採掘・成形・埋立'
      + '分解を含め約**100gのCO2**に相当'
      + 'します。マイ容器を持参すれば、'
      + '使用のたびにこの排出を完全に回避'
      + 'できます。[EPA WARMモデル]'
      + '(https://www.epa.gov/warm)でも、'
      + '発泡スチロールの回避は高い単位'
      + 'あたりの炭素削減効果があると確認'
      + 'されています。週1回の持ち帰りで'
      + '年間5kg以上のCO2削減になります。',
    es:
      'Un envase de poliestireno para '
      + 'comida para llevar representa '
      + 'aproximadamente **100g de CO2** '
      + 'incluyendo extracción de materias '
      + 'primas, moldeo y descomposición '
      + 'en vertederos. Traer tu propio '
      + 'envase elimina este impacto por '
      + 'completo en cada uso. El '
      + '[modelo EPA WARM](https://www.epa.gov'
      + '/warm) confirma que evitar el '
      + 'poliestireno produce un ahorro '
      + 'significativo de carbono por unidad. '
      + 'Con comida para llevar semanal, esto '
      + 'suma más de 5kg de CO2 al año.',
  },

  refuse_disposables: {
    en:
      'Refusing disposable straws, cutlery, '
      + 'napkins, and other single-use items '
      + 'today saves roughly **15g of CO2** '
      + 'from the petroleum-based '
      + 'manufacturing and disposal of these '
      + 'products. While each item is small, '
      + 'the [EPA WARM model]'
      + '(https://www.epa.gov/warm) shows '
      + 'that scaled avoidance of single-use '
      + 'plastics creates meaningful '
      + 'cumulative impact. Carrying a simple '
      + 'reusable kit with a spork and cloth '
      + 'napkin makes refusing easy. Over a '
      + 'year of daily refusals, this habit '
      + 'prevents over 5kg of CO2 and keeps '
      + 'hundreds of items out of landfills.',
    ja:
      '使い捨てストロー、カトラリー、'
      + 'ナプキンなどを断ると1日あたり約'
      + '**15gのCO2**を削減できます。'
      + '石油由来の製造・廃棄を回避する'
      + 'ためです。1つ1つは小さくても'
      + '[EPA WARMモデル](https://www.epa'
      + '.gov/warm)によると使い捨て'
      + 'プラスチックの回避は大きな累積'
      + '効果を生みます。スポークと布ナプ'
      + 'キンの簡単なマイセットを持ち歩けば'
      + '断るのも簡単です。毎日続ければ年間'
      + '5kg以上のCO2を防ぎ数百個のごみを'
      + '埋立地から守ります。',
    es:
      'Rechazar pajitas, cubiertos, '
      + 'servilletas y otros artículos '
      + 'desechables ahorra unos **15g de '
      + 'CO2** al día al evitar la fabricación '
      + 'y eliminación de productos derivados '
      + 'del petróleo. Aunque cada artículo es '
      + 'pequeño, el [modelo WARM de la EPA]'
      + '(https://www.epa.gov/warm) muestra '
      + 'que evitar plásticos de un solo uso '
      + 'genera un impacto acumulativo '
      + 'significativo. Llevar un kit '
      + 'reutilizable con cubiertos y '
      + 'servilleta de tela facilita el '
      + 'rechazo. En un año de hábito diario, '
      + 'se evitan más de 5kg de CO2 y '
      + 'cientos de artículos en vertederos.',
  },

  secondhand_clothing: {
    en:
      'Buying a secondhand garment instead '
      + 'of new avoids roughly **15,000g '
      + '(15kg) of CO2** from fiber '
      + 'production, dyeing, and global '
      + 'shipping. According to '
      + '[WRAP UK](https://wrap.org.uk/), '
      + 'extending a garment\'s life by just '
      + 'nine months reduces its carbon '
      + 'footprint by about 30%. The fashion '
      + 'industry accounts for roughly 10% '
      + 'of global carbon emissions, making '
      + 'secondhand shopping one of the '
      + 'highest-impact individual actions '
      + 'in the consumption category.',
    ja:
      '新品の代わりに古着を購入すると、繊維'
      + '生産・染色・国際輸送による約'
      + '**15,000g（15kg）のCO2**を回避'
      + 'できます。[WRAP UK]'
      + '(https://wrap.org.uk/)によると、'
      + '衣類の寿命をわずか9ヶ月延ばすだけ'
      + 'で炭素排出量を約30%削減できます。'
      + 'ファッション業界は世界の炭素排出量'
      + 'の約10%を占めており、古着の購入は'
      + '消費カテゴリにおいて最もインパクト'
      + 'の大きい個人行動の一つです。',
    es:
      'Comprar una prenda de segunda mano '
      + 'en lugar de nueva evita '
      + 'aproximadamente **15,000g (15kg) '
      + 'de CO2** de la producción de '
      + 'fibras, el teñido y el envío '
      + 'global. Según '
      + '[WRAP UK](https://wrap.org.uk/), '
      + 'extender la vida de una prenda '
      + 'solo nueve meses reduce su huella '
      + 'de carbono en un 30%. La industria '
      + 'de la moda representa alrededor '
      + 'del 10% de las emisiones globales '
      + 'de carbono, lo que convierte la '
      + 'compra de segunda mano en una de '
      + 'las acciones individuales de mayor '
      + 'impacto en la categoría de '
      + 'consumo.',
  },

  repair_item: {
    en:
      'Repairing a broken item instead of '
      + 'replacing it avoids roughly '
      + '**7,500g (7.5kg) of CO2** from '
      + 'new manufacturing, raw material '
      + 'extraction, and shipping. The '
      + '[WRAP UK](https://wrap.org.uk/) '
      + 'organization promotes repair as '
      + 'a key strategy in the circular '
      + 'economy. Extending a product\'s '
      + 'useful life reduces demand on '
      + 'resource-intensive supply chains '
      + '([Carbon Trust]'
      + '(https://www.carbontrust.com/)). '
      + 'From electronics to furniture, '
      + 'repair skills pay back in both '
      + 'carbon savings and money saved.',
    ja:
      '壊れた物を買い替えずに修理すること'
      + 'で、新品の製造・原料採掘・輸送に'
      + 'よる約**7,500g（7.5kg）のCO2**'
      + 'を回避できます。[WRAP UK]'
      + '(https://wrap.org.uk/)は修理を'
      + '循環型経済の重要な戦略として推進'
      + 'しています。製品の寿命を延ばすこと'
      + 'で資源集約型のサプライチェーンへの'
      + '需要を減らせます'
      + '（[Carbon Trust]'
      + '(https://www.carbontrust.com/)）。'
      + '家電から家具まで、修理スキルは'
      + 'CO2削減とお金の節約の両面で'
      + '見返りがあります。',
    es:
      'Reparar un artículo roto en lugar '
      + 'de reemplazarlo evita '
      + 'aproximadamente **7,500g (7.5kg) '
      + 'de CO2** de nueva fabricación, '
      + 'extracción de materias primas y '
      + 'envío. La organización '
      + '[WRAP UK](https://wrap.org.uk/) '
      + 'promueve la reparación como '
      + 'estrategia clave de la economía '
      + 'circular. Extender la vida útil '
      + 'de un producto reduce la demanda '
      + 'en cadenas de suministro '
      + 'intensivas en recursos '
      + '([Carbon Trust]'
      + '(https://www.carbontrust.com/)). '
      + 'Desde electrónicos hasta muebles, '
      + 'las habilidades de reparación '
      + 'generan ahorros tanto en carbono '
      + 'como en dinero.',
  },

  borrow_instead_buy: {
    en:
      'Borrowing a tool, appliance, or '
      + 'other item instead of buying new '
      + 'avoids roughly **8,000g (8kg) of '
      + 'CO2** from manufacturing and '
      + 'shipping. Most household tools are '
      + 'used for only 10-15 minutes across '
      + 'their entire lifetime '
      + '([European Environment Agency]'
      + '(https://www.eea.europa.eu/)). '
      + 'Borrowing maximises the useful life '
      + 'of items already produced and keeps '
      + 'demand for new manufacturing in '
      + 'check. Sharing networks and tool '
      + 'libraries are growing worldwide, '
      + 'making borrowing more convenient '
      + 'than ever.',
    ja:
      '工具や家電などを新品で買う代わりに'
      + '借りることで、製造・輸送による約'
      + '**8,000g（8kg）のCO2**を回避'
      + 'できます。家庭用工具の多くは生涯で'
      + 'わずか10〜15分しか使われません'
      + '（[European Environment Agency]'
      + '(https://www.eea.europa.eu/)）。'
      + '借りることで既に生産された物の有効'
      + '寿命を最大化し、新たな製造需要を'
      + '抑えられます。シェアリング'
      + 'ネットワークや工具ライブラリーが'
      + '世界中で広がり、借りることがかつて'
      + 'なく便利になっています。',
    es:
      'Pedir prestada una herramienta, '
      + 'electrodoméstico u otro artículo '
      + 'en lugar de comprar nuevo evita '
      + 'aproximadamente **8,000g (8kg) de '
      + 'CO2** de fabricación y envío. La '
      + 'mayoría de las herramientas del '
      + 'hogar se usan solo 10-15 minutos '
      + 'en toda su vida útil '
      + '([Agencia Europea de Medio '
      + 'Ambiente]'
      + '(https://www.eea.europa.eu/)). '
      + 'Pedir prestado maximiza la vida '
      + 'útil de artículos ya producidos '
      + 'y controla la demanda de nueva '
      + 'fabricación. Las redes de '
      + 'préstamo y bibliotecas de '
      + 'herramientas crecen en todo el '
      + 'mundo, haciendo que pedir '
      + 'prestado sea más fácil que '
      + 'nunca.',
  },

  plastic_free_hygiene: {
    en:
      'Choosing plastic-free hygiene '
      + 'products like bar soap, shampoo '
      + 'bars, and bamboo toothbrushes '
      + 'saves roughly **15g of CO2 per '
      + 'day** by eliminating the '
      + 'petroleum-based plastic packaging '
      + 'that wraps most bathroom products. '
      + 'A single plastic shampoo bottle '
      + 'takes 450-1,000 years to decompose '
      + '([EPA WARM](https://www.epa.gov'
      + '/warm)). Bar alternatives often '
      + 'last longer, use simpler '
      + 'ingredients, and ship more '
      + 'compactly. Switching your daily '
      + 'routine to package-free options '
      + 'compounds into several kilograms '
      + 'of CO2 savings per year.',
    ja:
      '固形石鹸・シャンプーバー・竹歯ブラシ'
      + 'などプラスチックフリーの衛生用品を'
      + '選ぶと、石油由来のプラスチック包装を'
      + '排除し1日あたり約**15gのCO2**を'
      + '削減できます。プラスチック製シャン'
      + 'プーボトル1本の分解には450〜1,000'
      + '年かかります'
      + '（[EPA WARM](https://www.epa.gov'
      + '/warm)）。固形タイプは長持ちし、'
      + '成分もシンプルで、よりコンパクトに'
      + '輸送できます。日々の習慣をパッケージ'
      + 'フリーに切り替えれば、年間数kgの'
      + 'CO2削減につながります。',
    es:
      'Elegir productos de higiene sin '
      + 'plástico como jabón en barra, '
      + 'champú sólido y cepillos de '
      + 'bambú ahorra aproximadamente '
      + '**15g de CO2 al día** al '
      + 'eliminar el empaque plástico '
      + 'derivado del petróleo que envuelve '
      + 'la mayoría de productos de baño. '
      + 'Una sola botella de champú '
      + 'plástica tarda 450-1,000 años en '
      + 'descomponerse '
      + '([EPA WARM](https://www.epa.gov'
      + '/warm)). Las alternativas en '
      + 'barra suelen durar más, usan '
      + 'ingredientes más simples y se '
      + 'envían de forma más compacta. '
      + 'Cambiar tu rutina diaria a '
      + 'opciones sin empaque se acumula '
      + 'en varios kilogramos de CO2 '
      + 'ahorrados al año.',
  },

  buy_bulk: {
    en:
      'Buying food or household items in '
      + 'bulk saves roughly **200g of CO2 '
      + 'per shopping trip** by reducing '
      + 'packaging per unit weight. '
      + 'Single-serve and individually '
      + 'wrapped items carry a '
      + 'disproportionate '
      + 'packaging-to-product ratio '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Bulk buying also reduces the '
      + 'frequency of shopping trips and '
      + 'their associated transport '
      + 'emissions. Bringing your own '
      + 'containers further eliminates the '
      + 'need for store-provided packaging.',
    ja:
      '食品や日用品のまとめ買いで、単位重量'
      + 'あたりの包装を減らし1回の買い物で約'
      + '**200gのCO2**を節約できます。'
      + '個包装や小分け商品は製品に対して不釣'
      + 'り合いな包装比率になっています'
      + '（[WRAP UK](https://wrap.org.uk/)）。'
      + 'まとめ買いは買い物の頻度も減らし、'
      + '移動に伴う排出の削減にもつながり'
      + 'ます。マイ容器を持参すれば店舗提供の'
      + '包装も不要になります。',
    es:
      'Comprar alimentos o artículos del '
      + 'hogar a granel ahorra '
      + 'aproximadamente **200g de CO2 por '
      + 'viaje de compras** al reducir el '
      + 'empaque por unidad de peso. Los '
      + 'productos de porción individual y '
      + 'envueltos por separado tienen una '
      + 'proporción desproporcionada de '
      + 'empaque respecto al producto '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'La compra a granel también reduce '
      + 'la frecuencia de viajes de compras '
      + 'y sus emisiones de transporte '
      + 'asociadas. Llevar tus propios '
      + 'envases elimina aún más la '
      + 'necesidad de empaque proporcionado '
      + 'por la tienda.',
  },

  donate_items: {
    en:
      'Donating a bag of usable items '
      + 'instead of discarding them prevents '
      + 'roughly **12,000g (12kg) of CO2** '
      + 'by extending product lifespans and '
      + 'displacing new manufacturing. The '
      + '[WRAP UK](https://wrap.org.uk/) '
      + 'circular economy model shows that '
      + 'reuse avoids the full production '
      + 'chain of replacement goods. '
      + 'Clothing, electronics, furniture, '
      + 'and household items all carry '
      + 'significant embedded carbon. A '
      + 'single donation run can have the '
      + 'same climate impact as weeks of '
      + 'dietary changes.',
    ja:
      'まだ使える物を捨てずに寄付すると、'
      + '製品寿命の延長と新品製造の代替に'
      + 'より1袋あたり約**12,000g（12kg）'
      + 'のCO2**を防げます。[WRAP UK]'
      + '(https://wrap.org.uk/)の循環型経済'
      + 'モデルによると、再利用は代替品の'
      + '生産チェーン全体を回避できます。'
      + '衣類・家電・家具・日用品のすべてに'
      + '大量の炭素が内包されています。1回の'
      + '寄付が数週間分の食生活の改善に匹敵'
      + 'する気候インパクトを持ちます。',
    es:
      'Donar una bolsa de artículos '
      + 'utilizables en lugar de '
      + 'desecharlos evita '
      + 'aproximadamente **12,000g (12kg) '
      + 'de CO2** al extender la vida útil '
      + 'de los productos y desplazar '
      + 'nueva fabricación. El modelo de '
      + 'economía circular de '
      + '[WRAP UK](https://wrap.org.uk/) '
      + 'muestra que la reutilización evita '
      + 'toda la cadena de producción de '
      + 'los bienes de reemplazo. Ropa, '
      + 'electrónicos, muebles y artículos '
      + 'del hogar contienen carbono '
      + 'incorporado significativo. Una '
      + 'sola donación puede tener el '
      + 'mismo impacto climático que '
      + 'semanas de cambios en la dieta.',
  },

  no_impulse_buy: {
    en:
      'Avoiding an unnecessary impulse '
      + 'purchase saves roughly **200g of '
      + 'CO2** that would have been emitted '
      + 'during production, packaging, and '
      + 'shipping. The '
      + '[Carbon Trust]'
      + '(https://www.carbontrust.com/) '
      + 'emphasizes that reducing overall '
      + 'consumption is one of the most '
      + 'effective climate strategies. '
      + 'Many impulse buys end up unused or '
      + 'discarded quickly, compounding '
      + 'the waste '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Pausing before purchasing is a '
      + 'simple but powerful habit for '
      + 'cutting personal emissions.',
    ja:
      '不要な衝動買いを避けることで、生産'
      + '・包装・輸送で排出される約**200g'
      + 'のCO2**を節約できます。'
      + '[Carbon Trust]'
      + '(https://www.carbontrust.com/)は、'
      + '全体的な消費の削減が最も効果的な'
      + '気候変動対策の一つだと強調して'
      + 'います。衝動買いの多くはすぐに未使用'
      + 'のまま廃棄され、無駄が拡大します'
      + '（[WRAP UK](https://wrap.org.uk/)）。'
      + '購入前に立ち止まることは、個人の'
      + '排出削減のためのシンプルで強力な'
      + '習慣です。',
    es:
      'Evitar una compra impulsiva '
      + 'innecesaria ahorra aproximadamente '
      + '**200g de CO2** que se habrían '
      + 'emitido durante la producción, el '
      + 'empaque y el envío. El '
      + '[Carbon Trust]'
      + '(https://www.carbontrust.com/) '
      + 'enfatiza que reducir el consumo '
      + 'general es una de las estrategias '
      + 'climáticas más efectivas. Muchas '
      + 'compras impulsivas terminan sin '
      + 'usarse o se descartan rápidamente '
      + '([WRAP UK](https://wrap.org.uk/)). '
      + 'Pausar antes de comprar es un '
      + 'hábito simple pero poderoso para '
      + 'reducir las emisiones personales.',
  },

  choose_minimal_packaging: {
    en:
      'Choosing products with minimal '
      + 'packaging saves roughly **50g of '
      + 'CO2** per purchase by reducing '
      + 'material production, printing, '
      + 'and waste processing. '
      + '[WRAP UK](https://wrap.org.uk/) '
      + 'reports that packaging accounts '
      + 'for a significant share of retail '
      + 'product emissions. Selecting loose '
      + 'produce, concentrated formulas, '
      + 'and refillable containers all '
      + 'contribute to lower impact '
      + '([Carbon Trust]'
      + '(https://www.carbontrust.com/)). '
      + 'Consumer demand for less packaging '
      + 'also drives industry-wide change.',
    ja:
      '包装の少ない製品を選ぶことで、材料'
      + '生産・印刷・廃棄処理の削減により'
      + '1回の購入あたり約**50gのCO2**を'
      + '節約できます。[WRAP UK]'
      + '(https://wrap.org.uk/)によると、'
      + '包装は小売製品の排出量のかなりの'
      + '割合を占めています。ばら売りの'
      + '青果・濃縮タイプ・詰め替え容器の'
      + '選択がすべて環境負荷の低減に貢献'
      + 'します'
      + '（[Carbon Trust]'
      + '(https://www.carbontrust.com/)）。'
      + '消費者が簡易包装を求めることは業界'
      + '全体の変革も促します。',
    es:
      'Elegir productos con empaque '
      + 'mínimo ahorra aproximadamente '
      + '**50g de CO2** por compra al '
      + 'reducir la producción de '
      + 'materiales, la impresión y el '
      + 'procesamiento de residuos. '
      + '[WRAP UK](https://wrap.org.uk/) '
      + 'informa que el empaque representa '
      + 'una parte significativa de las '
      + 'emisiones de productos minoristas. '
      + 'Seleccionar productos sueltos, '
      + 'fórmulas concentradas y envases '
      + 'rellenables contribuye a un menor '
      + 'impacto '
      + '([Carbon Trust]'
      + '(https://www.carbontrust.com/)). '
      + 'La demanda de menos empaque también '
      + 'impulsa cambios en toda la '
      + 'industria.',
  },

  used_car_purchase: {
    en:
      'Buying a quality used car instead '
      + 'of a new one avoids roughly '
      + '**3 tonnes of CO2** from vehicle '
      + 'manufacturing. Producing a new car '
      + 'generates 6-35 tonnes of CO2 '
      + 'before it ever hits the road, '
      + 'depending on the model '
      + '([IEA](https://www.iea.org/)). '
      + 'A well-maintained used vehicle '
      + 'extends the useful life of '
      + 'materials already extracted and '
      + 'processed. This is one of the '
      + 'single highest-impact consumer '
      + 'decisions you can make, rivalling '
      + 'years of dietary changes in a '
      + 'single choice.',
    ja:
      '新車の代わりに良質な中古車を購入'
      + 'すると車両製造による約**3トンの'
      + 'CO2**を回避できます。新車は走行前'
      + 'にモデルにより6〜35トンのCO2を'
      + '排出します（[IEA](https://www.iea'
      + '.org/)）。整備の行き届いた中古車は'
      + '既に採掘・加工された素材の有効寿命'
      + 'を延ばします。食生活の変化を何年も'
      + '続けるのに匹敵するほど1回の選択で'
      + '最もインパクトの大きい消費行動の'
      + '1つです。',
    es:
      'Comprar un coche usado de calidad '
      + 'en lugar de uno nuevo evita '
      + 'aproximadamente **3 toneladas de '
      + 'CO2** de la fabricación del vehículo. '
      + 'Producir un coche nuevo genera entre '
      + '6 y 35 toneladas de CO2 antes de '
      + 'salir a la carretera, según el modelo '
      + '([IEA](https://www.iea.org/)). '
      + 'Un vehículo usado bien mantenido '
      + 'extiende la vida útil de materiales '
      + 'ya extraídos y procesados. Es una de '
      + 'las decisiones de consumo con mayor '
      + 'impacto que puedes tomar, comparable '
      + 'a años de cambios en la dieta en una '
      + 'sola elección.',
  },
};

module.exports = descriptions;
